### ISSUE TITLE
Add world compatibility

### ISSUE THREAD

**Issue by spacephoton** [GenSpectrum/cov-spectrum-website#101]

**Comment by spacephoton** [comment]
Region = world

**Comment by spacephoton** [comment]
@chaoran-chen can we add World as a region instead of taking no country/region parameters? @tehwalris any disadvantages if we do it like this? 

Since world is basically a region

**Comment by chaoran-chen** [comment]
The database table has a region and a country column, i.e., each sequence is assigned to a region and a country. The parameters correspond to filter conditions and asking for the world means not setting the filters. Allowing "world" as a region wouldn't make sense.

**Comment by tehwalris** [comment]
Since Chaoran already said that it doesn't make sense on the API side, an alternative would be to have `Place` be a country, a region _or "World"_. Then in the API endpoints you don't add any query parameters if place/country is "World".
