### ISSUE TITLE
Frontend crash reporting

### ISSUE THREAD

**Issue by tehwalris** [GenSpectrum/cov-spectrum-website#103]
If the frontend crashes or errors are thrown, it would be very good to know. The easiest way is to use something like [Sentry](https://sentry.io/). It is a hosted service that's quite easy to use. We might need one of their paid plans. The main question is if we can use it for privacy reasons. There is a [self hosted version](https://develop.sentry.dev/self-hosted/), but that is difficult to deploy. There are also [ways to remove personal data](https://docs.sentry.io/platforms/rust/data-management/sensitive-data/) at various levels.

**Comment by tehwalris** [comment]
@chaoran-chen Can you check if this would be allowed from a privacy standpoint?

**Comment by tehwalris** [comment]
#104 is related to this.

**Comment by chaoran-chen** [comment]
I will find out about the privacy issues and move this issue (and #104) to the todo list again once it's clarified.
