### ISSUE TITLE
Combine export buttons together

### ISSUE THREAD

**Issue by tehwalris** [GenSpectrum/cov-spectrum-website#105]
Combine the new icon buttons (CSV and PNG export) and the old "Share" button into one new "Export" dropdown button. This requires changing the structure around `Widget` and similar internal components.

**Comment by chaoran-chen** [comment]
Hi @tehwalris, I just remembered this issue. Do you think that - in addition to writing the documentation which certainly has the highest priority - you will still have the time to resolve this issue? If not, could you please outline what you had in mind for the implementation?
