### ISSUE TITLE
Covspectrum is not working dec 25

### ISSUE THREAD

**Issue by FedeGueli** [GenSpectrum/cov-spectrum-website#1061]
It seems that Covspectrum is failing to load the data for any request today, also noticed by @shay671

**Comment by chaoran-chen** [comment]
Hi @FedeGueli, thank you very much for the report! I just fixed it. Many apologies for the downtime!

**Comment by shay671** [comment]
Thank you very much

**Comment by FedeGueli** [comment]
> Hi @FedeGueli, thank you very much for the report! I just fixed it. Many apologies for the downtime!

thank you very much!
