### ISSUE TITLE
VariantInternationalComparisonPlot: getPlacesMostVariantSamples/country selection is wrong

### ISSUE THREAD

**Issue by chaoran-chen** [GenSpectrum/cov-spectrum-website#113]
The default country selection is not working as intended. For B.1.1.7, the four countries with the most samples are UK, US, Germany, and Sweden. I'm however getting Belgium and the Netherlands.

![image](https://user-images.githubusercontent.com/18666552/116794732-90d89f80-aacf-11eb-91cd-2b733af86b78.png)

I suspect that this line is causing the bug: https://github.com/cevo-public/cov-spectrum-website/pull/110/files/ffa66d0967b927502f8982b327000189757992e9#r624163179

**Comment by spacephoton** [comment]
![image](https://user-images.githubusercontent.com/36269621/116808226-efd1ff00-ab37-11eb-8a6f-7bd0710c7130.png)

**Comment by chaoran-chen** [comment]
You have to look into the objects. One object can represent multiple samples:

![image](https://user-images.githubusercontent.com/18666552/116809422-3f1b2e00-ab3e-11eb-861f-11fe5b6ce4ef.png)

I.e., instead of counting the entries, the `count`-values have to be summed up.

This is based on how the API works (see https://github.com/cevo-public/cov-spectrum-docs/blob/develop/API.md#sample-new). UK sequenced >200k samples but only 1046 are unique with respect to the metadata we are using.

**Comment by spacephoton** [comment]
> You have to look into the objects. One object can represent multiple samples:
> 
> ![image](https://user-images.githubusercontent.com/18666552/116809422-3f1b2e00-ab3e-11eb-861f-11fe5b6ce4ef.png)
> 
> I.e., instead of counting the entries, the `count`-values have to be summed up.
> 
> This is based on how the API works (see https://github.com/cevo-public/cov-spectrum-docs/blob/develop/API.md#sample-new). UK sequenced >200k samples but only 1046 are unique with respect to the metadata we are using.

Makes sense!
Will fix, thank you! 👍
