### ISSUE TITLE
Smart ticks for week axis

### ISSUE THREAD

**Issue by tehwalris** [GenSpectrum/cov-spectrum-website#12]
Most of our plots have a time axis in weeks. I used `tickvals` so that there is a tick every week, which looks nice on most time scales. Without this Plotly chooses to place ticks very sparsely and at pretty random intervals.

The problem is that a tick for every week is too much if the plot contains lots of weeks (the labels become vertical and can even overlap). In addition every week is labeled with a year which uses tons of space, but the year only interesting for the boundary between two years, as well as maybe first and last data points of the whole plot.

Ideally we would:
- Show week ticks at uniform intervals
- Show one tick every week as long as that fits well
- Remove ticks "smartly" if we don't have space (keep first week, last week, and weeks near year changes)
- Hide the year on most ticks (show on first week, last week, and near year changes)

We might be able to find some good existing code to do this. Maybe there's a function for spacing weekly ticks in D3 or a related library.

**Comment by chaoran-chen** [comment]
Outdated - we don't use Plotly so much.
