### ISSUE TITLE
Show less mutations in deep focus

### ISSUE THREAD

**Issue by spacephoton** [GenSpectrum/cov-spectrum-website#120]
![image](https://user-images.githubusercontent.com/36269621/117155567-2a989900-adbd-11eb-8170-f5fe4f043424.png)

**Comment by tehwalris** [comment]
We could also put these in a card like everything else. That way the whole page won't get shifted down once the mutations load.

**Comment by chaoran-chen** [comment]
The mutations have been at the very bottom of the page for a while and I think that the long list is not disturbing. As this issue does not provide a concrete suggestion for improvement, I'll close it.
