### ISSUE TITLE
Partially outdated datasets when the server receives new data

### ISSUE THREAD

**Issue by chaoran-chen** [GenSpectrum/cov-spectrum-website#130]
Data are not loaded at the same time. Not only is the data fetching process not atomic, but some datasets (e.g., `wholeSampleSet`) are also fetched much less frequently than others (e.g., `variantSampleSet`).

Now that we update the data multiple times a day rather than twice a week, this is becoming an issue. When the data used by the application are not in sync, the shown values can be very wrong!

To fix it, a new endpoint was implemented in https://github.com/cevo-public/cov-spectrum-server/issues/23 ([documentation](https://github.com/cevo-public/cov-spectrum-docs/blob/develop/API.md#data-status)) that returns the timestamp of the last data update **in UTC time**. Two suggestions:

- Whenever the user performs an action, the web app checks the data update timestamp and reloads the page (or only the data) when the data were updated.
- Every minute, the web app checks the data update timestamp. When the data were updated, a non-removable overlay should be shown telling the user that we have new data and it should show a big refresh button.

The embed widgets are partially affected as well. Because the data are not fetched atomically, in rare cases (well, with sufficient visitors, it wouldn't be rare in absolute numbers..), it could also have loaded non-matching datasets. Could we implement that the embed widgets call the data-status endpoint after everything else is fetched and check?

**We can also first fix the first part (ignoring the widgets) as it is more likely! But the widgets will also need a quick fix because we should avoid showing wrong plots by any means!**

**That's just my first idea. Better suggestions are of course highly welcome!**

**In the near future, we should redesign the API so that every response contains the timestamp!**

**Comment by chaoran-chen** [comment]
506c59e08e5adce0936aa9aca556907ef1b574ac implemented a check scheduled for every 4 seconds in the ExploreFocusSplit. It does not resolve the issue for the widgets.

@tehwalris, @TKGZ: What do you think the best long-term solution should be?

**Comment by spacephoton** [comment]
I'm not quite sure, but I do feel like we shouldn't show an option to update the data to the user, and make it invisible from their point of view.

**Comment by tehwalris** [comment]
I agree with Michael that we should just reload the data without asking.

From a technical point of view I think we should:
- Check `getDataStatus` after each request instead of periodically
    - Faster reaction to bad data
    - No need to keep making requests when idle
    - We'll probably need to add a line to every function in `api.ts` to hook this in
- Check if `dataStatus.lastUpdateTimestamp` has changed, instead of comparing it to the page load time
    - Because the server and client clock might be badly synchronized
- Reload the whole page, instead of making the data reload
    - Simpler code

**Comment by chaoran-chen** [comment]
What's about "redesign the API so that every response contains the timestamp"? Would it be a better long-term solution? From the server-side, it can be implemented quite quickly.

For example:

```
{
    info: {
        apiVersion: 1,
        dataUpdateTimestamp: timestamp,
        errors: null
    },
    payload: <the original response>
}
```

We can also introduce versioning of the API. I can put the new API under `/api/v1/...` and keep the old endpoints at `/api/...` until we changed the frontend.

**Comment by chaoran-chen** [comment]
As discussed with @TKGZ and @ningxie1991 on Slack, it might be better if the app could silently update the data rather than asking the user to reload the page.
