### ISSUE TITLE
Visualize mutations

### ISSUE THREAD

**Issue by tehwalris** [GenSpectrum/cov-spectrum-website#131]
We currently show the mutations for a lineage as a list of items like `S:A570D (98.88%)`. The percentage represents the prevalence of this mutation within samples of this lineage. We could visualize this percentage in a bar blot instead. In addition we could visualize a second percentage: the percentage of sequences from other variants that contain this mutation. If we add this visualization, then we should probably move the whole mutation list into a card (and maybe a deep focus page). Here's a rough sketch of how this could look:

![PXL_20210520_093722241](https://user-images.githubusercontent.com/1489115/118956521-f6e27500-b95f-11eb-9b71-c977bb09e137.jpg)

**Comment by chaoran-chen** [comment]
I think the idea of the bar plot a lot! However, can we still somehow maintain an easy copy-pastable list of mutations as well?

Edit: Ah, or just make the data downloadable? Might be good enough.

**Comment by chaoran-chen** [comment]
This issue is now outdated. We have new visualizations for mutations.
