### ISSUE TITLE
Geographic visualization

### ISSUE THREAD

**Issue by spacephoton** [GenSpectrum/cov-spectrum-website#132]
- [x] Canton-level
- [ ] Global level
The libraries include cantons so won't have to build the map from scratch like with the Zip-code level.

@tehwalris if that's okay with you, I would like to do this one

**Comment by chaoran-chen** [comment]
To clarify: When talking about the global level, I didn't mean a global map. We have "division" information for many countries (e.g., states in the US, Bundesländer in Germany, cantons in Switzerland, etc.) and it would be great if we can have a map for the different countries.

**Comment by spacephoton** [comment]
Got it, so a local division for each.

**Comment by chaoran-chen** [comment]
Done.

It might be useful to have a world/continental map, but that will be the topic of another issue.
