### ISSUE TITLE
Add explanations of charts

### ISSUE THREAD

**Issue by spacephoton** [GenSpectrum/cov-spectrum-website#133]
- [ ] Add (?) next to the chart title that has a short description of what the chart does when user hovers over it.

**Comment by chaoran-chen** [comment]
Is hovering really a good choice? I have the feeling that many people will never find it.

Rather, I was thinking about doing it as it was done for the "transmission advantage"-plot. I.e., add the explanations right above the plot and make it expandable:

![image](https://user-images.githubusercontent.com/18666552/119127403-95d8a100-ba34-11eb-812d-aa2be5a3b19c.png)

**Comment by spacephoton** [comment]
The problem if we put too much text it becomes easily overwhelming

We can make the (?) button next to the title very obvious, I think people will notice it :)

**Comment by chaoran-chen** [comment]
@TKGZ, what do you think about moving the explanations of the transmission advantage plot to a new tab?

On the other hand, the current solution allows us to make screenshots that include the description. Hm..

**Comment by spacephoton** [comment]
That could be a good idea

When people make screenshots, wouldn't they explain things separately anyway? For example if you're including the screenshot in an article.

Also, I feel like using a little (?) is a better idea than having a new tab, what do you think? 

What about making tabs using icons instead of text? For example you'd have the little bar plot icon as a tab? 

> @TKGZ, what do you think about moving the explanations of the transmission advantage plot to a new tab?
> 
> On the other hand, the current solution allows us to make screenshots that include the description. Hm..
