### ISSUE TITLE
100.00% does not fit into the metrics

### ISSUE THREAD

**Issue by chaoran-chen** [GenSpectrum/cov-spectrum-website#149]
Could we please increase the width of the metrics by a little so that "100.00%" would fit?

Or should we rather always write "100%" instead of "100.00%"?

---

![image](https://user-images.githubusercontent.com/18666552/120100883-7253db80-c143-11eb-9569-42a237ee6bdc.png)

![image](https://user-images.githubusercontent.com/18666552/120100910-90b9d700-c143-11eb-97d1-1f26275e941b.png)

**Comment by spacephoton** [comment]
Let's do 100%! :)

**Comment by spacephoton** [comment]
since it's the only case where it's too long

**Comment by spacephoton** [comment]
I would choose a lighter color for the heatmap, but we can easily change later :)

**Comment by chaoran-chen** [comment]
Fixed in #243
