### ISSUE TITLE
Sequencing representativeness in Switzerland

### ISSUE THREAD

**Issue by chaoran-chen** [GenSpectrum/cov-spectrum-website#154]
**Aim**

I'm thinking about adding a deep focus page to the sequencing intensity box for Switzerland. The sequencing intensity plot shows us how consistent we sequence through time. The aim of the new widget is to help us analyze whether we sample representatively with respect to the cantons, age, and sex.

It should allow some slightly deeper analysis and, for example, not only answer the question "How representative did we sample w.r.t. the cantons?" but also "How representative did the cantons sample w.r.t. different age groups?"

**Idea**

An idea is to have the attributes division, age, and sex as checkboxes and the user can choose only one...

![image](https://user-images.githubusercontent.com/18666552/120331091-b5ea4900-c2ed-11eb-8edb-700c64eaaf1c.png)

or multiple:

![image](https://user-images.githubusercontent.com/18666552/120331681-52145000-c2ee-11eb-94a2-954490550523.png)

This will of course create a lot of bars but I think that it is still easy to understand and to use. If we allow all three to be checked, it would create about 500 rows.

**API**

(The required endpoints are not there yet but we have the data and can create them once we decided how the plot should look like.)

(@TKGZ, what do you think?)

**Comment by spacephoton** [comment]
Hard for me to say how useful this is but if researchers say they want this of course! :)

Are you thinking of putting it through a show more button like the others?

I was thinking, maybe we can move the interesting variants above since that is the first thing people interact with, and you can still see sequencing intensity on the first page. What do you think?

**Comment by chaoran-chen** [comment]
> I was thinking, maybe we can move the interesting variants above since that is the first thing people interact with, and you can still see sequencing intensity on the first page. What do you think?

Sure, we can try it out. But let's do it in another issue.
