### ISSUE TITLE
Large confidence interval causes case estimation plots to be badly scaled

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/cov-spectrum-website#159]
Case estimation plots seem to have an autoscale for the y-axis. Huge confidence intervals for the most recent estimates where there are few cases cause the axis to be scaled so that the scale is objectively bad, hiding most of the information, see here for example: 
![image](https://user-images.githubusercontent.com/25161793/120899811-d853cd80-c631-11eb-947d-fc46b0d21092.png)

To solve this, I would limit the autoscale to something like 2x max of the mean. This way the plot is much more informative. Cutting off confidence intervals is better than not displaying any real information other than the top of the confidence intervals.

Would have to be done here I think: https://github.com/cevo-public/cov-spectrum-website/blob/bf03be8cd85369b9880e19ba363ce4b5638adf5d/src/charts/EstimatedCasesChart.tsx#L142

**Comment by chaoran-chen** [comment]
I like the idea!

**Comment by corneliusroemer** [comment]
Beautiful, well done! I think my personal taste would be to scale it to 2x max rather than 3x max but that doesn't really matter ;)
![image](https://user-images.githubusercontent.com/25161793/121035107-da429b80-c7ad-11eb-90d5-19e8cc0607e3.png)
