### ISSUE TITLE
Color scheme

### ISSUE THREAD

**Issue by chaoran-chen** [GenSpectrum/cov-spectrum-website#16]
Hey @tehwalris and @TKGZ! Let's slowly (not urgent) start putting a color scheme together for the overall website and the plots.

Until now, I've been using the following colors for many variant plots (but not in this project): #0D4A70, #67916E, #1883C6, #99D9A4, and we could re-use them if you like.

Do you have experience in defining a color scheme for a website/plots? How many/which "types" of colors do we need?

**Comment by spacephoton** [comment]
Sounds good, would recommend using something like flatuicolors.com

**Comment by chaoran-chen** [comment]
https://color.adobe.com/ is also very cool

**Comment by chaoran-chen** [comment]
Suggestions for colors for plots:

- Primary: #1883C6 and #0D4A70
- Secondary: #99D9A4 and #67916E
- Tertiary: #FBA337 and #F18805

See: https://coolors.co/1883c6-0d4a70-99d9a4-67916e-fba337-f18805

We would need to derive more colors that fit and define a continuous color scale. I stated two similar colors per category so that the lighter color could e.g. be used for confidence intervals or when it serves more as background.
