### ISSUE TITLE
[Feature request] Add time of last data update

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/cov-spectrum-website#166]
Outbreak.info shows when the data was last updated. It'd be great to have the same feature on this website.
![image](https://user-images.githubusercontent.com/25161793/121060953-8e9aec80-c7c3-11eb-9478-755d4d18b54a.png)

**Comment by chaoran-chen** [comment]
This is a little difficult because we use multiple data sources which are updated at different times. We could easily show the time when something has been last updated but it would, for example, not mean that the latest GISAID data has been imported at that time.

**Comment by corneliusroemer** [comment]
I see. Which data sources do you use?
SPSP for Switzerland and GISAID for the rest? Or also Genbank?

As a start any update would be good. Maybe just GISAID? Depends where the
bulk of the data comes from.

**Comment by chaoran-chen** [comment]
We use GISAID, sequences produced by the Swiss SARS-CoV-2 Sequencing Consortium (S3C) before the release, additional metadata received from the BAG, case data from OWID, wastewater results produced by the Computational Biology group at ETHZ and medRxiv/bioRxiv abstracts.

We could create a "data status" page where we list all the datasets and when they were last updated.

**Comment by corneliusroemer** [comment]
Yes a data status page would be very cool. Though for a start either the Swiss and/or GISAID update should already provide most of the benefit.

**Comment by spacephoton** [comment]
@chaoran-chen would this be easy to include? What about putting it under the about page?

**Comment by chaoran-chen** [comment]
We would have to adapt Harvester (the program that is gathering data from the different sources) first to store the timestamp of the import. It's not exactly what the data-status endpoint currently returns.

I'll work on it when I have a little more time.
