### ISSUE TITLE
⭐ Looking for a New Logo

### ISSUE THREAD

**Issue by chaoran-chen** [GenSpectrum/cov-spectrum-website#167]
CoV-Spectrum is looking for a new logo! Launched in May 2021, CoV-Spectrum (https://cov-spectrum.ethz.ch) is helping scientists to identify and investigate variants of SARS-CoV-2 while making the data and results also available to the broader public.

The only requirement is that the logo should contain the name of the website. **The way to write the name is not fixed.** The current logo writes "covSPECTRUM", but otherwise, we tend to write "CoV-Spectrum". We are curious to see other variants.

Please send us your submission either here in this Github issue or by email to chaoran.chen@bsse.ethz.ch. An internal jury will make a pre-selection and put our favorites out for a public vote.

The artist of the winning submission will be acknowledged on our website and receive a small gift from Switzerland. If the person should come to Basel, Switzerland, we are also happy to provide a free tour ;)

**Comment by corneliusroemer** [comment]
You have a logo?

**Comment by chaoran-chen** [comment]
No, but I gave up...
