### ISSUE TITLE
Aliases need to be taken into account for (wildcard) searches

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/cov-spectrum-website#169]
It looks like you're not accounting for aliases in your queries at the moment.

The way pangolin nomenclature works, when a lineage gets more than 3 numbers, a new letter is assigned: B.1.617.2.1 -> AY.1

For logical consistency, this means two things:
1. You should forward queries for B.1.617.2.1 to AY.1 (this seems not to be the case so far)
2. Wildcard searches should yield results for any aliases that belong to sub-lineages: B.1.617* should not only count results for B.1.617.1, B.1.617.2 but also B.1.617.2.1 = AY.1

I really like the wildcard feature, since sometimes you just want to count the delta with sub-lineages, and not have to do two separate searches. But it could be that for full functionality of this feature you still need to add the alias redirection.

![image](https://user-images.githubusercontent.com/25161793/121790327-94873800-cbde-11eb-9fbd-b13ee65f9b90.png)
![image](https://user-images.githubusercontent.com/25161793/121790328-96e99200-cbde-11eb-9035-2ed687ec6dcb.png)

**Comment by chaoran-chen** [comment]
That sounds indeed useful! Do you know where I can find a list of aliases? Preferably in a machine-readable format under a stable URL

**Comment by corneliusroemer** [comment]
Found it, handily called `alias_key.json` - should probably invert keys and values for wildcard searches.

https://github.com/cov-lineages/pango-designation/blob/master/alias_key.json

**Comment by corneliusroemer** [comment]
This is exactly what you wanted, I think
![image](https://user-images.githubusercontent.com/25161793/121791042-da93ca00-cbe5-11eb-9cf6-ff38cebd9af0.png)

**Comment by chaoran-chen** [comment]
This looks great, thanks!

Do you have a suggestion on how we should deal with the XA lineage which is a "recombinant lineage with parental lineages B.1.1.7 and B.1.177" (https://cov-lineages.org/lineages/lineage_XA.html).

**Comment by corneliusroemer** [comment]
Tough one, but at this point not very important since there's only one recombinant alias with very few descendants.

I would just not treat it as an alias at all but as an entirely different clade. Otherwise we get double counting and things like that.

So we'd have three roots without parent: A, B and XA (plus any other recombinant lineages that may appear in the future).

Here you can see that A and B share a common ancestor but are not descendants of each other:
![image](https://user-images.githubusercontent.com/25161793/121813109-e7a6cc80-cc6a-11eb-87d0-830ee4ed9f66.png)
