### ISSUE TITLE
Show the full name of aliases

### ISSUE THREAD

**Issue by chaoran-chen** [GenSpectrum/cov-spectrum-website#170]
As discussed in #169, the pangolin lineage nomenclature knows aliases. For example, AY is an alias for B.1.617.2. (I will soon add an endpoint to fetch all available aliases.)

We should show the resolved full name of the lineages somewhere.

**Comment by corneliusroemer** [comment]
So cool! Well done
![image](https://user-images.githubusercontent.com/25161793/122105894-90932a00-ce19-11eb-9ffd-7fcf558c676a.png)
