### ISSUE TITLE
[Feature request] Allow immediate searching by pressing enter without requiring arrow down key

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/cov-spectrum-website#173]
When I enter a lineage like `B.1.1.7` in the search bar, I can't just press `Enter` to submit. This is contrary to usual conventions and reduces usability.

Two possible fixes (if you want to):
a. Do an implicit down arrow when enter is pressed in the search bar
b. Explicitly select the first suggestion by default and underline the first suggestion in blue

![image](https://user-images.githubusercontent.com/25161793/122102855-30e74f80-ce16-11eb-8d15-4ef43f269388.png)

**Comment by spacephoton** [comment]
@corneliusroemer I like this suggestion, thanks!

**Comment by spacephoton** [comment]
@corneliusroemer Couldn't find an obvious way to make it work with enter key, but it works with tab! Does this work for you? 😊

**Comment by spacephoton** [comment]
But I agree, enter is more intuitive.

**Comment by corneliusroemer** [comment]
Actually you can press enter and it will submit the currently gray lineage. It only doesn't work for *new selection*s, they are not autofilled.

In fact here's the configuration and you seem to have added the select on enter stuff. Just the new selection does not seem to combine with enter.
https://github.com/cevo-public/cov-spectrum-website/blob/62d4bb42b8e471e4b4690efe2549c2c1dfa37010/src/components/KnownVariantsList/KnownVariantsList.tsx#L190-L191

**Comment by chaoran-chen** [comment]
I'm rewriting the search feature.
