### ISSUE TITLE
Check "Estimated cases" calculation

### ISSUE THREAD

**Issue by michfuchs** [GenSpectrum/cov-spectrum-website#177]
![image](https://user-images.githubusercontent.com/9607008/122751359-f3f4e000-d28f-11eb-83da-fb36826ebe94.png)

The estimated value of the most recent datapoint seems to be quite random, often at the extreme (both high and low) end of the confidence interval. Looks buggy and unrealistic.

**Comment by spacephoton** [comment]
Thanks @michfuchs. @chaoran-chen what do you think?

**Comment by julianoes** [comment]
I was just confused by that as well:

![Screenshot from 2021-06-27 18-04-17](https://user-images.githubusercontent.com/1419688/123551481-3a57ac80-d772-11eb-84dd-c7615f509824.png)

**Comment by corneliusroemer** [comment]
It's a good feature in theory, in practice it needs more smoothing for countries other than UK/Denmark that sequence almost everything. Smoothing would need to be dynamic, quite tricky.

**Comment by chaoran-chen** [comment]
Hi everyone. Sorry for being so slow! The cutoff was indeed not implemented very nicely. It only checked that always 7 days worth of case data went into the smoothing but did not ensure that there are enough sequencing data. It is now fixed! (Online in <15 minutes.)

Thank you very much for creating this issue!
