### ISSUE TITLE
Make short bars in bar plots tappable above bar for mobile usability

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/cov-spectrum-website#178]
Short bars are currently not easily tappable, because one has to hit the small rectangle both horizontally and vertically.

It would be good, if it was possible to select bars at full height, no matter their height.

See screencast for illustration. Otherwise, mobile UX is already great!

https://user-images.githubusercontent.com/25161793/123266334-302c7880-d4fc-11eb-8058-51ca50ae518b.mp4

**Comment by spacephoton** [comment]
Thanks @corneliusroemer! The way they were implemented means there isn't an obvious way, but I will have another look :)

**Comment by chaoran-chen** [comment]
https://github.com/cevo-public/cov-spectrum-website/blob/92efa86ce8fe7128e9ccbc1adc0ce9be25b422e5/src/widgets/MetadataAvailabilityPlot.tsx#L89-L99

I found a way using the tooltip component (see code above). [See here (Metadata availability).](https://cov-spectrum.ethz.ch/explore/Switzerland/AllSamples/AllTimes/sequencing-coverage)

**Comment by spacephoton** [comment]
Woah @chaoran-chen !! I remember spending a lot of time a while ago and not figuring this out. Thanks!

**Comment by spacephoton** [comment]
@corneliusroemer fixed now with #180 ! :)

**Comment by corneliusroemer** [comment]
Wow, this is great! Thanks :)
