### ISSUE TITLE
Division maps

### ISSUE THREAD

**Issue by chaoran-chen** [GenSpectrum/cov-spectrum-website#179]
We talked about it so often but apparently, we never created an issue for it?

It would be great to have a map to visualize the prevalence (or absolute numbers) of the divisions in a selected country. It would be a replacement/alternative to the current geography table.

As for the map type, I like what the BAG uses on their dashboard: https://www.covid19.admin.ch/de/repro/val

![image](https://user-images.githubusercontent.com/18666552/123325838-cc747080-d538-11eb-8a17-dd9a2c53da62.png)

Finding the map data for all countries is certainly difficult but starting with a few countries and making the implementation easily extensible would be enough for now. For example, Switzerland, United States, and Germany (these are the three countries from which most of our users are from),

**Comment by corneliusroemer** [comment]
We can chat about this if you like. I know a bit about how outbreak.info
does it. They use GADM data. The biggest challenge they had was matching
GADM division names to GISAID division names, but it's a problem we can fix
in a way similar to how nextstrain canonicalises GISAID geonames.

**Comment by chaoran-chen** [comment]
Oh yes, sure! We would love to hear your input!
