### ISSUE TITLE
International comparison table: sorting feature

### ISSUE THREAD

**Issue by chaoran-chen** [GenSpectrum/cov-spectrum-website#191]
The user should be able to sort the international comparison table by the four columns. Currently, it's always sorted by the country name.

![image](https://user-images.githubusercontent.com/18666552/124351760-913f0500-dbfc-11eb-9c30-dbd7a868c839.png)

**Comment by corneliusroemer** [comment]
Where can I find this comparison table on the website?

**Comment by chaoran-chen** [comment]
Click on the "Show more" button of the international comparison plot :)

**Comment by anastasia-escher** [comment]
Should it be ascending or descending order for the last three columns?

**Comment by chaoran-chen** [comment]
It would be great if the user can change the order by clicking on the column name. The first click would sort the column in one way, and a second click would reverse the order.

By default, I suggest sorting them in ascending order.

**Comment by anastasia-escher** [comment]
Should country always be ascending (from "A" to "Z") or also switchable to descending (from "Z" to "A")?

**Comment by chaoran-chen** [comment]
I'd make it also switchable to be consistent with the other columns.

**Comment by corneliusroemer** [comment]
Oh yes, this feature would be amazing!
