### ISSUE TITLE
Wastewater heatmap: Fix left column when scrolling

### ISSUE THREAD

**Issue by chaoran-chen** [GenSpectrum/cov-spectrum-website#195]
The left column with the mutation names of the wastewater heatmap should be fixed during horizontal scrolling if the width of the screen is large enough. 

![image](https://user-images.githubusercontent.com/18666552/124727759-4a5c5280-df0f-11eb-817e-fff3d0bb70d6.png)

**Comment by chaoran-chen** [comment]
A possibly useful resource shared by @DrYak: https://css-tricks.com/a-table-with-both-a-sticky-header-and-a-sticky-first-column/

**Comment by DrYak** [comment]
Note, for this to work, the headers needs to be in the same table and put in &lt;TH> tags - so you can address them separately in the CSS and they are part of the same object.
(Currently, the header is in a separate table, with &lt;TD> tags)
