### ISSUE TITLE
Search: Accept comma-separated list

### ISSUE THREAD

**Issue by chaoran-chen** [GenSpectrum/cov-spectrum-website#198]
The user should be able to copy&paste a comma-sperated list of mutations into the search field. The list should then be parsed.

In pictures:

![image](https://user-images.githubusercontent.com/18666552/124828753-f6d21f00-df77-11eb-90b3-92c489b0f15e.png)

to

![image](https://user-images.githubusercontent.com/18666552/124828973-47497c80-df78-11eb-85a4-7edde4126013.png)

Open question: What if one of the mutations is in an invalid format?

**Comment by ningxie1991** [comment]
@TKGZ @chaoran-chen Could you please explain a bit the requirement logic behind the following function from VariantSearch? For example, why the condition `(!onePLAlreadySelected && isValidPangolinLineageQuery(query))`, etc. Thanks!

https://github.com/cevo-public/cov-spectrum-website/blob/601be84331101ef9d1f497fa1b41ddca7e332be5/src/components/VariantSearch/VariantSearch.tsx#L108-L125

**Comment by ningxie1991** [comment]
> The user should be able to copy&paste a comma-sperated list of mutations into the search field. The list should then be parsed.
> 
> In pictures:
> 
> ![image](https://user-images.githubusercontent.com/18666552/124828753-f6d21f00-df77-11eb-90b3-92c489b0f15e.png)
> 
> to
> 
> ![image](https://user-images.githubusercontent.com/18666552/124828973-47497c80-df78-11eb-85a4-7edde4126013.png)
> 
> Open question: What if one of the mutations is in an invalid format?

For the open question, we can check each item of the comma separated list and only map the valid ones into option tags, and then give a small error message for the invalid items on the list?

Question, should the parsing action happen after user enters or pastes a comma separated list and hit enter or just immediately after entering/pasting the list string?

**Comment by spacephoton** [comment]
Maybe we can do parsing after user presses space or comma? Since enter will submit the search request with the other pull request.

**Comment by spacephoton** [comment]
> @TKGZ @chaoran-chen Could you please explain a bit the requirement logic behind the following function from VariantSearch? For example, why the condition `(!onePLAlreadySelected && isValidPangolinLineageQuery(query))`, etc. Thanks!
> 
> https://github.com/cevo-public/cov-spectrum-website/blob/601be84331101ef9d1f497fa1b41ddca7e332be5/src/components/VariantSearch/VariantSearch.tsx#L108-L125

@chaoran-chen should know this one :)

**Comment by spacephoton** [comment]
Personally, I feel like we should just have it update the search results every time we add a mutation, without a search button.

**Comment by spacephoton** [comment]
And we were thinking eventually to have what you see on the right to be synced with what is in the search bar, for example, if you select a known mutation, the search bar automatically fills out. Right now, they are not in sync.

![CleanShot 2021-07-25 at 21 27 10@2x](https://user-images.githubusercontent.com/36269621/126910979-d08d6088-280a-4265-ae71-9eda9f2e9497.png)

**Comment by chaoran-chen** [comment]
Hi.

> @TKGZ @chaoran-chen Could you please explain a bit the requirement logic behind the following function from VariantSearch? For example, why the condition (!onePLAlreadySelected && isValidPangolinLineageQuery(query)), etc. Thanks!

A sample can have a lot of mutations but is assigned to (at most) one pangolin lineage. Therefore, the user should also only be able to filter for at most one pangolin lineage. The `!onePLAlreadySelected` clause makes sure that the search bar only suggests pangolin lineages if there isn't already a pangolin lineage in the search field.

> For the open question, we can check each item of the comma separated list and only map the valid ones into option tags, and then give a small error message for the invalid items on the list?

Sounds good!

> Question, should the parsing action happen after user enters or pastes a comma separated list and hit enter or just immediately after entering/pasting the list string?

Do you have a preference?

> Personally, I feel like we should just have it update the search results every time we add a mutation, without a search button.

I have a hard time judging whether that would be better. We can try it out. Would you like to create an issue for it?

> And we were thinking eventually to have what you see on the right to be synced with what is in the search bar, for example, if you select a known mutation, the search bar automatically fills out. Right now, they are not in sync.

Yep, that would be great! See #40.

**Comment by ningxie1991** [comment]
> Maybe we can do parsing after user presses space or comma? Since enter will submit the search request with the other pull request.

Which pull request is that? Right now enter only creates a tag in the input box. We have to click "Search" to trigger the action.
