### ISSUE TITLE
Alias translation is case sensitive

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/cov-spectrum-website#199]
While generally lower case in search input is interpreted as upper case, this is *not* the case for pango lineages, that need to be translated to an alias.

Entering `b.1.1.28.1` yields "no result", while `B.1.1.28.1` gives results. That's because `B.1.1.28.1` = `P.1`

![image](https://user-images.githubusercontent.com/25161793/124832486-0b64e600-df7d-11eb-99b9-0addb5676f40.png)

![image](https://user-images.githubusercontent.com/25161793/124832496-0e5fd680-df7d-11eb-8780-5a7b95fd1dc2.png)

Lower case yields no match: https://cov-spectrum.ethz.ch/explore/Switzerland/AllSamples/AllTimes/variants/json=%7B%22variant%22%3A%7B%22name%22%3A%22b.1.1.28.1%22%2C%22mutations%22%3A%5B%5D%7D%2C%22matchPercentage%22%3A1%7D

But turning the b from lower to upper case yields results: https://cov-spectrum.ethz.ch/explore/Switzerland/AllSamples/AllTimes/variants/json=%7B%22variant%22%3A%7B%22name%22%3A%22B.1.1.28.1%22%2C%22mutations%22%3A%5B%5D%7D%2C%22matchPercentage%22%3A1%7D

**Proposed fix**
Turn all input in the search box automatically to upper case in javascript. Alternatively, do the same in the backend when parsing URL query parameters. Should be a one-liner.

**Comment by chaoran-chen** [comment]
Thanks for reporting!

> Turn all input in the search box automatically to upper case in javascript.

That's not ideal because we usually write `ORF1a` with a lower-case a. But the problem should nonetheless be easy to fix :)

I consider it as a backend error because it should be case-insensitive whenever it makes sense.

**Comment by corneliusroemer** [comment]
Ah right, but that's the only exception. Easy to write a regex that just keeps the A of ORF1a lower case. Almost everything else should be canonicalised to upper case in the front end, no?
