### ISSUE TITLE
Initiate search with enter

### ISSUE THREAD

**Issue by chaoran-chen** [GenSpectrum/cov-spectrum-website#202]
The user should be able to perform a search by clicking on Enter.

I already tried to implement it yesterday. There is an `onKeyDown` event handler that can be used to get the Enter event. However, it wasn't obvious to me how we can find out whether the user clicked on Enter to select a suggestion or not.

(Thanks @corneliusroemer for the suggestion.)

**Comment by corneliusroemer** [comment]
> However, it wasn't obvious to me how we can find out whether the user clicked on Enter to select a suggestion or not.

Well, whenever there is a suggestion already selected and no text in the box it's a submission enter. Otherwise it's a select suggestion enter. That should cut it, shouldn't it?
