### ISSUE TITLE
Normalize mutation and lineage name

### ISSUE THREAD

**Issue by chaoran-chen** [GenSpectrum/cov-spectrum-website#204]
We should make sure that the pangolin lineage and mutation names are always presented in the same way with the right capitalization, etc.

Some useful functions already exist in `helpers/mutations` and `helpers/variant-selector`.

**Comment by chaoran-chen** [comment]
The new `/resource/reference-genome` endpoint ([documentation](https://github.com/cevo-public/cov-spectrum-docs/blob/develop/API.md#reference-genome)) gives us the sequence (both nucleotides and amino acids) of the reference genome. With this information, we can transform an input like `S:501Y` to `S:N501Y`.

**Comment by anastasia-escher** [comment]
Could you please explain in a bit more detail what should be done here?

**Comment by chaoran-chen** [comment]
Good question. I'll think about it and come back to you in a few days.

**Comment by chaoran-chen** [comment]
@anastasia-escher, I finally thought about this issue again. I'd suggest only changing the `VariantSelector.formatVariantDisplayName()` function to return normalized values.

- `pangoLineage`: upper-case
- `nextcladePangoLineage`: same like `pangoLineage` but with the extension ` (Nextclade)`
- `gisaidClade`: upper-case and with the extension ` (GISAID clade)`
- `nextstrainClade`: upper-case and with the extension ` (Nextstrain clade)`
- `nucMutations`: `<base in reference genome><position><optionally the queried base>`, all in upper-case
- `aaMutations`: `<gene name with correct capitalization>:<AA in reference genome><position><optionally the queried AA>`, AA have upper-case, gene names are listed in `ReferenceGenomeService.genes`
- `nucInsertions`: `ins_<position>:<query>`, the query should be in upper-case, the "ins_" prefix in lower-case
- `aaInsertions`: `ins_<gene name with correct capitalization>:<position>:<query>`, the query should be in upper-case, the "ins_" prefix in lower-case

The advanced queries should be ignored for now.

**Comment by chaoran-chen** [comment]
I think that the `ReferenceGenomeService` should provide all relevant information.
