### ISSUE TITLE
Filter out dates that lie in the future

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/cov-spectrum-website#208]
Gisaid apparently doesn't filter out dates from the future, something that obviously cannot be possible and is a clear labelling error.

It would thus be good if you could simply discount any data with sampling dates with 1d or less of publication date.

![image](https://user-images.githubusercontent.com/25161793/125445761-6a1fbd71-a20c-4b28-81f8-3f82e2fa137c.png)

Strain in this case: USA/ND-NDDH-02591/2021

**Comment by chaoran-chen** [comment]
I would like to keep the server returning everything and suggest that we do the filtering on the frontend side.

**Comment by corneliusroemer** [comment]
Sure, either way.

Filtering could include samples were collection and submission dates are <2 days as this is not possible and indication of some error. There's a French lab that simply dates everything a day before submission which screws everything up. Better to just exclude.

**Comment by chaoran-chen** [comment]
I think that we should only exclude samples from the future but not try to identify and exclude errors with heuristics based on the difference between sampling and submission date. It should be the task of GISAID to fix errors. Also, for some analyses, a date that is wrong by a week might not be a big issue. And, is it technically really impossible to sequence within two days?

**Comment by chaoran-chen** [comment]
This issue might be addressed as part of #106.

**Comment by corneliusroemer** [comment]
The fact is that GISAID doesn't really do this kind of stuff. See these issues: https://github.com/outbreak-info/outbreak.info/issues/385 https://github.com/outbreak-info/outbreak.info/issues/392

And especially a few wrongly labelled recent sequences can totally screw up the meaning of plots. But sure, it's hard to make a heuristic for this, other than samples coming from the future. Maybe same day.

Otherwise, it'd be maybe good to use an exclusion table. Nextstrain curates a table with samples that are problematic, for example. That could be used directly.

**Comment by chaoran-chen** [comment]
Is it still causing problems? If not, I would close the issue.

**Comment by corneliusroemer** [comment]
Haven't seen any problems on cov-spectrum, but that may be because you use filtered data from Nextstrain and we're now throwing out dates from the future? Could this be why the problem is solved? May still make sense to have a simple check and chuck out sequences from the future yourself so as not to rely on Nextstrain sanity checking?

**Comment by chaoran-chen** [comment]
The GISAID data are directly from the source and not coming from Nextstrain.

I checked the GISAID data and currently, there are no sequences dated in the future. Maybe GISAID implemented a filter?

**Comment by corneliusroemer** [comment]
Alright! In that case, sure let's close this if it's solved reliably by GISAID. No need to add unnecessary complexity.
