### ISSUE TITLE
Website down/doesn't load: white screen

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/cov-spectrum-website#209]
I tried loading the website on both my computer and my smartphone, with WIFI and mobile internet and it doesn't load. It's just a white screen. But not getting 404 either. Weird.
![image](https://user-images.githubusercontent.com/25161793/125863973-a97381d6-a0b1-4d8e-86c6-f2c33b88831b.png)

Tried on Brave, Safari, Chrome, nothing works.

**Comment by chaoran-chen** [comment]
I fixed it yesterday night. I think that it is because the storage of the server was full because of some large log files (and not so much storage overall).

**Comment by corneliusroemer** [comment]
Works again, thanks!
