### ISSUE TITLE
Optional log scaling in the "Estimated cases" plots?

### ISSUE THREAD

**Issue by gonnet** [GenSpectrum/cov-spectrum-website#211]
Hi,

Just wondering if, given the exponential nature of the data, it would be possible to either
- add an option, or
- make it the default

to show the data in the "Estimated cases" plots (e.g. at the top right [here](https://cov-spectrum.ethz.ch/explore/Switzerland/AllSamples/AllTimes/variants/json=%7B%22variant%22%3A%7B%22name%22%3A%22B.1.617.2%22%2C%22mutations%22%3A[]%7D%2C%22matchPercentage%22%3A1%7D)) using logarithmic scaling on the _y_-axis?

Many thanks and keep up the amazing work!
Pedro

**Comment by chaoran-chen** [comment]
Thanks for the suggestion, Pedro! I could imagine having it as an option!
