### ISSUE TITLE
[Feature suggestion] Allow queries to specify "all but lineage x"

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/cov-spectrum-website#212]
In the UK, Delta now represents 99.5% of all sequences. It would be interesting to see what the rest is.

However, I couldn't think of an easy way to search for sequences that are "all but Delta". This should be fairly simple to add to the query backend.

![image](https://user-images.githubusercontent.com/25161793/126525698-d0454f34-7d1a-496d-a3ff-265d16d2001e.png)

**Comment by chaoran-chen** [comment]
Related to #287
