### ISSUE TITLE
Long title in variant boxes expands poorly

### ISSUE THREAD

**Issue by spacephoton** [GenSpectrum/cov-spectrum-website#213]
<img width="378" alt="CleanShot 2021-07-22 at 20 58 08@2x" src="https://user-images.githubusercontent.com/36269621/126694360-0932b06a-ef27-464b-9586-0901975e87d2.png">

**Comment by chaoran-chen** [comment]
Do you have a solution a mind?

**Comment by spacephoton** [comment]
Maybe we can just hide overflow of title? or do you think important to see the whole title?

**Comment by chaoran-chen** [comment]
Without the full title, we wouldn't know which exact variant is meant and I believe that is important.

**Comment by chaoran-chen** [comment]
I think that @TKGZ found a good solution. That's how it looks now:

![image](https://user-images.githubusercontent.com/18666552/140661961-5b2309c7-f1bf-4376-89f6-b153be9a2193.png)
