### ISSUE TITLE
Variant search: "remove all" button not working property

### ISSUE THREAD

**Issue by chaoran-chen** [GenSpectrum/cov-spectrum-website#216]
The "x" at the right side of the variant search field to remove all input is not working properly. 

![image](https://user-images.githubusercontent.com/18666552/126907202-54c21f4c-7077-400e-a379-010278474714.png)

How to reproduce the error:

1. Open https://cov-spectrum.ethz.ch/
2. Enter in the variant search field "B.1.1.7"
3. Click on the remove all "x" button
4. Enter S:N501Y
5. Click on search

Instead of showing the page for the "S:N501Y" variant, it shows "B.1.1.7 + S:N501Y".

**Comment by ningxie1991** [comment]
Fixed in pull request #218, closing this issue.

https://github.com/cevo-public/cov-spectrum-website/blob/a714299c3789f11b2a60b467d2e897fe61f6696e/src/components/VariantSearch/VariantSearch.tsx#L271-L274
