### ISSUE TITLE
Time machine

### ISSUE THREAD

**Issue by chaoran-chen** [GenSpectrum/cov-spectrum-website#219]
I would find it cool to be able to go back in time and see how the world looked like on a particular day. We could contribute to that by providing a setting to use only sequences submitted before a certain date.

The backend should be easy to implement: we can add a submission date filter.

How could we design the frontend? @TKGZ, @ningxie1991

**Comment by spacephoton** [comment]
Why not just a selector from start to end date?

**Comment by chaoran-chen** [comment]
Where would you put that selector?

**Comment by ningxie1991** [comment]
Right now, users can use the mouse cursor to hover over the plots to see data on a certain day for a certain plot. Do you mean that we want to allow users to pick a day, and then all the information on the screen will just be from that one particular chosen day only?

I came across this covid data website before where there's a slide bar at the bottom of the diagram where user can slide to see the data changes as the days go by (kind of like a weather map). Maybe we can try something like this?
https://ourworldindata.org/grapher/stay-at-home-covid?time=2020-06-30

![2021-08-09_16-07-48](https://user-images.githubusercontent.com/3387698/128719997-5feeb525-d370-4a94-b251-138217cc35fc.gif)

**Comment by chaoran-chen** [comment]
No, I actually meant something else.

It is currently possible to choose a date range in the header (e.g., last 3 months) and if such a filter is set, only sequences with a sampling date in that time frame will be used. The sampling date in this case usually refers to the date on which the COVID-test was performed/the swap was taken from the patient.

It will however take some time until the test result is known and even more time until sequencing is performed and the results are known. The time machine should make it possible to use only the data that were available on a particular date.

**Comment by spacephoton** [comment]
> Where would you put that selector?

We could make this the overall selector for date on top of the page
