### ISSUE TITLE
CovSpectrum is down

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/cov-spectrum-website#227]
For some reason I get a white screen when loading cov spectrum on both my desktop and my mobile.

![image](https://user-images.githubusercontent.com/25161793/133644010-44a0ef99-14f4-4391-ab58-cd07fde3753b.png)

![image](https://user-images.githubusercontent.com/25161793/133644016-e6edc8a0-8694-4b4b-ad52-a771a6c6a36b.png)

**Comment by chaoran-chen** [comment]
The server's disk was full... Thanks so much for reporting! The website is online again.
