### ISSUE TITLE
[Feature request] Allow more fine-grained date filters

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/cov-spectrum-website#230]
It would be great if it was possible to zoom in to say the last 4 weeks. Right now the user can only choose between 4 possible date choices: `All times`, `2020`, `2021`, `Past 3 months`, `Past 6 months`

What are the reasons for having only those 5 options? As a quick fix, could we add past month and past 2 weeks? That should cover most use cases without requiring a sophisticated date picker (though that would be cool!).

![image](https://user-images.githubusercontent.com/25161793/134032949-f1bec254-832e-4704-ae8d-2a6e9b6603c1.png)

**Comment by chaoran-chen** [comment]
We are working on allowing the user to set arbitrary date ranges.
