### ISSUE TITLE
Liberia not available as a country

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/cov-spectrum-website#236]
When looking for Liberia, I noticed it's missing as a country. Could it be that you once populated the list of countries only with countries that had sequences at this point, and therefore miss out on countries that uploaded for the first time?

![image](https://user-images.githubusercontent.com/25161793/134697843-aa59eaab-f485-4728-8405-51d58cc30062.png)

**Comment by chaoran-chen** [comment]
Thanks for noticing! You are very right, that was the problem. I added Liberia and Niger. They should appear tomorrow afternoon after the daily data update.

**Comment by corneliusroemer** [comment]
Shouldn't you add all countries, even if they haven't added sequences yet? Or at least auto update countries? :)

**Comment by chaoran-chen** [comment]
There is a manually maintained table in which we fix the URL component so that it does not change if GISAID should decide to modify a country name. But it would be good to check if new countries are added from time to time.

![image](https://user-images.githubusercontent.com/18666552/134709606-7e38eb28-f281-4f74-9abe-1d9aaa80aa4d.png)

**Comment by corneliusroemer** [comment]
Which makes me wonder: is there a Github bot that periodically re-opens an issue? This issue should be reopened in say 2 weeks for a check.

**Comment by chaoran-chen** [comment]
I would assume that there is such a bot!

Liberia is now there, so I will close this issue. Maybe we will find a better solution after our API refactoring.

**Comment by corneliusroemer** [comment]
This PR should open an issue twice a month to remind you to check for new countries ;) 
https://github.com/cevo-public/cov-spectrum-website/pull/244
@chaoran-chen
