### ISSUE TITLE
Why do some queries crash the site - or is the backend down?

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/cov-spectrum-website#240]
This query causes a crash. Why's that the case? Or maybe is the server just sometimes down? When I do too many queries in a row? Something odd's going on.

https://cov-spectrum.ethz.ch/explore/World/AllSamples/AllTimes/variants/json=%7B%22variant%22%3A%7B%22name%22%3A%22B.1.617.2*%22%2C%22mutations%22%3A[%22S%3A222V%22%2C%22Orf1a%3A640D%22]%7D%2C%22matchPercentage%22%3A1%7D

**Comment by corneliusroemer** [comment]
Alright, I think the backend is down @chaoran-chen 
![image](https://user-images.githubusercontent.com/25161793/134782460-678e3831-f3f6-43ca-830e-4a2131380a36.png)

**Comment by chaoran-chen** [comment]
Do you have a script checking the website constantly, or are you just always on cov-spectrum? o.O

I am currently doing a `vacuum full` in the database and thought that Saturday evening would be the best time. I guess that we need to put #92 onto the agenda again.

**Comment by corneliusroemer** [comment]
Hah, well, I've been using cov-spectrum to help with checking pango lineage designations. It's very helpful. Although a few things could be a little UX friendlier. I'm tired of typing `B.1.617.2*,` 😄 
And I'd love to see the breakdown of mutations for my queries (not just for pango lineages).

Oh and nuc mutations would be amazing. That power feature I'm missing dearly.

**Comment by chaoran-chen** [comment]
It's online again. Sorry for the trouble!

**Comment by corneliusroemer** [comment]
No worries at all :)
