### ISSUE TITLE
[Feature request] Make URL parameters less escape-sequence-heavy

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/cov-spectrum-website#241]
As a power user, I sometimes like to write my queries directly in the URL bar to bypass frontend hassles.

However, I've noticed that the URL queries are very escape sequence heavy, as follows: `/json=%7B"variant"%3A%7B"mutations"%3A["S%3A222V"]%7D%2C"matchPercentage"%3A1%7D`

It'd be nice if the queries didn't contain escape characters. After all, you're not accepting any sort of strings but are passing well-defined parameters. So you can write your own proper encoding. Or probably better, there are libraries for this. Have a look at what Auspice uses for example, much cleaner and nicer on the eye to understand what's going on:
`https://nextstrain.org/groups/neherlab/ncov/europe/2021-08-30?branchLabel=aa&c=gt-S_123,1&l=unrooted&m=div`

Here's how you could rewrite your query parameters (proposal):
`/json=variant&mutations=S_A222V&matchPercentage=1`

Isn't this much cooler than the above mess? I like to see what the query is in the URL bar and you're just making my life hard in this respect ;) 

I think the root cause is that you pass a single string as query parameter, rather than multiple query parameters. It's a shortcut that may have been good in the early days to save time, but for a maintained web app it's a bit, hmm, ugly :)

**Comment by chaoran-chen** [comment]
You could write a short script to generate or decode the URLs ;)

This is certainly a good idea but I'm afraid that it will take quite some effort and won't enjoy a high priority for a while.

**Comment by corneliusroemer** [comment]
If you tell me what needs to be done I can have a look.

You're thinking of a thin encoder/decoder that gets added between frontend to URL to encode and a decoder on your backend to decode?

If you point me where it would make sense to slot these in, I can take a stab. Don't know your code base at all :)
