### ISSUE TITLE
Get list of contributors

### ISSUE THREAD

**Issue by chaoran-chen** [GenSpectrum/cov-spectrum-website#245]
The user should be able to download a list of contributors that contributed to the sequences of a variant. I suggest adding a button somewhere in the top area of the focus page. The list should be formatted as a CSV file with the fields `gisaid_epi_isl, submittingLab, originatingLab, authors`.

The corresponding API is part of LAPIS.

**Comment by corneliusroemer** [comment]
Just a small note on nomenclature: I think most people reserve variant for lineages with functionally significant behaviour. The broader term is lineage (it means it started from one ancestor). So pango lineages are all lineages, but one probably wouldn't call them variants, apart from the significant ones (Alpha, Beta, Gamma, etc.).

When doing queries like Delta + S:613H it's not even a lineage, since it may contain multiple independent occurences of the mutation. Hope that's useful.

**Comment by chaoran-chen** [comment]
Hm, but how would you call "Delta + S:613H" or some random combination of mutations? Just a "set of sequences"?

On the top left of the page, we currently write "Which variant would you like to explore?" - how would you reframe it?

**Comment by corneliusroemer** [comment]
If you query single AA mutations, that's often not enough to make it monophyletic, so I'd indeed call it just "set of sequences" or "lineage*s* with S:613H" - plural being important here. Once you add many mutations, it does become more likely monophyletic, but the transition is blurry, so not easy for nomenclature.

It'd be better technically to call it "Which lineage would you like to explore". If you have a query of lineage + mutation, it's still a lineage, or a set of daugther lineages - whereas if it's just a mutation you'd explore a mutation. Maybe @emmahodcroft has some opinions on this. Let's see whether she responds ;)

**Comment by emmahodcroft** [comment]
Personally I'd call any set of sequence with defining mutations a variant, even if it's unknown if they are functionally significant. There are lot of strong views on nomenclature, but I think usage is too diverse to put too much stock in any of them. The only one I try to stay away from is "strain" as I do think this has more "significant" connotations around a definable change (antigenic, functional, etc). I regularly use variant to describe any set of sequence defined by mutations in my talks and the like.

**Comment by emmahodcroft** [comment]
(Indeed, on Co _Variants_, I make no claim as to whether they are measurably different outside of their mutations!)
