### ISSUE TITLE
Questionable choice, given time filters exist: date ranges are clipped

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/cov-spectrum-website#246]
When I look at lineages that are rare in a given country, and I use a filter of say last 6 months, I'd expect the frequency plot to show data for _all_ of the past 6 months.

What happens in fact is that the min and max date are chosen by the first and last occurence of the lineage. This is potentially misleading. If it hasn't been observed for a long time, shouldn't one show that? If it only popped up in the last month and I select 6 months, should I not see 5 months of 0 and only then bars, rather than bars for 4 weeks?

![image](https://user-images.githubusercontent.com/25161793/135835545-be6418f8-b711-4a2c-af00-45222ecd1e41.png)

This ties in with a bigger question of how to show uncertainty due to small, irregular sampling. I feel that outbreak.info does overall a better job (though it has a few quirks that you could iron out).

I do think it'd help to have some sort of error bar to indicate when there was sampling and when there was none. In the case of Morocco this is very necessary, but even for countries like Germany it'd help to see at a glance how certain or not the most recent week's data is.

I find this plot extremely well made, showing not only the sample average, but also a confidence interval AND the number of samples per day as a bar chart at the very bottom.

![image](https://user-images.githubusercontent.com/25161793/135836494-9de1e9c5-535c-461d-8d15-022b07dbe7ed.png)

**Comment by chaoran-chen** [comment]
Hi. Does GenSpectrum/cov-spectrum-website#106 cover the first issue?

With respect to the error bars: What do you think would be a good visualization that fits cov-spectrum?

**Comment by chaoran-chen** [comment]
The date part was fixed in GenSpectrum/cov-spectrum-website#264.

The error bars belong to a new issue.

**Comment by corneliusroemer** [comment]
Error bars are mentioned in GenSpectrum/dashboards#62
