### ISSUE TITLE
[Feature request] Enable country plots, similar to region plots

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/cov-spectrum-website#248]
I'm wondering why there are no country plots, similar to these region plots. The regions are cool, but the countries would be even more useful! Yes, there's the international comparison panel, but it's limited to 6 countries and it's all in one, vs. lots of plots at one glance. Adding country plots just the same way you're doing regions would really be a new cool power feature. And it shouldn't require almost any coding! I'd love the feature in any case ;)

![image](https://user-images.githubusercontent.com/25161793/135902557-6dde0cca-f58a-4b88-97aa-b91ebbf907b7.png)

**Comment by chaoran-chen** [comment]
I like the idea. What we could do is that, whenever a region (Europe, NA, ...) is selected, we show a "Show countries" button instead of "Show regions" - and whenever the world is selected, we can show the "big regions" rather than the sub-regions.

**Comment by corneliusroemer** [comment]
Hmm, I think that countries are much more useful than continents. Continents are few, and not homogeneous. Countries are more homogeneous and useful to spot patterns of frequencies going up and down. So I'd just do countries for now.

When one is in a country (by query) one could show regions for that country only.

Do it as you may though, as long as there's a big nice list of all countries and their frequencies I'm happy. If I have to go to world to see it, so be it. Would just be a shame if I could never see all countries over the world in one click. Right now, I can see all regions over the world, which is maybe overload for regions, but not for countries.

Is there harm in having two buttons: regions and countries? Don't think so!

**Comment by corneliusroemer** [comment]
Any progress here @chaoran-chen ? I'd love this feature, countries would be more useful than regions in my eyes (at least for most use cases, regions are very rarely useful for most countries, only maybe states in US, regions in UK, and Germany, in other countries it's too much of a mess)

**Comment by chaoran-chen** [comment]
Enjoy! :) https://cov-spectrum-develop-git-lapis-and-refactoring-cov-spectrum.vercel.app/explore/World/AllSamples/AllTimes/variants?pangoLineage=AY.4

![cov-spectrum country plots](https://user-images.githubusercontent.com/18666552/137770712-d369f679-cc65-41b9-ac48-6ce87e3dc20a.png)

**Comment by corneliusroemer** [comment]
You're an absolute star @chaoran-chen !

**Comment by corneliusroemer** [comment]
If you can now do something similar for the 40 or so most common lineages or so :)
