### ISSUE TITLE
[Performance] Website data transfer is extremely slow and it's not my download speed

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/cov-spectrum-website#251]
covSPECTRUM loads extremely slowly at the moment. My internet connection is fast. But the download of chunked JS files is pathetically slow. Why is that? 14s for a chunked .js file?

![image](https://user-images.githubusercontent.com/25161793/136459765-6c3e20e1-6dd9-4e07-a994-914045177dd6.png)

![image](https://user-images.githubusercontent.com/25161793/136459767-c38a94c7-999f-443e-a807-ef8efa5f9034.png)

**Comment by chaoran-chen** [comment]
For how long was it slow? Now, it should be okay again?
