### ISSUE TITLE
'Add mutations' button needed

### ISSUE THREAD

**Issue by FedeGueli** [GenSpectrum/cov-spectrum-website#252]
Two  issues ' IF' you could address

I will find very useful if after completing one research, example S: N679K then i could restrict further that research to one or plus more mutations.

Same story for lineageas: 
example
i was looking at S: N679K , wow it is in P.1.12, but look!
it is also in AY. lets me see where and what is that Ay. +N679K.

Actually to do that on mobile i have to go back.and restart the research.

Not  big issues both of them!

Thx for your work 🙏

**Comment by corneliusroemer** [comment]
Basically, the current query should be pre-filled in the query entry field, if I understand the request correctly.

I agree this would be useful for usability.

**Comment by chaoran-chen** [comment]
Hi @FedeGueli, thanks for reaching out!

For desktop, would #40 be helpful?

For mobile, we might need to think about a better concept that does not require the user to go back every time.

**Comment by FedeGueli** [comment]
Thank you!!

**Comment by chaoran-chen** [comment]
I think that these issues have been resolved by now. If not, please re-open :)

**Comment by FedeGueli** [comment]
Yes thx sorry i didnt close b4. Great work
