### ISSUE TITLE
Insertions and stop codons

### ISSUE THREAD

**Issue by c19850727** [GenSpectrum/cov-spectrum-website#253]
Hi there, a newbie question:

If for example I need to search "Spike_ins145N" or "NS8_Q27stop" in Cov-Spectrum, what do I need input for deletion and stop codons?

Thanks!

Sakaguchi

**Comment by chaoran-chen** [comment]
Hi @c19850727! Deletions are encoded as `-` (example: `S:69-`) and stop codons are encoded as `*` (example: `ORF9b:86*`). It is unfortunately not possible to search for insertions yet.

**Comment by c19850727** [comment]
@chaoran-chen Thanks!
