### ISSUE TITLE
Country missing: South Sudan

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/cov-spectrum-website#254]
Even though South Sudan has sequences on GISAID, South Sudan doesn't appear in cov-spectrum. Please add all countries there are in the world to prevent this ;)

**Comment by chaoran-chen** [comment]
https://cov-spectrum-develop-git-lapis-and-refactoring-cov-spectrum.vercel.app/explore/South%20Sudan/AllSamples/AllTimes/variants?pangoLineage=B.1.617.2* - coming soon!
