### ISSUE TITLE
Performance: Backend very slow, request takes 30+ seconds

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/cov-spectrum-website#255]
Simple request takes 30+ seconds, is this expected?
![image](https://user-images.githubusercontent.com/25161793/136983342-ff0b840b-b79e-44df-a3bb-5603b20c72e9.png)
https://cov-spectrum.ethz.ch/explore/Europe/AllSamples/AllTimes/variants/json=%7B%22variant%22%3A%7B%22name%22%3A%22AY.33%22%2C%22mutations%22%3A[]%7D%2C%22matchPercentage%22%3A1%7D

**Comment by chaoran-chen** [comment]
Now it's quick again. This time, I also noticed that the performance has dropped but I don't know why. There was no increased traffic and no error messages in the server log. Both the server program and the database are running in VMs on shared hosts, so there are a lot of other factors that may impact the performance of cov-spectrum.

**Comment by corneliusroemer** [comment]
Maybe much traffic? Maybe add logging of the time takes to complete
requests, and then dig a bit deeper?

**Comment by chaoran-chen** [comment]
I can see the number of requests in the server logs and during the performance drop in the afternoon, I was monitoring it live. There wasn't any increased traffic to cov-spectrum. Maybe there was more traffic on other VMs of the same host or issues with the network (...) but I can't investigate it myself. If the problem occurs often, I will have to ask for assistance.

**Comment by corneliusroemer** [comment]
Can you log how long requests take to complete so that we know how often this occurs?

**Comment by chaoran-chen** [comment]
There are some general server issues that I can't fix right now. Let's wait a bit and re-open if it does not improve.
