### ISSUE TITLE
Feature request: number of cases stats/plot

### ISSUE THREAD

**Issue by rkdover** [GenSpectrum/cov-spectrum-website#257]
Hi, first of all thank you for this excellent tool. It is really helping us keep track of which variants to look for in our clinical work here in Sweden.

One thing I seem to always be missing when on cov-spectrum is an absolute number of cases for a given variant, and I tend to get it by downloading the "sequences over time" data and summing it in excel. Could this be done? I looked through some earlier issues here and it seems to have been mentioned but it seems people are referring to this:

![image](https://user-images.githubusercontent.com/54945737/137269195-f16ce589-c90d-4c8d-afbf-9448f9aa5fa0.png)

which appears to be showing daily cases, or at least doesn't match the numbers found in GISAID or obtained by the method I mentioned. Just a number of total known cases would be great, but the possibility to plot cumulative known cases over time would be even better. Thanks for your work!

**Comment by chaoran-chen** [comment]
Hi @rkdover! I like the idea a lot! Thank you.

**Comment by chaoran-chen** [comment]
Hi @rkdover. Is that what you have envisioned?

![image](https://user-images.githubusercontent.com/18666552/138717125-06867013-d4a1-4f87-8044-f7e06fb3b35a.png)

**Comment by rkdover** [comment]
Looks great! This will be useful, thank you!

Might be useful to add a graph adding a time dimension at some point as well, but it could be a separate issue. I can start thinking about how it could look, if you don't mind.

**Comment by chaoran-chen** [comment]
I'm not sure what you mean, but yes, you are very welcome to open a new issue!
