### ISSUE TITLE
Page not loading in Safari - invalid date range regex

### ISSUE THREAD

**Issue by chaoran-chen** [GenSpectrum/cov-spectrum-website#258]
The whole website does not work in (at least some versions of) Safari. It just shows a blank page. I tracked down the problem to the following code block:

![image](https://user-images.githubusercontent.com/18666552/137472305-87324fe5-649b-4114-9891-c61e618f399d.png)

![image](https://user-images.githubusercontent.com/18666552/137472291-6e0d0807-d8bd-44ef-ac92-e94f32e5b7d4.png)

(Thanks @laduplessis for reporting!)

**Comment by ningxie1991** [comment]
https://stackoverflow.com/questions/63716837/javascript-regex-safari-issue
https://stackoverflow.com/questions/51568821/works-in-chrome-but-breaks-in-safari-invalid-regular-expression-invalid-group
