### ISSUE TITLE
Chart library

### ISSUE THREAD

**Issue by chaoran-chen** [GenSpectrum/cov-spectrum-website#27]
Hi @TKGZ and @tehwalris. How do you feel about the Plotly library we currently are using? Do you like it? Would you like to use it as the main library for common charts or do you have another preference?

Anything else you would like to discuss about plotting?

(I don't have any preferences.)

**Comment by spacephoton** [comment]
I think we can keep using it since it's well documented, we cna always switch later

**Comment by chaoran-chen** [comment]
It was decided to use recharts.
