### ISSUE TITLE
New Nextstrain integration

### ISSUE THREAD

**Issue by chaoran-chen** [GenSpectrum/cov-spectrum-website#272]
The old Nextstrain integration was removed in #264.

![image](https://user-images.githubusercontent.com/18666552/137744248-c28b7a25-5828-446f-b87b-344da6e97928.png)

It only supported Switzerland using the `/groups/swiss/ncov/switzerland` build. Shall we decide to bring the feature back, it should support more countries.

**Comment by corneliusroemer** [comment]
That's easy to do, we have loads of countries now. You can find the links here:
It'd be cool if highlighting was automatically enabled based on the pango lineage/mutations. I can help if you need to know what to add as query variables.

Here you can find all available datasets:
https://nextstrain.org/charon/getAvailable?prefix=/groups/neherlab/
