### ISSUE TITLE
Search Nextclade pango lineage, nextstrain clade and GISAID clade

### ISSUE THREAD

**Issue by chaoran-chen** [GenSpectrum/cov-spectrum-website#274]
~Is there any reason why we shouldn't make it possible to search for Nextstrain and GISAID clades in addition to the pango lineages?~

## Update 12 April 2022:

Currently, with the normal (not advanced) search, the user can specify `pangoLineage`, `aaMutations` and `nucMutations`. LAPIS also supports `nextcladePangoLineage`, `nextstrainClade` and `gisaidClade` and the user should also be able to search them. I think that the major challenge is to design the auto completion well.

The nextcladePangoLineages look like just the other pango lineages but are calculated with Nextclade instead of pangolin. Example values/queries: `B.1.351, BA.1, BA.1*` (current full list: https://lapis.cov-spectrum.org/gisaid/v1/sample/aggregated?fields=nextcladePangoLineage)

Examples for GISAID clade: `L, O, GH` (current full list: https://lapis.cov-spectrum.org/gisaid/v1/sample/aggregated?fields=gisaidClade)

Examples for Nextstrain clades: `21C, 20I` (current full list: https://lapis.cov-spectrum.org/gisaid/v1/sample/aggregated?fields=nextstrainClade)

**Comment by corneliusroemer** [comment]
Nope, this sound alike a good idea! Especially since Nextstrain has some cleaner hierarchy with 21I/J for example

**Comment by chaoran-chen** [comment]
By extending the `variantQuery` of LAPIS, it's now possible to search them through the advanced search.
