### ISSUE TITLE
How should ambiguous nucleotides be treated in nucleotide queries?

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/cov-spectrum-website#278]
Discussion issue for comments based on @chaoran-chen's tweet request for comment, feel free to reply in a comment if you have an opinion

> How should CoV-Spectrum's nucleotide mutation search handle IUPAC ambiguity code? (1) Transform all ambiguity codes (Y, R, W, ...) to N, i.e., people can only search for A, T, C, G, N and -. (2) Keep the ambiguity codes. Do you have an use case where ambiguity codes are useful?

https://twitter.com/ChaoranChen_/status/1450757156224094209?s=20

Do you have opinions?
@theosanderson @shay671 @emmahodcroft @trs @trvb @AngieHinrichs

**Comment by corneliusroemer** [comment]
I think it'd make sense to start off with just the set of 6 options. Do you know how common ambiguous nucs are @chaoran-chen? I know that you ETH people have a very low threshold to call them in contrast to most labs around the world. What percentage is ambiguous with which code? Quick summary data would help.

It's important though that you turn beginnings and ends into Ns, they are usually `-` which is a terrible convention for nucleotide based searches.

**Comment by chaoran-chen** [comment]
@laduplessis had an interesting idea:

> How about in the search box you can only search for A/C/G/T at a given position, but then there is a checkbox to also show ambiguous results, so if there is an ambiguous nucleotide at that site that matches your search (N matches all, Y matches C+T, R matches A+G etc.) then those matching sequences are also shown. That way you don’t allow users to search for all ambiguous codes and you also don’t have to throw away informative data.

Instead of seeing the number of cases that definitely have certain mutations, this would give us all cases that might have these mutations.

**Comment by corneliusroemer** [comment]
Before going about implementing such a feature, I'd first check how common ambiguous sites are globally. Should be a quick query, no?

**Comment by chaoran-chen** [comment]
13% of the sequences contain ambiguity codes. Here is a break-down by country:

|country                |has ambiguity code|total|
|--------------------------------|---------|-------|
|Afghanistan                     |34       |99     |
|Albania                         |10       |42     |
|Algeria                         |0        |72     |
|Andorra                         |0        |29     |
|Angola                          |1        |945    |
|Anguilla                        |0        |12     |
|Antigua and Barbuda             |0        |67     |
|Argentina                       |1168     |8500   |
|Armenia                         |0        |143    |
|Aruba                           |108      |2676   |
|Australia                       |6600     |36915  |
|Austria                         |430      |61029  |
|Azerbaijan                      |0        |14     |
|Bahrain                         |95       |968    |
|Bangladesh                      |786      |2987   |
|Barbados                        |0        |78     |
|Belarus                         |29       |91     |
|Belgium                         |1190     |52213  |
|Belize                          |31       |178    |
|Benin                           |14       |282    |
|Bermuda                         |19       |40     |
|Bolivia                         |0        |152    |
|Bonaire                         |25       |503    |
|Bosnia and Herzegovina          |2        |273    |
|Botswana                        |18       |1262   |
|Brazil                          |674      |48645  |
|Brunei                          |22       |38     |
|Bulgaria                        |469      |5426   |
|Burkina Faso                    |43       |424    |
|Burundi                         |0        |63     |
|Cabo Verde                      |0        |40     |
|Cambodia                        |21       |1261   |
|Cameroon                        |22       |220    |
|Canada                          |24671    |162794 |
|Canary Islands                  |0        |73     |
|Central African Republic        |1        |118    |
|Chad                            |0        |9      |
|Chile                           |5582     |11187  |
|China                           |94       |1337   |
|Colombia                        |5        |6366   |
|Costa Rica                      |539      |1345   |
|Côte d'Ivoire                   |4        |236    |
|Croatia                         |7        |8404   |
|Cuba                            |49       |1049   |
|Curacao                         |27       |821    |
|Cyprus                          |30       |168    |
|Czech Republic                  |38       |10273  |
|Democratic Republic of the Congo|3        |870    |
|Denmark                         |41547    |177117 |
|Djibouti                        |3        |306    |
|Dominica                        |0        |9      |
|Dominican Republic              |35       |327    |
|Ecuador                         |31       |2365   |
|Egypt                           |183      |1046   |
|El Salvador                     |1        |152    |
|England                         |2        |3      |
|Equatorial Guinea               |0        |207    |
|Estonia                         |3        |6237   |
|Eswatini                        |0        |124    |
|Ethiopia                        |6        |219    |
|Fiji                            |7        |531    |
|Finland                         |10       |18886  |
|France                          |3883     |119164 |
|French Guiana                   |0        |17     |
|French Polynesia                |0        |11     |
|Gabon                           |35       |314    |
|Gambia                          |0        |687    |
|Georgia                         |0        |264    |
|Germany                         |4068     |223366 |
|Ghana                           |61       |1436   |
|Greece                          |32       |10654  |
|Grenada                         |0        |12     |
|Guadeloupe                      |9        |591    |
|Guam                            |0        |2      |
|Guatemala                       |3        |774    |
|Guinea                          |58       |262    |
|Guinea-Bissau                   |0        |48     |
|Guyana                          |0        |14     |
|Haiti                           |0        |95     |
|Honduras                        |2        |116    |
|Hong Kong                       |82       |5015   |
|Hungary                         |24       |435    |
|Iceland                         |0        |9678   |
|India                           |17988    |70002  |
|Indonesia                       |119      |7854   |
|Iran                            |56       |606    |
|Iraq                            |6        |275    |
|Ireland                         |2363     |36434  |
|Israel                          |1405     |16071  |
|Italy                           |6738     |67661  |
|Jamaica                         |2        |177    |
|Japan                           |498      |130789 |
|Jordan                          |17       |833    |
|Kazakhstan                      |70       |465    |
|Kenya                           |404      |3569   |
|Kosovo                          |4        |702    |
|Kuwait                          |9        |314    |
|Laos                            |0        |23     |
|Latvia                          |1        |5624   |
|Lebanon                         |285      |1020   |
|Lesotho                         |1        |18     |
|Liberia                         |0        |77     |
|Libya                           |2        |22     |
|Liechtenstein                   |0        |130    |
|Lithuania                       |2745     |20841  |
|Luxembourg                      |239      |12752  |
|Madagascar                      |131      |722    |
|Malawi                          |0        |586    |
|Malaysia                        |230      |3849   |
|Maldives                        |319      |362    |
|Mali                            |3        |71     |
|Malta                           |9        |299    |
|Martinique                      |2        |144    |
|Mauritius                       |13       |290    |
|Mayotte                         |0        |4      |
|Mexico                          |1495     |32056  |
|Moldova                         |7        |67     |
|Monaco                          |1        |78     |
|Mongolia                        |14       |28     |
|Montenegro                      |0        |260    |
|Montserrat                      |0        |5      |
|Morocco                         |2        |484    |
|Mozambique                      |51       |580    |
|Myanmar                         |9        |75     |
|Namibia                         |163      |281    |
|Nepal                           |186      |287    |
|Netherlands                     |1274     |66464  |
|New Zealand                     |0        |2806   |
|Niger                           |8        |24     |
|Nigeria                         |402      |2769   |
|North Macedonia                 |16       |699    |
|Norway                          |25       |28694  |
|Oman                            |10       |877    |
|Pakistan                        |308      |1265   |
|Palestine                       |20       |141    |
|Panama                          |285      |1262   |
|Papua New Guinea                |68       |1001   |
|Paraguay                        |0        |398    |
|Peru                            |2837     |7619   |
|Philippines                     |229      |7134   |
|Poland                          |430      |22859  |
|Portugal                        |1        |19055  |
|Puerto Rico                     |90       |264    |
|Qatar                           |21       |2966   |
|Republic of the Congo           |10       |269    |
|Reunion                         |0        |28     |
|Romania                         |758      |4058   |
|Russia                          |1172     |8921   |
|Rwanda                          |50       |650    |
|Saint Barthélemy                |0        |9      |
|Saint Kitts and Nevis           |0        |13     |
|Saint Lucia                     |0        |43     |
|Saint Martin                    |0        |10     |
|Saint Vincent and the Grenadines|0        |15     |
|Saudi Arabia                    |55       |1096   |
|Senegal                         |94       |621    |
|Serbia                          |0        |327    |
|Seychelles                      |0        |259    |
|Sierra Leone                    |2        |51     |
|Singapore                       |4252     |8500   |
|Sint Eustatius                  |0        |4      |
|Sint Maarten                    |121      |1637   |
|Slovakia                        |1        |8281   |
|Slovak Republic                 |0        |1      |
|Slovenia                        |3638     |29382  |
|Solomon Islands                 |0        |6      |
|Somalia                         |3        |37     |
|South Africa                    |425      |21095  |
|South Korea                     |12       |16018  |
|South Sudan                     |1        |89     |
|Spain                           |12255    |70979  |
|Sri Lanka                       |15       |1556   |
|Sudan                           |3        |116    |
|Suriname                        |2        |750    |
|Sweden                          |7305     |110205 |
|Switzerland                     |7868     |73147  |
|Taiwan                          |13       |257    |
|Thailand                        |706      |4795   |
|The Bahamas                     |0        |133    |
|Timor-Leste                     |27       |356    |
|Togo                            |182      |347    |
|Trinidad and Tobago             |1        |617    |
|Tunisia                         |30       |132    |
|Turkey                          |13       |65452  |
|Turks and Caicos Islands        |0        |5      |
|Uganda                          |29       |712    |
|Ukraine                         |37       |363    |
|Union of the Comoros            |0        |6      |
|United Arab Emirates            |27       |2629   |
|United Kingdom                  |274872   |1065305|
|Uruguay                         |5        |740    |
|USA                             |135740   |1341829|
|U.S. Virgin Islands             |139      |428    |
|Uzbekistan                      |0        |90     |
|Vanuatu                         |0        |2      |
|Venezuela                       |0        |171    |
|Vietnam                         |36       |695    |
|Wallis and Futuna Islands       |0        |10     |
|Zambia                          |0        |970    |
|Zimbabwe                        |177      |659    |

I think that I will implement @laduplessis' proposal, and possibly add an option to directly search ambiguity codes.  As this will take a bit longer, it will not be part of #264.
