### ISSUE TITLE
[Information] Out of curiosity: how many daily users does covSPECTRUM have? Do you have analytics?

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/cov-spectrum-website#280]
I'd love to know how many daily users covSPECTRUM has, how many requests there are on average per user and where users are from. Do you have some analytics set up for that? We set up plausible on nextclade and it's cool to see those stats.

**Comment by chaoran-chen** [comment]
We don't do any sophisticated analysis, but we look at the server logs. We have on average 700 "unique users" every day. The top countries are the US and Switzerland followed by Germany with a bit distance.

**Comment by corneliusroemer** [comment]
Do you know how many queries there are? I probably have around 50 per day alone?

**Comment by chaoran-chen** [comment]
I can see the number of requests to the server but the number is not meaningful at all. For example, we had a bug for a while that made the frontend application send requests to the server in an endless loop.

**Comment by corneliusroemer** [comment]
Ah, so some analytics tool could be useful for that :)

**Comment by chaoran-chen** [comment]
True. I assume that we will add one eventually (-> #104).
