### ISSUE TITLE
Why do I get this error: A transmission advantage cannot be estimated for this variant.

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/cov-spectrum-website#281]
Trying to fit transmission advantage but it fails, why? This occurs quite regularly, just never bothered to open an issue.

https://cov-spectrum-develop-git-lapis-and-refactoring-cov-spectrum.vercel.app/explore/World/AllSamples/from=2020-11-06&to=2021-07-20/variants?aaMutations=N%3A204P&pangoLineage=B.1.1.7*

![image](https://user-images.githubusercontent.com/25161793/138126068-689dee95-d265-45e0-80d0-237e9e4ada9c.png)

**Comment by chaoran-chen** [comment]
The preview had a bug. Now, the error should only occur very rarely. Sometimes, the statsmodels package is not able to fit the model and throws

```
statsmodels.tools.sm_exceptions.PerfectSeparationError: Perfect separation detected, results not available
```

If you still see the error often, please send me a list of cases where the error appears.

**Comment by corneliusroemer** [comment]
Thanks, I'll close this issue for now then
