### ISSUE TITLE
[Suggestion] Make Twitter account for covSPECTRUM to tweet news (releases etc.)

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/cov-spectrum-website#283]
I sometimes tweet about covSPECTRUM and it's a shame that I can't tag it in tweets. Would be great to have an account that tweets out when there's a new release etc that I could tag!

**Comment by chaoran-chen** [comment]
Would you be interested to help maintain the account?

**Comment by corneliusroemer** [comment]
Yup, happy to

**Comment by corneliusroemer** [comment]
Done, it's @covSpectrum https://twitter.com/covSpectrum
