### ISSUE TITLE
[Enhancement] Add option to choose between Usher and pangoLEARN default mode for pango lineages

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/cov-spectrum-website#284]
Pango lineages are at the core of covSPECTRUM. Unfortuantely, the default mode of pangoLEARN is not very precise and has many false positives and negatives. Usher mode is much more precise and also updated much more regularly.

It'd be amazing if you could add an option to use Usher assignments in place of default assignments. That way AY.4.2 could already have been shown for 2 weeks now.

This would also really help everyone working on pango lineages.

It shouldn't be difficult to generate the labels, just run Usher on all the sequences, it's not computationally intensive, really.

**Comment by chaoran-chen** [comment]
See: https://github.com/cov-lineages/pangoLEARN/issues/32#issuecomment-946937425

According to that rough calculation, computing the pango lineages with the UShER mode with a 64-core machine would take >7h for 3.7 million sequences. For the current 4.9 sequences, that would cost >10h.

The code is already there (https://github.com/cevo-public/LAPIS/commit/cac5724c18f23a255c91aec61d86918aec5e0e2d) but I'm hesitating to run it.

**Comment by chaoran-chen** [comment]
As of #285, we use the pango lineage assignments from https://github.com/cov-lineages/pangolin-assignment if available.

Instead of running `pangolin --usher` ourselves, I would like to wait for https://github.com/cov-lineages/pangolin-assignment/issues/1.

**Comment by AngieHinrichs** [comment]
Hi @chaoran-chen - just wondering the status of this.  More recently I got the impression that you were using the pangoLEARN assignments from GISAID, is that right?  cov-lineages/pangolin-assignment now includes pangolin/UShER assignments (without scorpio) associated with aligned & masked sequence hashes.  I could provide a mapping of sequence names and/or IDs to pangolin/UShER assignments (updated every time cov-lineages/pangolin-data and pangolin-assignment are updated) if that would help.

**Comment by corneliusroemer** [comment]
Ideally maybe also without Scorpio override which seems to be responsible for many clear misclassifications lately?

**Comment by chaoran-chen** [comment]
I'm really sorry that there is no progress on this. Yes, receiving a file with an ID to the different pango lineage assignments would be hugely helpful!

**Comment by AngieHinrichs** [comment]
No problem, and great work standing up mpox-spectrum so quickly!  I will email you a file with v1.9 assignments.  

> Ideally maybe also without Scorpio override which seems to be responsible for many clear misclassifications lately?

Yes, I use `--skip-scorpio` when precomputing the assignments for the pangolin-assignment repo.  (Then, at runtime, if the cache is used with `--skip-scorpio`, then the assignments will come through, but if scorpio is enabled (default) it will still override the cache assignments.)
