### ISSUE TITLE
[Enhancement] Do pangolin assignments by running pangoLEARN rather than using GISAID metadata

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/cov-spectrum-website#285]
In light of this thread: https://twitter.com/CorneliusRoemer/status/1451568094699311109?s=20 explaining that GISAID pangolin assignments are incremental over the course of a week and thus contain mixed pangoLEARN versions, it would make a lot of sense to not use GISAID annotations but generate them oneself by running pangoLEARN on the data once downloaded from GISAID. This should probably happen in cevo-public/LAPIS

**Comment by chaoran-chen** [comment]
https://github.com/cov-lineages/pangolin-assignment :)

**Comment by chaoran-chen** [comment]
We now use the pango lineage assignments from https://github.com/cov-lineages/pangolin-assignment if available.
