### ISSUE TITLE
Public data version

### ISSUE THREAD

**Issue by chaoran-chen** [GenSpectrum/cov-spectrum-website#286]
Now that we use LAPIS, we can also easily deploy a version that uses fully public data based on `/public/api/` of LAPIS.

What would be a good URL? `public.cov-spectrum.ethz.ch`?

**Comment by ningxie1991** [comment]
Yeah that seems like a good one.

**Comment by corneliusroemer** [comment]
Call it open not public, open data is what Nextstrain uses for Genbank etc, that is nom-Gisaid. If I understand correctly, there is Gisaid and nom-Gisaid.

Which do you call which at the moment?

**Comment by chaoran-chen** [comment]
open.cov-spectrum.ethz.ch?

**Comment by corneliusroemer** [comment]
Can you explain the two names right now?

there's gisaid and only totally open, what do you call them for now?

**Comment by chaoran-chen** [comment]
The gisaid one is running on cov-spectrum.ethz.ch and I don't plan to change it. The question is now how the domain of the fully open one should be.

**Comment by corneliusroemer** [comment]
Right, thanks for clarifying. In that case open is good I think, aligns
with Nextstrain usage.

**Comment by chaoran-chen** [comment]
8c64a1d04e6343fcb3e8dba3fe02f647e411b8b1 introduced a build that uses open data.

It's available at https://open.cov-spectrum.ethz.ch/.
