### ISSUE TITLE
[Enhancement] Support more complex queries, for example with OR

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/cov-spectrum-website#287]
Use case:

I want to find all sequences based on the following specification:
```
- Classified as B.1.617.2*
- S:145H OR S:222V
```

Right now this query seems not possible, yet. It'd be amazing if it was.

**Comment by chaoran-chen** [comment]
This would be a huge task. Are you (or @TKGZ, @ningxie1991) familiar with how to design such a system? E.g., how to design the API, how should the search queries be parsed? There are certainly a lot of existing concepts.

**Comment by corneliusroemer** [comment]
If it's too hard and other things more interesting, don't worry. As a user, one can just execute multiple queries, as long as they are all mutually exclusive one can simply aggregate.

**Comment by spacephoton** [comment]
> This would be a huge task. Are you (or @TKGZ, @ningxie1991) familiar with how to design such a system? E.g., how to design the API, how should the search queries be parsed? There are certainly a lot of existing concepts.

Knew some people working on similar things, and I think it's quite complex. Although, I have a feeling there might be some libraries that simplify the task.
