### ISSUE TITLE
Feature request: break up styling for mutations

### ISSUE THREAD

**Issue by rkdover** [GenSpectrum/cov-spectrum-website#288]
I love the mutation prevalence tool, not sure if its new but haven't seen it before. The percentage prevalence is an excellent thought! Would be great to visually group them by coding region though (and maybe add the nucleotide change under the same). Here's a quick and dirty mockup using the same box styling as for the rest of the page:

![image](https://user-images.githubusercontent.com/54945737/138605821-3deeee9b-236e-4b9c-b99d-3e78d0cc6283.png)

Since ORF mutations vary in quantity I'm not sure how to break them up, maybe even make one per ORF (but I'm no microbiologist 😄). Also bear in mind my limited knowledge of the field but I have recently found myself looking for what the underlying code mutation leading to a residue change is, so something like the following would be lovely to see:

![image](https://user-images.githubusercontent.com/54945737/138606142-8bb52f9f-213d-4d23-8c55-b1f3b0d1d4e8.png)

I look forward to hearing your thoughts. Thank you for your hard work!

**Comment by corneliusroemer** [comment]
That's a great suggestion! I'd like to add that I'd prefer column major over row major order, it's much easier to scan down, then right - like a newspaper.

**Comment by rkdover** [comment]
@corneliusroemer I believe that that was inherited from the existing styling, and also threw me off at first so +1 for that change.

**Comment by chaoran-chen** [comment]
@rkdover, thanks for the suggestion! I agree that the mutation list deserves some improvement.

About: 

> I'd like to add that I'd prefer column major over row major order

See #193

**Comment by anastasia-escher** [comment]
@chaoran-chen how do you find this? Do you have any preferences on how to style the section further?
<img width="1440" alt="Screenshot 2022-04-11 at 15 25 38 2" src="https://user-images.githubusercontent.com/52914023/162749369-09ef9afa-2588-4d87-a55b-88436b2483a5.png">
