### ISSUE TITLE
[Enhancement] Geographic plots should have a legend for color -> percentage

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/cov-spectrum-website#291]
It would be great if geographic plots had a legend showing which number a color corresponds to:
![image](https://user-images.githubusercontent.com/25161793/138738058-6440028f-69ac-4bc6-841d-334cf05246f2.png)

Hovering by mouse isn't really that great for screenshots etc.

**Comment by chaoran-chen** [comment]
A color legend would also be useful for the wastewater heatmap

![image](https://user-images.githubusercontent.com/18666552/138743263-040dae3d-a657-4e48-be46-07e745203342.png)

**Comment by chaoran-chen** [comment]
I saw this interactive legend on Cloudflare. The triangle points to the value of the currently hovered country. I like the idea!

![image](https://user-images.githubusercontent.com/18666552/144495523-3897aefd-2f19-4150-946f-da4bd0115e05.png)
