### ISSUE TITLE
[Outage] Request returns 504: Gateway timeout

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/cov-spectrum-website#297]
It looks like cov-spectrum is down? Have I made too many requests? 😮 

![image](https://user-images.githubusercontent.com/25161793/139091842-6b9d3077-b98a-4547-b28e-3af023a7a5ba.png)

**Comment by corneliusroemer** [comment]
covSpectrum is back. Do you know what happened @chaoran-chen?

**Comment by chaoran-chen** [comment]
Ah, it might indeed be you! The application crashed due to not having sufficient memory.
