### ISSUE TITLE
Allow custom threshold for aa/nuc mutations to show

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/cov-spectrum-website#303]
Right now the cutoff value for mutations to show up in the mutation overview is hardcoded to 5%. It would be great if this could be changed by the user, especially to something smaller, like 1%, or 0.1% etc.

LAPIS supports this cutoff now, so it shouldn't be too difficult. To discover new interesting mutations arising in lineages, 5% is quite a high cutoff.

![image](https://user-images.githubusercontent.com/25161793/139150908-2ee65e7b-b9ff-4aa4-ba8f-127d519c00ea.png)

**Comment by chaoran-chen** [comment]
Can I ask, why are you actually interested in the mutations that are rarely present? :)

**Comment by corneliusroemer** [comment]
Any new variant will start small. For something like AY.4.2, it would be extremely good if I could quickly check the frequency of all Spike mutations appearing >0.1% within AY.4.

Or for Delta generally, what are all the Spike mutations appearing more than >0.1%.

If the threshold is 5%, I can just as well wait for them to pop up on the tree, the differential benefit of using covSpectrum is small in that case. Very different if the threshold was 0.1%, then covSpectrum would help me spot interesting developments earlier.

Makes sense?

**Comment by chaoran-chen** [comment]
Ah, yes, that makes sense! Thanks for the suggestion, I'll add it to the todo list!

**Comment by corneliusroemer** [comment]
Great! It would be particularly useful, if the mutations were shown sorted by protein (S separate) and column major as mentioned before ;)

**Comment by chaoran-chen** [comment]
Same as #433, fixed by @dameyerdave in #440
