### ISSUE TITLE
Very slow from NaN to actual values

### ISSUE THREAD

**Issue by ningxie1991** [GenSpectrum/cov-spectrum-website#304]
![image](https://user-images.githubusercontent.com/3387698/139414059-15ffd5e7-d379-4441-bc68-6686e257cb56.png)

**Comment by chaoran-chen** [comment]
Do you know why?

**Comment by ningxie1991** [comment]
> Do you know why?

Now I think it's expected, because there's no data on the date 10-25, if I change to date to when there's data, it's working. False alarm.
