### ISSUE TITLE
Variant header and date range picker should stay while content is loading?

### ISSUE THREAD

**Issue by ningxie1991** [GenSpectrum/cov-spectrum-website#305]
When I implemented the date range picker, I moved the variant header and the date picker out of the loadable content, so that they stay when user changes the date and only the content below would load. Now the header and date picker will disappear while loading as well. Should we keep the old way? For me, if the header disappear, it seems like something is going wrong.

@chaoran-chen @TKGZ  What do you think?

![image](https://user-images.githubusercontent.com/3387698/139428225-b5015666-d82e-4059-89ce-b6986c2e2c4c.png)

![image](https://user-images.githubusercontent.com/3387698/139428257-7e613cac-c2a4-45ae-8e38-eac348bdd292.png)

**Comment by spacephoton** [comment]
> When I implemented the date range picker, I moved the variant header and the date picker out of the loadable content, so that they stay when user changes the date and only the content below would load. Now the header and date picker will disappear while loading as well. Should we keep the old way? For me, if the header disappear, it seems like something is going wrong.
> 
> 
> 
> @chaoran-chen @TKGZ  What do you think?
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/3387698/139428225-b5015666-d82e-4059-89ce-b6986c2e2c4c.png)
> 
> 
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/3387698/139428257-7e613cac-c2a4-45ae-8e38-eac348bdd292.png)
> 
> 

I agree
