### ISSUE TITLE
Large confidence intervals for most recent dates screw up `Estimated cases` plot range

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/cov-spectrum-website#315]
The large confidence intervals of the most recent days shouldn't screw up the y-axis limits like here:

Axis scaling should just be determined by the main line, maybe something like 1.5x max of main line.

![image](https://user-images.githubusercontent.com/25161793/139598365-3ef8ca7e-8561-4d3c-ab56-1c297801a2b9.png)

**Comment by chaoran-chen** [comment]
I have 1.5x for the new sequences over time plot as well, so that's a good idea!
