### ISSUE TITLE
Overflows on small screens

### ISSUE THREAD

**Issue by chaoran-chen** [GenSpectrum/cov-spectrum-website#316]
We have a number of components that overflow on smaller or mobile devices (probably mostly my fault!).

- [x] The buttons

![image](https://user-images.githubusercontent.com/18666552/139600966-f471738b-c535-4866-b32b-12eecdeb1fb2.png)

- [x] Sequences over time chart

![image](https://user-images.githubusercontent.com/18666552/139600980-0a39b387-7313-4aef-921e-ba3ab3a01213.png)

- [x] Transmission advantage chart

![image](https://user-images.githubusercontent.com/18666552/139601158-84c7b63c-f3dd-4dad-8150-1a22883c1f83.png)

- [x] International comparison chart

![image](https://user-images.githubusercontent.com/18666552/139601014-9edbe0ee-9da3-4b06-861b-3b4260212d1d.png)

**Comment by chaoran-chen** [comment]
@TKGZ, you are our mobile expert! Do you have ideas on how to fix these overflows?

**Comment by corneliusroemer** [comment]
I think the title is wrong, this isn't limited to small screens. It shows on my Macbook Pro 15" screen by default.
![image](https://user-images.githubusercontent.com/25161793/139604207-eff90469-feb5-43dc-a2c5-d67ab0760d73.png)

**Comment by spacephoton** [comment]
I think I Know how to fix, will focus on this next
