### ISSUE TITLE
Most recent data update more than 24hr ago: did something crash/fail? Or just no new data? 

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/cov-spectrum-website#319]
I noticed that the most recent data update is more than 24hr ago. Did the update fail? Or was there just no new data, in which case, it might make sense to update the date nonetheless.

Maybe as a potential extra feature, list the number of new sequences since last update? Then you could update if there's no new data and just say: `+0`.
```
The sequence data was updated on: 2021-10-30T11:18:02.000Z
Data obtained from GISAID that is used in this Web Application
remain subject to GISAID’s Terms and Conditions.
```

![image](https://user-images.githubusercontent.com/25161793/139604454-849c8690-428f-4e2b-afe6-0526c3b876e7.png)

**Comment by chaoran-chen** [comment]
The importer indeed crashed once (-> https://github.com/cevo-public/LAPIS/issues/13) but worked again yesterday night.

> Maybe as a potential extra feature, list the number of new sequences since last update? Then you could update if there's no new data and just say: +0.

Feel free to create a new issue for that :)

**Comment by corneliusroemer** [comment]
Ah good! Do you want to write an email if it crashes like you did in the past? I liked that a lot!

**Comment by chaoran-chen** [comment]
I might set up the automatic email notifications (or Slack notifications? :)) eventually, but it doesn't enjoy any priority right now.
