### ISSUE TITLE
Add resolution selection for "Geographic distribution" box

### ISSUE THREAD

**Issue by rkdover** [GenSpectrum/cov-spectrum-website#321]
As it is currently, the geographic distribution box is suited for analysis of a particular country, but if the filter is set for `region` or `global` it becomes overwhelming. It would be nice to default to only showing the geographic division below the filter (e.g. `global->region`, `region->country`, `country->division`, `division->location`) but even better if there could be a selector (as the increased resolution may be useful for export).

Here is an example, filtered for "Europe":
![image](https://user-images.githubusercontent.com/54945737/139658764-537b4eb3-c6b4-4e43-a01c-1a8e4838417b.png)

**Comment by anastasia-escher** [comment]
The filter options should look like a nested menu, right?

**Comment by chaoran-chen** [comment]
How are you imagining it?

I thought that we would just add a dropdown list where the user can select the granularity: region, country, or division.

**Comment by anastasia-escher** [comment]
I thought of something like this
![menu](https://user-images.githubusercontent.com/52914023/163120779-ca6030a5-703b-4b85-adbe-5f6698cf5036.png)

**Comment by chaoran-chen** [comment]
Interesting. And what happens if the user selects e.g. Europe? Does it then show only divisions in Europe?

**Comment by anastasia-escher** [comment]
Yes, it will show only divisions in Europe (I don't know though if the data is suitable for such a menu, haven't seen it yet in detail). Or would you prefer simply to add a dropdown for granularity?

**Comment by chaoran-chen** [comment]
I'm not sure what the initial intent of @rkdover is, but I think that if someone is interested in a particular country/region, they can go to the specific country/region page. A granularity selector would be more interesting in my opinion. If someone is on the "world" page, the selection options would then be region, country, and division. On a region page, it would only be country and division. And then, on the country page, we don't need a selection because the only option is division.

**Comment by anastasia-escher** [comment]
Ok!

**Comment by anastasia-escher** [comment]
Sorry, another question. The default selected country is Switzerland. So, which options should be displayed when a user clicks on the select field for the first time? All of them - world, region, country, division - or only world?

**Comment by chaoran-chen** [comment]
Ah, looking at #458, I finally understand the misunderstanding! This is not about the overall country selection in the top bar, but about the "Geographic distribution" table (see screenshot above) that appears on pages that do not have a map. Examples:

- Sweden: https://cov-spectrum.org/explore/Sweden/AllSamples/Past6M/variants?pangoLineage=B.1.1.529*&
- World: https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?pangoLineage=B.1.1.529*&

In the table for "world", the table is extremely long as it contains all divisions from all countries. That's not particularly useful, therefore, the granularity selector.

Is that clearer? If not, we can also have a call. Sorry for the confusion!

**Comment by anastasia-escher** [comment]
ah, ok, now it is clear! 
Would you like to leave the dropdown selection also in the top bar or delete it? It looked a bit unstructured without it.

**Comment by chaoran-chen** [comment]
I don't really understand the purpose of the dropdown in the top bar. Does it do something different than the search field?

**Comment by chaoran-chen** [comment]
Ah, now I see! I don't think that we need the filter for the search options in the top bar.

**Comment by anastasia-escher** [comment]
Ok!

**Comment by anastasia-escher** [comment]
Another question, just to make sure that i get it right now. So, for example, if a user is on the "world" page and has selected "regions" in the dropdown at the table, the table should show number of sequences and prevalence pro region? And the same with countries?

**Comment by chaoran-chen** [comment]
Yes, this sounds correct!

So, for the implementation, you might need to extend [this](https://github.com/cevo-public/cov-spectrum-website/blob/develop/src/pages/FocusSinglePage.tsx#L94) and [this](https://github.com/cevo-public/cov-spectrum-website/blob/230c72757f71dabbfd66fceb405fad609cecdb75/src/pages/FocusSinglePage.tsx#L358) to also fetch region- and country-stratified data. (If it makes things easier, don't worry about fetching the data for all the granularities even they are not immediately needed,)

**Comment by anastasia-escher** [comment]
But I could also calculate it directly in the table component (VariantDivisionDistributionChart)? Just add a function there.

**Comment by chaoran-chen** [comment]
Sure, that's also possible.

**Comment by chaoran-chen** [comment]
Wait.. What do you mean with calculate? In the current architecture, we are avoiding any data fetching in the `...Chart` components. They are supposed to be "pure", i.e., they can do calculations but should only depend on the data that they receive as input.

**Comment by anastasia-escher** [comment]
Yes, I see that now as well.

**Comment by anastasia-escher** [comment]
An alternative to a dropdown with granularity options  would be to include in the table fields "country" and "region" and make it filterable by these two parameters.

**Comment by chaoran-chen** [comment]
Interesting. Could we then make it somehow collapsable so that it is easy also to see only the sum for the regions or countries?

**Comment by anastasia-escher** [comment]
For now I have only added the dropdown, please check if it is what you meant.

**Comment by chaoran-chen** [comment]
Closed in #458
