### ISSUE TITLE
Show axis ticks also on right hand side of plots for easier plot reading of recent changes

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/cov-spectrum-website#323]
When I look at these plots, I'm always most interested in the right hand side of the plots. I've noticed that the ticks are only on the left hand side, which is visually far away and makes it hard to quickly grasp the scale of the percentages.

I'd be good to have the percentage values show also on the right hand side. I'm now talking about the huge "tooltip" but the axis labels.

I feel like the big numbers are far too prominent. Much more useful is to look at the line, but then it's very important one knows the scale, what does the top correspond to? 1%, 10% 100%? That info is not visually as evident as it should be, especially it's missing on the right hand side.

![image](https://user-images.githubusercontent.com/25161793/139691484-b3ec5ae8-54f5-479b-981f-aa15d17ce2ab.png)

**Comment by chaoran-chen** [comment]
Hi. That's interesting to hear. I personally only look very briefly at the ticks at the beginning to see the rough scale, but then fully rely on the big numbers while moving my mouse through the plot.

Wouldn't ticks at the right side make the right area quite crowded? I think that I'd like to keep it as is for now, but if more people join this issue and share your opinion, I would re-think.
