### ISSUE TITLE
Axis tick float formatting messed up

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/cov-spectrum-website#325]
![image](https://user-images.githubusercontent.com/25161793/139951642-acbb92a0-0084-4a93-9630-cfecb3d510fa.png)

This is on the line chart for example here:
![image](https://user-images.githubusercontent.com/25161793/139951873-1f62120f-142d-42db-9606-5cb2dcca8269.png)

https://cov-spectrum.ethz.ch/explore/World/AllSamples/AllTimes/variants?aaMutations=S%3A613H&pangoLineage=AY.44

**Comment by chaoran-chen** [comment]
Just to confirm that the bug still exists and is relevant, here are two more examples where it occurred:

https://github.com/cov-lineages/pango-designation/issues/403#issuecomment-1013843451
https://github.com/cov-lineages/pango-designation/issues/402#issue-1100730038

**Comment by anastasia-escher** [comment]
Does it only occur on the "Sequences over time" plot? And does it only occur sometimes, not always? 
It looks ok on my screen:
![Screenshot 2022-04-11 at 14 15 32](https://user-images.githubusercontent.com/52914023/162737550-7e088e58-bf62-46e1-8de8-cce7e01c50b9.png)

**Comment by anastasia-escher** [comment]
Does it only occur on the "Sequences over time" plot and only sometimes, not always?

**Comment by chaoran-chen** [comment]
I only noticed it in the "Sequences over time" plot. I think that it mostly happens when the numbers are small. And it might also depend on the window size?

**Comment by anastasia-escher** [comment]
A solution could be to reduce the number of digits after the decimal point to 2 or 3. In this case it doesn't look messy. Would it be acceptable or it should be a very precise number with all of the digits after the decimal point?

**Comment by chaoran-chen** [comment]
I think that's a good solution. I'd also suggest that we set the minimum of the maximum of the y-axis to something like 0.01% (do you know what I mean?).

**Comment by anastasia-escher** [comment]
Or alternatively the maximum tick on the Y axis can always be the maximum value in the data?

**Comment by chaoran-chen** [comment]
But what if the maximum in the data is very small, like 0.0001%? If we round it to two digits after the decimal point, we would write 0% on every tick.

**Comment by anastasia-escher** [comment]
Ok, that it can be 0.01 if the maximum in the data is less than 0.01 and otherwise the actual maximum?

**Comment by chaoran-chen** [comment]
Yes, I think that would be good
