### ISSUE TITLE
`is small` showing in footer

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/cov-spectrum-website#326]
![image](https://user-images.githubusercontent.com/25161793/140190455-198a1a7d-9efc-4fb8-bc1b-f7fe84427feb.png)

A bug here?

https://github.com/cevo-public/cov-spectrum-website/blob/00c98b72b3ba467df6e25c1cb0a6f97b0247a44d/src/pages/ExplorePage.tsx#L76

**Comment by chaoran-chen** [comment]
@TKGZ? :)
