### ISSUE TITLE
[Enhancement] Given a query, provide link to show strain subsample on Usher phylo place

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/cov-spectrum-website#328]
Behind any query like `Germany, Past 3 M, B.1.617.2* + S:677H` there is a list of strain names satisfying this query.

It would be cool, if there was an interface with Usher (ping @angiehinrichs) so that at the click of a button, a subset of strain names matching the query is submitted to Usher Phylo place https://genome.ucsc.edu/cgi-bin/hgPhyloPlace https://www.nature.com/articles/s41588-021-00862-7 

That would allow one to quickly look at the result of a query on a phylogenetic tree, allowing one to see whether a query corresponds to a single monophyletic clade or if it's in fact multiple independent clades.

Right now, it's quite tricky to do investigations like that.

Direct interfacing to usher would be the most convenient, but it would also be ok if covspectrum just output a list of strain names that one could then copy paste and drop right into Usher.

The key is the provision of strain names.

**Comment by chaoran-chen** [comment]
#245 introduced a button to download a list of sequence identifiers and their contributors. That list includes the strain name.

We'll add an explicit integration with UShER.

**Comment by corneliusroemer** [comment]
oh great, so we're half way there!

**Comment by AngieHinrichs** [comment]
Wonderful!  @chaoran-chen If you can create a (temporary) file that contains sequence names or IDs and make it available on your server (e.g. `https://myserver.edu/path/to/nameFile.txt`) then you can form a URL to send to UShER like this:
```
https://genome.ucsc.edu/cgi-bin/hgPhyloPlace?db=wuhCor1&phyloPlaceTree=hgPhyloPlaceData/wuhCor1/public.plusGisaid.latest.masked.pb&subtreeSize=1000&remoteFile=https://myserver.edu/path/to/nameFile.txt
```
(I put "subtreeSize=1000" in there, you may want to try different values.  The max subtree size is 5000.  Large subtrees are useful for evaluating whether sequences form a monophyletic lineage; small subtrees (e.g. 50) are better when investigating a small outbreak & wanting to find the most closely related sequences.)

Please let me know if you have any issues or questions.

**Comment by AngieHinrichs** [comment]
Are there ways that UShER results should be linking in to cov-spectrum, e.g. using assigned lineages?  mutations?

**Comment by chaoran-chen** [comment]
Thank you very much @AngieHinrichs for the information! That made it very easy to implement.

![image](https://user-images.githubusercontent.com/18666552/140499869-8270f17b-28c2-4766-9752-a88370e044bd.png)

> Are there ways that UShER results should be linking in to cov-spectrum, e.g. using assigned lineages? mutations?

Sure! CoV-Spectrum URLs have the following format:

```
https://cov-spectrum.ethz.ch/explore/World/AllSamples/AllTimes/variants?aaMutations=<aa-mutations>&nucMutations=<nuc-mutations>&pangoLineage=<pango-lineage>
```

The AA mutations and nuc mutations can be comma-separated lists and it does not matter if you specify the base of the reference genome, e.g., `S:501Y,S:E484K` or `123A,C913T`.

**Comment by chaoran-chen** [comment]
@AngieHinrichs, is there a small icon that represents Usher? E.g., the U in the Usher logo?

**Comment by AngieHinrichs** [comment]
Wow, that was really fast, thanks!  

> @AngieHinrichs, is there a small icon that represents Usher? E.g., the U in the Usher logo?

I don't know if there is a small icon for UShER but @yatisht made the nice larger logo (https://github.com/yatisht/usher/blob/master/images/usher_logo.png) -- Yatish, do you have an icon/mini version?
