### ISSUE TITLE
[Enhancement] Use wildcarded lineages in top lineages as non-wildcared is arbitrary

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/cov-spectrum-website#330]
Since lineage assignment is basically arbitrary and non-exhaustive, it doesn't make much sense to talk about lineages that have sub-lineages without wildcarding them.

Example: `AY.4` is a bad version of `AY.4*`. The former excludes all arbitrarily chosen sublineages.

Especially for the top 12 lineages etc it'd make a lot of sense to always use wildcard, and not unwildcarded.

I know, that opens the whole question what to do about `B*`, `B.1*`, etc. but I'd suggest this is fixed by a manual exclude for boring wildcards. That list would be quite short. Just containing everything leading up to and including `B.1.617*`.

![Uploading image.png…]()

**Comment by chaoran-chen** [comment]
The "top lineages" known variant list does not exist anymore. It might come back but, in the meantime, this issue can be closed.
