### ISSUE TITLE
[Bug] Some strains not found when looking at strains on Usher

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/cov-spectrum-website#331]
Just tried the Usher feature and some strains were not found. This is a known problem due to different ways spaces and other "difficult" characters are encoded.

@AngieHinrichs may have some ideas of what can be done. This is not critical as maybe only 10-20% of sequences are affected but it would be nice to fix. See here: https://genome.ucsc.edu/cgi-bin/hgPhyloPlace?db=wuhCor1&phyloPlaceTree=hgPhyloPlaceData/wuhCor1/public.plusGisaid.latest.masked.pb&subtreeSize=1000&remoteFile=https%3A%2F%2Fcov-spectrum.ethz.ch%2Fgisaid%2Fapi%2Fv1%2Fsample%2Fstrain-names%3Fhost%3DHuman%26country%3DGermany%26dateFrom%3D2020-01-06%26aaMutations%3DS%253A255F%26pangoLineage%3DB.1.617.2*
![image](https://user-images.githubusercontent.com/25161793/140509486-6068c036-5e2e-468a-b40e-9d9098e663e1.png)

**Comment by AngieHinrichs** [comment]
@corneliusroemer I think this is the same issue that you reported here: https://github.com/yatisht/usher/issues/175

There are also issues with GenBank names vs GISAID names.  (So this shouldn't happen with cov-spectrum's new open-data version.)  (The hCoV-19/ is not a problem, very easy to strip, but there are other classes of name inconsistencies -- especially for RKI sequences from Germany, with IMS-...... names in GenBank/BioSample but XX-RKI-... names in GISAID.)  

[I have an idea of how to fix many of these, just have not got around to it, working on masking additional sites in the tree & re-optimizing at the moment.]

**Comment by chaoran-chen** [comment]
Would it be better to submit a list of GISAID_EPI_ISL instead?

**Comment by corneliusroemer** [comment]
@AngieHinrichs yes this has the same phenomenology but there may be other workarounds available for covSPECTRUM, like using EPI_ISL as suggested by @chaoran-chen.

And yes, I do think EPI_ISL could be a quick fix for covSPECTRUM. Worth a try!

**Comment by AngieHinrichs** [comment]
Yes, EPI_ISL should work better, great idea!
