### ISSUE TITLE
Download fasta

### ISSUE THREAD

**Issue by chaoran-chen** [GenSpectrum/cov-spectrum-website#336]
The user should be able to download the sequences (both aligned and unaligned) with the click of a button if the used data source is open.

It may make sense to wait for https://github.com/cevo-public/LAPIS/issues/5.

**Comment by corneliusroemer** [comment]
Yes please, I just rediscovered that this feature would be amazing. Apparently I thought about it already 2 weeks ago in #411 😄 

I worked around it by downloading the "sequence details" file, then extracting the Genbank IDs, joining with a comma and appending to the LAPIS URL like this https://lapis.cov-spectrum.org/open/v1/sample/fasta?genbankAccession=OV771661,OV772037 but obviously that's quite a bit of work that would be easy to implement in the front end for a LAPIS request at the click of a button :)

Feature would really show the power of covSpectrum and the power of open data sharing!
