### ISSUE TITLE
Date picker already reloads when typing single digit: should only reload on enter

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/cov-spectrum-website#337]
When I manually edit the date range, the page reloads with a new date range, as soon as I edit for example one month.

The whole page turns white and I can't actually finish setting the date range.

This is particularly problematic as covSpectrum has very slow load times. So I have to edit the URL instead of using the date entry field - which is alright for me but not very user friendly.

**Comment by chaoran-chen** [comment]
@ningxie1991, could you please look into that?

**Comment by ningxie1991** [comment]
@chaoran-chen @corneliusroemer There are two issues here, one I am trying to fix, which is that the variant header and the date ranger picker should not disappear when data is loading. And second is the change on enter key. I will fix them together
