### ISSUE TITLE
Taxonium integration

### ISSUE THREAD

**Issue by chaoran-chen** [GenSpectrum/cov-spectrum-website#339]
As pointed out by @corneliusroemer, @theosanderson's Taxonium is another great candidate for an "integration". Just as it was done for UShER in #328, the user should be redirected to Taxonium with the click of a button.

It is possible to provide our own tree, but because we don't have one, we can use https://taxonium.org/?protoUrl=/nodelist.pb.gz.

A variant query can be encoded in the URL. As far as I can see, the `search`-request param contains a JSON encoded with `encodeURIComponent()`. It is possible to search for AA mutations and pango lineages. It is not possible to include sub-lineages of a pango lineage. An example:

```
[
    {
        "id": 0.14905260471396242,
        "category": "lineage",
        "value": "B.1.617.2",
        "enabled": true,
        "aa_final": "any",
        "min_tips": 1,
        "aa_gene": "S",
        "search_for_ids": ""
    },
    {
        "id": 0.45225127463465387,
        "category": "mutation",
        "value": "",
        "enabled": true,
        "aa_final": "Y",
        "min_tips": 1,
        "aa_gene": "S",
        "search_for_ids": "",
        "aa_pos": "501"
    }
]
```

Note: This will highlight `B.1.617.2` in one color and highlight `S:501Y` in another color. It will not filter for sequences that are B.1.617.2 AND have the mutation S:501Y. Nonetheless, I believe that it is useful to translate our `B.1.617.2+S:501Y` to that because the user can then look for overlaps themselves.

The `id` is just a random number ([code](https://github.com/theosanderson/taxonium/blob/9fb8bb5cc945750d66f793938bd3616843c07dc6/src/components/SearchPanel.jsx#L202)).

It is also possible to filter for a list of GenBank-IDs. We might want to do that in our open version if the number of available sequences is low. This shall however be the object of another issue.

@theosanderson, thank you very much for creating this amazing tree viewer! Would it be alright with you that we add this integration? Do you have any advice for us, or did I miss something?

**Comment by theosanderson** [comment]
Hi @chaoran-chen . This integration would be really cool, and a great honour! Of course your interpretation is absolutely right. I'll try to get a link out to CovSpectrum from the lineage buttons at some point. (I used to have a link to Outbreak.info but this was broken by a feature addition, and it would be cool to link to a range of options).

Taxonium has the ability to link to a zoomed-in search (you add `?zoomToSearch=0` to zoom to the first one, etc.) but I think here due to occasional lineage misassignments that probably won't help so much. You can also add `?blinking=true` to make it obvious where the lineage is, but that can also be annoying!

**Comment by chaoran-chen** [comment]
Hm.. I'm confused. Why is the link taxodium.org - with a d? Not taxonium?

**Comment by theosanderson** [comment]
Hah, I originally called the library Taxodium, based on a species of tree. Then realised that was impossible to google because of the species of tree.. Both URLs work and I'd encourage you to use the N version (taxonium.org) - I need to get that set up as a forced redirect

**Comment by theosanderson** [comment]
Super cool! Thanks for figuring out and bearing with the kinda random JSON!
