### ISSUE TITLE
New pango release, we should prevent slow GISAID sweep from causing confusion

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/cov-spectrum-website#340]
We should run pangolin once over all old sequences to prevent the slow GISAID sweep from causing confusions.

https://github.com/cov-lineages/pangoLEARN/releases/tag/2021-11-04

**Comment by chaoran-chen** [comment]
Since #285, we fetch the pango lineages from https://github.com/cov-lineages/pangolin-assignment. Do you know if they already use the new version?

**Comment by chaoran-chen** [comment]
Argh.. The files were removed again.. There is now this `pango_assignment.cache`-file. Do you know the status?

**Comment by corneliusroemer** [comment]
All I know is that we can't yet rely on this pango assignment repo giving assingments. It's in discussions with GISAID. But not necessarily proceeding.

Doing assignments oneself is the solution. It's easy, we could set it up as a Github action: download sequences from GISAID (with self-provided username/password), install pangolin, run assignments, output results to private repo.

Just have to do it :/ If I had time...

Ok so if we won't apply labels ourselves, the second best is to wait until GISAID has them all thoroughly applied, not just to the most recent sequences. So just staying with previous assignments is fine for now, I guess. Better than using just GISAID. Though then we do have two different versions applied.

**Comment by chaoran-chen** [comment]
> we could set it up as a Github action

This would be great and very re-usable. But the computation takes many hours of CPU time, does GH action allow it (for free)? Or do you have a (very powerful) self-hosted runner?

Would you be able to quickly run pangolin on the sequences somewhere and send me the mapping table? Then I can use it.
