### ISSUE TITLE
No update for 2 days

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/cov-spectrum-website#355]
I've noticed there's not been an update for 2 days.

The GISAID dump updated today at 1pm CET. Can you trigger it manually? @chaoran-chen 

Then the first B.1.1.529 will appear!

![image](https://user-images.githubusercontent.com/25161793/143915820-ac1221b7-3c4a-474b-a5a2-6ccffb057157.png)

**Comment by chaoran-chen** [comment]
It's already running :)

**Comment by chaoran-chen** [comment]
The data was updated!
