### ISSUE TITLE
Reduce data update lag by pulling from GISAID at around 1pm

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/cov-spectrum-website#357]
GISAID dump updates once a day, right now around 11.30-12.30 Basel time.

CovSpectrum seems to update at 3am - which means 15hr more delay than necessary. I'd recommend changing the trigger time to something like 1pm Basel time for now.
![image](https://user-images.githubusercontent.com/25161793/144293444-5c10ab46-8c21-4c92-9327-9cc8b7a3f205.png)

**Comment by chaoran-chen** [comment]
Thanks for the information! I changed it to 13h. It would be great if you can keep me updated on the current update times.

The update time written on the website is the time when the data update pipeline has finished, not when the data was downloaded.
