### ISSUE TITLE
Data update seems to have failed yesterday

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/cov-spectrum-website#361]
Data seems stale, update seems to have failed yesterday

![image](https://user-images.githubusercontent.com/25161793/144873365-d0e3315b-0be4-4039-8a07-d15b66e4e276.png)

**Comment by corneliusroemer** [comment]
Again no update today, should have happened by now

**Comment by chaoran-chen** [comment]
The server issues on Sunday also disrupted the update cycles. But now we are back on the daily schedule again.
