### ISSUE TITLE
Document title

### ISSUE THREAD

**Issue by chaoran-chen** [GenSpectrum/cov-spectrum-website#365]
Currently, we only show "covSPECTRUM" as the document title. It would be better to show page-specific titles. This would e.g. make it easier to find the right tab and to create descriptive bookmarks.

I suggest:

- ExplorePage
```
<country> - covSPECTRUM
Ex.: Europe - covSPECTRUM
```

- DeepSequencingCoveragePage
```
Sequencing coverage - <country> - covSPECTRUM
Ex.: Sequencing coverage - Europe - covSPECTRUM
```

- FocusPage and the other Deep-pages
```
<variant display name> - <country> - covSPECTRUM
Ex.: B.1.617.2* + S:N501Y - Europe - covSPECTRUM
```

For now, I suggest that we don't give the Deep-pages specific names because the names would be getting quite long.

- The other pages
```
Stories - covSPECTRUM
Wastewater in Switzerland - Stories - covSPECTRUM
About - covSpectrum
Login - covSPECTRUM
```

**Comment by spacephoton** [comment]
This is a good idea. I noticed it for the story as well, page titles always the same. They're quite easy to set with react router actually.
