### ISSUE TITLE
Landing page

### ISSUE THREAD

**Issue by chaoran-chen** [GenSpectrum/cov-spectrum-website#366]
Our current landing page is mostly just empty.

![image](https://user-images.githubusercontent.com/18666552/145729378-42ab6b53-0f85-456a-bab1-27547ff65c9d.png)

Isn't that quite a waste of space? Instead, we could use the space to give the user a better overview and make the search bar easier to find. Here is a quick sketch:

![image](https://user-images.githubusercontent.com/18666552/145729448-e3ec410d-6f50-4886-b0e7-bbeb93a2b1b2.png)

(What do you think, @TKGZ and @ningxie1991?)

**Comment by spacephoton** [comment]
good idea

**Comment by spacephoton** [comment]
Think it needs some kind of one sentence pitch. For example 'Analyze covid variants... ' , any ideas @chaoran-chen @ningxie1991 ?
