### ISSUE TITLE
Layout restructuring: move search bar and simplify ExplorePage

### ISSUE THREAD

**Issue by chaoran-chen** [GenSpectrum/cov-spectrum-website#367]
Here's an idea for a small restructuring. The search bar is on the right side. If we implement #366, the sequencing intensity plot is already on the landing page and does not need to appear on the ExploreFocusSplit-view. This allows us to make the left area narrower.

![image](https://user-images.githubusercontent.com/18666552/145729839-c9dcf038-04df-4656-bcda-71e5b3eccc03.png)

**Comment by ningxie1991** [comment]
I like this layout!

**Comment by chaoran-chen** [comment]
Actually, we can even abandon the two-sided layout, no need for two scroll bars anymore.

![image](https://user-images.githubusercontent.com/18666552/146208589-b45f3364-11e4-40e7-8c9d-f56c91e70e15.png)

**Comment by ningxie1991** [comment]
> Actually, we can even abandon the two-sided layout, no need for two scroll bars anymore.
> 
> ![image](https://user-images.githubusercontent.com/18666552/146208589-b45f3364-11e4-40e7-8c9d-f56c91e70e15.png)

Agreed. I was about to suggest the same that we should not have two scroll bars.

**Comment by spacephoton** [comment]
What about keeping it horizontal by default?

**Comment by ningxie1991** [comment]
And what about moving the date range picker up from the variant header to where the search bar is?

**Comment by chaoran-chen** [comment]
Sure, sounds good!
