### ISSUE TITLE
BUG: International comparison chart cut off by footer

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/cov-spectrum-website#376]
International comparison chart seems to be cut off by footer, on Brave and Firefox (macOS 12.1)

![image](https://user-images.githubusercontent.com/25161793/147857033-38e7e26f-7fbd-43fe-addb-edd3ca98d4bf.png)

https://cov-spectrum.org/explore/Germany/AllSamples/Past6M/variants/international-comparison?pangoLineage=BA.2

**Comment by chaoran-chen** [comment]
Thanks very much for reporting the bug! It should be fixed. (Deployment within 10 minutes)

**Comment by corneliusroemer** [comment]
Thanks for the quick fix 😊

**Comment by corneliusroemer** [comment]
I think there's still a bit of a problem, this is on mobile brave
![Screenshot_20220101-215509~2.jpg](https://user-images.githubusercontent.com/25161793/147860037-5e7dd192-4762-422b-b71b-d119efc8d722.jpg)
