### ISSUE TITLE
Show absolute number of sequences over time

### ISSUE THREAD

**Issue by chaoran-chen** [GenSpectrum/cov-spectrum-website#378]
It should also be possible to see the absolute number of sequences over time. We could add a button to switch. This should impact both the line and the bar chart.

![image](https://user-images.githubusercontent.com/18666552/148527654-81821a00-3d09-4876-aaff-577b3f381706.png)

**Comment by gautier-collab** [comment]
As I'm creating the chart I'm wondering what should be the difference between the "Estimated cases" chart and the "Absolute numbers" view of the "Sequences over time" chart?

**Comment by gautier-collab** [comment]
Should the "Estimated cases" plot actually be embedded inside the Sequences over time plot, visible when the "Asbolute numbers" button is triggered?

**Comment by chaoran-chen** [comment]
The estimated cases are calculated by multiplying the proportions (as in sequences over time) with the confirmed case numbers (i.e., the number of positive tests).

The absolute number version of the sequences over time plot, however, should show the absolute number of sequenced genomes of a variant.

Does it make sense?

**Comment by gautier-collab** [comment]
Yes, it's clear now. Thank you

**Comment by Jmuccigr** [comment]
So you mean that instead of the y-axis being percentage, it's number (of cases)? If so, yes, please.

**Comment by chaoran-chen** [comment]
Yes, exactly!

**Comment by corneliusroemer** [comment]
I think number of sequences, not cases, to be totally precise, because cases could also mean estimated cases from proportion and number of cases reported by authorities.

It would also still be cool to have total number of overall sequences generated per week, like outbreak.info does. I think that comment doesn't belong here but it somewhat fits ;) There may be a previous issue for that, too.

**Comment by Jmuccigr** [comment]
> I think number of sequences, not cases, to be totally precise, because cases could also mean estimated cases from proportion and number of cases reported by authorities. 


Yeah, this is what I want, the estimated number of cases by sequence.
