### ISSUE TITLE
Insertions is still impossible to search for them?

### ISSUE THREAD

**Issue by FedeGueli** [GenSpectrum/cov-spectrum-website#381]
Hi thank you for your great tool.
 I am looking for sequences with an insertion, but it seems to me i cannot do that . is this still true?

Federico

**Comment by chaoran-chen** [comment]
Hi @FedeGueli. No, unfortunately, it is still not possible to search for insertions. But thanks for reminding me of the topic, I should really start tackling it!

**Comment by chaoran-chen** [comment]
Closing this issue because it is redundant to #253.
