### ISSUE TITLE
ENH: Add multi-region overview panel for comparison plots

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/cov-spectrum-website#386]
It'd be amazing to have that multi region overview panel for comparison plots

Like this:
![image](https://user-images.githubusercontent.com/25161793/148982229-c5655809-fc77-44e0-8107-507f0df00bdd.png)

**Comment by FedeGueli** [comment]
Agree ot would be of great help and it could help to disentangle the different sequencing frequence effect from.country to country

**Comment by chaoran-chen** [comment]
Implemented in #409
