### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by chaoran-chen** [GenSpectrum/cov-spectrum-website#391]
The documentation deserves another round of updates. I'll take care of the documentation about ...

- [ ] the page structure and which components are fetching the data
- [x] the snapshot tests

@TKGZ, could you please write a bit about ...?

- [ ]  the styling, i.e., how the CSS is structured ([`/docs/styling.md`](https://github.com/cevo-public/cov-spectrum-website/blob/develop/docs/styling.md))

**Comment by spacephoton** [comment]
sure thing
