### ISSUE TITLE
AA mutation comparison: Configurable min proportion

### ISSUE THREAD

**Issue by chaoran-chen** [GenSpectrum/cov-spectrum-website#393]
This is an extension to #392.

The user should be able to set the percentage in the definition of when a mutation is considered as belonging to a variant.

One idea is to show the sentence "A mutation is considered as belonging to a variant if at least XX% of the samples of the variant have the mutation.". When the user then clicks on "XX%", a small slider should pop up, allowing the user to change the value.

**Comment by corneliusroemer** [comment]
Sounds good, need to make sure that Ns are left out of the denominator since otherwise high percentages cannot be achieved (there's always some dropout, and best is to assume we don't know what was there). I think right now you calculate percentage assuming N is its own base.

**Comment by chaoran-chen** [comment]
Thanks for pointing this out! It is difficult to exclude the unknowns right now, but I will print a note so that the users are aware of the issue.
