### ISSUE TITLE
Mutation comparison: Venn diagram

### ISSUE THREAD

**Issue by chaoran-chen** [GenSpectrum/cov-spectrum-website#394]
This is a possible improvement to #392. Instead of showing a table, we could show a Venn diagram as in https://twitter.com/shay_fleishon/status/1480934070012059649.

---

The image copied from the tweet:
![image](https://user-images.githubusercontent.com/18666552/150804491-4f69cd9d-e163-4e90-8417-6e514a0c35d6.png)

---

Can we also make it work for comparisons of three variants?

**Comment by chaoran-chen** [comment]
This looks useful: https://upset.app/ (thanks @lenaschimmel for sharing the link)

**Comment by corneliusroemer** [comment]
Also, if I may suggest, even more interesting than counts would be the actual mutations

Relevant would be a three way comparison, too. Two way is done pretty well by outbreak.info already

<img width="1555" alt="image" src="https://user-images.githubusercontent.com/25161793/163222105-b5c9273e-2cf1-4a83-b895-f55a87c07a26.png">


https://outbreak.info/compare-lineages?pango=Omicron&pango=Delta&pango=Alpha&pango=Beta&pango=Gamma&gene=ORF1a&gene=ORF1b&gene=S&threshold=75&nthresh=1&sub=false&dark=false

**Comment by chaoran-chen** [comment]
Sure. Placing the mutations labels into the Venn diagrams nicely is probably a bit challenging, but it would be really cool.

**Comment by chaoran-chen** [comment]
Nice! - https://twitter.com/caco3cz/status/1502211656037900290?s=21&t=pyCrYilFxZ-g6AB_F2NW_g
