### ISSUE TITLE
Usher not working 

### ISSUE THREAD

**Issue by FedeGueli** [GenSpectrum/cov-spectrum-website#396]
Since yesterday night i saw Usher is not working from the covspectrum page.

**Comment by chaoran-chen** [comment]
Do you have an example? I just tried it from https://cov-spectrum.org/explore/Switzerland/AllSamples/Past6M/variants?nucMutations=T29867A%2CC3241T&pangoLineage=B.1.1.529* and it worked.

**Comment by FedeGueli** [comment]
Every query i have done finished up with this: 
![Schermata 2022-01-29 alle 12 49 08](https://user-images.githubusercontent.com/87669813/151659882-571e394e-a8b6-49c7-9970-0e182846bb7a.png)

**Comment by chaoran-chen** [comment]
Could you please send me the genome browser link?

**Comment by FedeGueli** [comment]
Now it is working again thanks
