### ISSUE TITLE
Synchronize search with selection

### ISSUE THREAD

**Issue by tehwalris** [GenSpectrum/cov-spectrum-website#40]
As discussed in the meeting, make the pre-fill the ~"Search by mutations" fields~ search field when the selected variant changes. If the user edits the search fields, the "focus" panel (just like now) shouldn't update until they click "Search".

**Comment by chaoran-chen** [comment]
With the new search introduced in #196, I believe that this feature is very useful again.

**Comment by chaoran-chen** [comment]
Closed in 99b927a42a6ce4c298b568949e5f869237deb9a3
