### ISSUE TITLE
ENH: Provide Genbank fastas from query

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/cov-spectrum-website#411]
It'd be nice if one could download fastas corresponding to an open=Genbank query directly from covspectrum.

This would be a nice addition to the "sequence list" that provides EPI_ISLs etc but no fasta, as that's not ok under GISAID terms.

For Genbank, that's ok though. This feature could allow easy linkage with Nextclade:  a Nextclade button would simply append that download link to nextclade e.g. as follows:
```
https://clades.nextstrain.org/?dataset-name=sars-cov-2&input-fasta=https://open.cov-spectrum.org/fasta/World/AllSamples/Past6M/variants?nucMutations=3505T%2C4015G%2C28732T
```

where 
```
https://open.cov-spectrum.org/fasta/World/AllSamples/Past6M/variants?nucMutations=3505T%2C4015G%2C28732T
```

would be the endpoint that provides fastas for that query

**Comment by chaoran-chen** [comment]
This sounds like to duplicate to #336? :)

**Comment by corneliusroemer** [comment]
Oops, yes indeed :)
