### ISSUE TITLE
Maybe I broke open.cov-spectrum.org with my queries? White screen...

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/cov-spectrum-website#412]
https://open.cov-spectrum.org/ gives me just a white screen for more than 15min, did I break it? Lapis open also doesn't respond.

**Comment by corneliusroemer** [comment]
After a minute, I get this:
<img width="2542" alt="image" src="https://user-images.githubusercontent.com/25161793/155153556-6c4fd49e-1e1a-49fd-98fe-0e4bf06764fe.png">

**Comment by corneliusroemer** [comment]
I noticed it keeps saying that the sequence data was updated a minute or two ago. Could be that it's continuously getting updated and hence no time to cache? Or database is busy updating and hence can't handle queries?

**Comment by chaoran-chen** [comment]
This is strange. The server did not crash but somehow could not be reached. After a restart, it is working again.

Can you try to do whatever you did before again? Let me know if you can reproduce it!

**Comment by corneliusroemer** [comment]
Now it works splendidly, and weirdly it says: `The sequence data was updated: Today at 2:07 AM` as if time was reset?

Will prod it a bit more to see whether I can reproduce. Will let you know.

**Comment by corneliusroemer** [comment]
I think I know how to crash it: request https://lapis.cov-spectrum.org/open/v1/sample/fasta?genbankAccession=OM647790,OM647768,OM647353,OM647096

It seems down again after I made that request

**Comment by chaoran-chen** [comment]
Okay, a problem was that the program had too little RAM. But I don't know how it would relate to https://lapis.cov-spectrum.org/open/v1/sample/fasta?genbankAccession=OM647790,OM647768,OM647353,OM647096 as this query shouldn't need much RAM.

I increased the memory limit. Try to crash it again!

**Comment by corneliusroemer** [comment]
Now it seems to work 🎉

I'll prod a bit more...

**Comment by corneliusroemer** [comment]
Seems to work, will reopen if it comes back :)
