### ISSUE TITLE
ENH: When selecting "compare to a baseline" query should not populate baseline but variant

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/cov-spectrum-website#426]
The "compare variant to a baseline" feature is amazing.

I think the UX flow could be improved if upon the click of the "compare to a baseline button" the variant that was already entered like so:
<img width="792" alt="image" src="https://user-images.githubusercontent.com/25161793/157280883-a6091471-dd7e-44ac-8faa-0ebb6fbbe221.png">
would appear not in the baseline field like this:
<img width="1156" alt="image" src="https://user-images.githubusercontent.com/25161793/157280928-2c0dbfaf-e334-40be-869c-1633f50b9310.png">
but instead in the variant field like this:
<img width="903" alt="image" src="https://user-images.githubusercontent.com/25161793/157281007-fcede226-52cb-4405-9e25-579ceb02d457.png">
since that's I think how people usually use this feature. At least that's how I use it 95% of the time.

You want to compare the queried variant to its baseline. Not use the variant you've entered as the baseline.

**Comment by FedeGueli** [comment]
Agree vm it would be great tonhave it that way
