### ISSUE TITLE
BUG: It should say `Pango lineage` not `pangolin lineage`

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/cov-spectrum-website#428]
Just a small comment on terminology:

I noticed that the website says `pangolin lineage` but the correct term should be `Pango lineage`

<img width="701" alt="image" src="https://user-images.githubusercontent.com/25161793/157692533-a84b14ab-3dea-418b-a739-c20cd7f173ad.png">

See the addendum in Nature:
<img width="858" alt="image" src="https://user-images.githubusercontent.com/25161793/157692684-173634cc-6efb-48e5-b998-1a3a45220903.png">
https://www.nature.com/articles/s41564-021-00872-5

**Comment by corneliusroemer** [comment]
Spotted it in two more places and submitted PRs:
https://github.com/cevo-public/cov-spectrum-website/pull/430
https://github.com/cevo-public/cov-spectrum-website/pull/429

**Comment by chaoran-chen** [comment]
Thanks!!
