### ISSUE TITLE
ENH: Add Nextclade integration for open data

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/cov-spectrum-website#431]
The Fasta download feature is amazing.

Now it's super easy to add direct Nextclade integration.

All it takes is to URL encode the download link, make file download `false` and attach it to the following URL.

Here's an example URL:
```
https://clades.nextstrain.org/?dataset-name=sars-cov-2 \
&input-fasta=https%3A%2F%2Flapis.cov-spectrum.org%2Fopen%2Fv1%2Fsample\
%2Ffasta%3Fhost%3DHomo%2Bsapiens%26orderBy%3Drandom%26limit%3D100%26dateFrom\
%3D2021-09-06%26aaMutations%3DS%253A628K%26pangoLineage%3DBA.1.\
%2A%26downloadAsFile%3Dfalse
```

Or clickable: https://clades.nextstrain.org/?dataset-name=sars-cov-2&input-fasta=https%3A%2F%2Flapis.cov-spectrum.org%2Fopen%2Fv1%2Fsample%2Ffasta%3Fhost%3DHomo%2Bsapiens%26orderBy%3Drandom%26limit%3D100%26dateFrom%3D2021-09-06%26aaMutations%3DS%253A628K%26pangoLineage%3DBA.1.%2A%26downloadAsFile%3Dfalse

**Comment by chaoran-chen** [comment]
Here you go :) I set the limit to 200 sequences.

![image](https://user-images.githubusercontent.com/18666552/157842349-4a2c5730-68ea-4610-9e51-851527c4e8c8.png)
