### ISSUE TITLE
ENH: Show mutations rarer than 5%, too

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/cov-spectrum-website#433]
I think I've suggested this before but couldn't find the issue, maybe it was just a request for LAPIS but not for the website:

It would be really nice, if you showed the most common rare mutations for a given query too. Right now, only mutations with >5% share are shown. That means one misses out on interesting sub-lineages that may be growing but don't yet have a share of 5%.

One problem may be that this causes overwhelming numbers of mutations to show.

Possible solution:
Allow users to specify min (and maybe also max) proportion for mutations to show.

Looking for interesting mutations with say 1% share, I would then set min to 0.5%, max to 5% for example.

Maybe you could also add checkboxes to restrict to certain genes, e.g. S mutations only.

That would make the mutation widget on the website even more useful.

Just to be clear, I'm talking about this thing here:
<img width="2048" alt="image" src="https://user-images.githubusercontent.com/25161793/158077164-cf9d02d8-9140-4533-a2e6-76c3a7632abd.png">

I think given that LAPIS already supports min-frequency (at least for aa-mutations) this may be be a pure front-end task:
https://github.com/cevo-public/LAPIS/issues/9

**Comment by chaoran-chen** [comment]
I think that this task can be nicely combined with #288. @gautier-collab, would you be interested to think about the design/UI?

Generally, the goal would be to re-design the mutation panel and both improve the layout and add filtering/configuration features.

**Comment by FedeGueli** [comment]
Great to hear it would be wonderful to have that too!

**Comment by gautier-collab** [comment]
That makes sense. Yes, I can think about the UI of the mutation panel.
