### ISSUE TITLE
BUG: Advanced query does not allow `3013.` notation

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/cov-spectrum-website#439]
I like that it's possible to use `3014.` in normal queries to mean: 3014 unmutated.

For advanced queries, this type of notation seems not to work. Rather than getting results, it loads indefinitely.

When I replace it with explicit `T3014T` the result is there immediately.

Works:
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?variantQuery=BA.1*+%26+C29632T+%26+T3104T

Doesn't work:
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?variantQuery=BA.1*+%26+C29632T+%26+3104.

**Comment by chaoran-chen** [comment]
I did not add the `.` notation to the advanced queries, yet.

**Comment by corneliusroemer** [comment]
Ah alright, advanced queries are still cool :)
