### ISSUE TITLE
Sequencing intensity plot

### ISSUE THREAD

**Issue by chaoran-chen** [GenSpectrum/cov-spectrum-website#44]
In the explore area, we would like to show a plot presenting the sequencing intensity of the selected country.

The corresponding API is at https://github.com/cevo-public/cov-spectrum-docs/blob/develop/API.md#sequencing-intensity-through-time

A suggestion:

![image](https://user-images.githubusercontent.com/18666552/110212208-8ec0de80-7e9a-11eb-80e1-3173d08eddd2.png)

On hover, a tooltip should show the absolute number of cases, the absolute number of sequenced samples, and the relative number as percentage.

**Comment by tehwalris** [comment]
To whoever implements this: Make sure that it respects the global `dataType` ("Sampling strategy") setting.
