### ISSUE TITLE
Remove lodash

### ISSUE THREAD

**Issue by chaoran-chen** [GenSpectrum/cov-spectrum-website#443]
As a small code improvement measure: the [lodash library](https://github.com/lodash/lodash) does not seem to be actively maintained anymore and as we only use it [a very few times](https://github.com/cevo-public/cov-spectrum-website/search?q=lodash), I think that we should get rid of it. The [you-dont-need repository](https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore#_capitalize) might be helpful.

**Comment by anastasia-escher** [comment]
Problem:
We use the function _.isEqual here in deep-compare-hooks.ts: 

function useDeepCompareMemoize<T>(value: T): T | undefined {
  const ref = useRef<T>();
  if (!_.isEqual(value, ref.current)) {
    ref.current = value;
  }
  console.log('Deep compare:');
  console.log(value, ref.current);
  return ref.current;
}


There seems to be no reliable native alternative which can compare such a wide range of data structures. 
See  here: https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore/issues/177

Do you have any ideas, @chaoran-chen , @corneliusroemer, @dameyerdave  ?

**Comment by chaoran-chen** [comment]
Hi @anastasia-escher, I see two potential solutions:

- We don't need to compare the same wide range of data structures. I think that we only compare (more or less) plain objects. You could check the cases in which `useDeepCompareMemoize()` is currently being used.
- We should also be able to refactor our code so that it does not need to use `useDeepCompare...()` functions at all (but only the default `useMemo()/useEffect()`. This might actually be the best solution.

**Comment by anastasia-escher** [comment]
@chaoran-chen how about extracting the isEqual function from lodash and saving it as a helper?

**Comment by anastasia-escher** [comment]
@chaoran-chen 
please check if everything works as expected here after removing lodash:
https://cov-spectrum-develop-c7htoft68-cov-spectrum.vercel.app/explore/Switzerland/AllSamples/Past6M

**Comment by chaoran-chen** [comment]
Hi @anastasia-escher, did you check it? Already the first thing I tried did not work:

1. Click on the link you sent
2. Click on a variant in the known variants list (e.g., nextcladePangoLineage:BA.2.75*)
3. Click on another variant in the known variants list on the left (e.g., nextcladePangoLineage:BA.4*)

The title changed but nothing else.
