### ISSUE TITLE
ENH: Provide simple GISAID accession list

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/cov-spectrum-website#444]
Right now, information about sequences returned by a query can be downloaded.

But the format is a CSV with multiple columns.

To download sequences from GISAID, it's thus necessary to process the CSV manually to get just a list of accession IDs.

It would be nice if one could get a simple new line separated list of EPI_ISLs at the click of a button.

Ideally as plaintext in a new tab, so that one can copy directly, without having to open in an editor.

Random order would be good, too, so that one gets representative excerpt without randomisation.

**Comment by chaoran-chen** [comment]
What you could do right now is to copy&paste the link underneath the "Sequence list [download]" button and (1) replace `contributors` by `gisaid-epi-isl`, (2) add `&orderBy=random` to the end of the link, and (3) remove `&downloadAsFile=true&dataFormat=csv`.

I'm not sure how many people would benefit from an additional (sub-)button on the website. If you can get 7 thumbs-ups to your proposal, I'll add it.

**Comment by corneliusroemer** [comment]
Thanks!
7 thumbs ups :) that's a lot!
Everyone who wants to download things from GISAID would benefit.
I'll get a few supporting comments.

Wouldn't make it a button but drop-down or so similar to how sequence download works with open data

**Comment by corneliusroemer** [comment]
3 thumbs up already, that's almost a record 😅

**Comment by chaoran-chen** [comment]
Six is good enough, I'll implement it.

**Comment by corneliusroemer** [comment]
Nice, thanks! :)

**Comment by corneliusroemer** [comment]
Great, this works already:
https://lapis.cov-spectrum.org/gisaid/v1/sample/gisaid-epi-isl?host=Human&region=Europe&dateFrom=2021-09-27&nucMutations=2470T%2C13195C%2CG27382C%2CA29510C%2CC26858T%2CA27383T&downloadAsFile=false&dataFormat=csv
