### ISSUE TITLE
ENH: enable a query for 'animal host 'sequences  

### ISSUE THREAD

**Issue by FedeGueli** [GenSpectrum/cov-spectrum-website#445]
It would be interesting to have an option to flag a query restricting it just to non human hosted sequences.
I dont know if it is possible. But maybe it would be helpful in future.

**Comment by chaoran-chen** [comment]
Thanks for the suggestion! This should be easy to implement.

**Comment by FedeGueli** [comment]
Thx!! great to hear from you!
