### ISSUE TITLE
ENH: append `&` if URL ends with `.` or `*` to make links work properly

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/cov-spectrum-website#448]
Quite often, covSpectrum queries end in `*` or `.`, for example when querying for lineage `BA.2*`.

When one pastes the link to the query, many websites wrongly assume that the `*` or `.` is not part of the URL. This can cause scientific inaccuracy and is not great.

It would be easy to work around this limitation, by ending queries with a character that would be acceptable to websites like Twitter etc., for example if one simply appends `&` to the link, the `*` is not cut off when the URL is converted to a link (by Twitter, I verified).

This problem has bugged me for a while, but I sort of accepted it until @JosetteSchoenma asked me about it.

So it's definitely something that's not just having an impact on me. Many people are probably unaware that when they share their queries, they might be changed by the software they send the message in.

Example:

Notice that the `*` is white, meaning it's thought of as not part of the link by Twitter:
<img width="695" alt="image" src="https://user-images.githubusercontent.com/25161793/160853371-9dfb1a3a-a69e-4488-95ad-d831df019c94.png">

Appending `&` fixes it and the query still works:
<img width="679" alt="image" src="https://user-images.githubusercontent.com/25161793/160853264-b5a37fd4-1362-4d78-b291-e50452d3a274.png">

**Comment by chaoran-chen** [comment]
Thanks for the suggestion, @corneliusroemer! I also often noticed the problem but did not come up with this simple solution.

**Comment by corneliusroemer** [comment]
Great, thanks :) Maybe it's now a somewhat untypical URL but who cares if it works 😂
