### ISSUE TITLE
Question: Data update intervals

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/cov-spectrum-website#452]
I've noticed that the interval between successive data updates is sometimes much longer than 24hr.

I was wondering at what schedule you run them right now. Is it triggered by new data from GISAID, or at 48hr?

This was 40hr ago:
<img width="977" alt="image" src="https://user-images.githubusercontent.com/25161793/161789054-53f50cb7-1842-4dc8-ae9f-c453ac5e82c8.png">

**Comment by chaoran-chen** [comment]
It's usually triggered by new data. However, our cluster is offline for maintenance for two days - so no update today and tomorrow.

**Comment by corneliusroemer** [comment]
Right :) Remember you mentioned it a few days ago
