### ISSUE TITLE
CovSpectrum down: did I crash it?

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/cov-spectrum-website#454]
Got this screen for the past few minutes, it keeps saying it updated this minute, but the time keeps changing

<img width="1513" alt="image" src="https://user-images.githubusercontent.com/25161793/162588583-82e3d8e6-b076-476d-9131-cf84727da806.png">

Did I crash the server with too many complicated queries?

**Comment by corneliusroemer** [comment]
Ok, seems to be LAPIS down
<img width="1186" alt="image" src="https://user-images.githubusercontent.com/25161793/162588609-c588d091-7fdb-479b-86df-cfe267b2a79e.png">

**Comment by chaoran-chen** [comment]
I was trying to deploy a new LAPIS version with the precise mutation proportion calculation and better performance (https://github.com/cevo-public/LAPIS/pull/47), but unfortunately, the server does not have enough RAM for it...

I reverted to the old version. It's up again.
