### ISSUE TITLE
BUG: Slovakia suggested twice in country search

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/cov-spectrum-website#455]
<img width="265" alt="image" src="https://user-images.githubusercontent.com/25161793/162592757-0bbdc790-3c58-4554-bba8-0c90fdee8286.png">

**Comment by chaoran-chen** [comment]
Thanks for pointing it out! Internally, there were two entries: `Slovak Republic` and `Slovakia`. I cleaned it up.
