### ISSUE TITLE
BUG: Website reloads every 0.5s, never goes anywhere

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/cov-spectrum-website#456]
There seems to be a problem with the website, it loads, and reloads all the time

https://user-images.githubusercontent.com/25161793/162645306-3de62231-04d7-4702-b44f-4d922022f198.mov

**Comment by chaoran-chen** [comment]
That's strange. Does the problem still persist?

**Comment by corneliusroemer** [comment]
Not on mobile browser, will check laptop in a bit.

The big happened right when the data was updated today, around 1.46am

It could well be that this bug happens in the first few minutes after a data update?

Maybe why we haven't noticed it yet?

**Comment by corneliusroemer** [comment]
Same thing again now, on mobile.
Maybe there's just new data in? 😅

**Comment by chaoran-chen** [comment]
Yes, new data indeed came in just before that. Strange, I'll have to try to reproduce it at some point.

**Comment by chaoran-chen** [comment]
The correct behavior is that, after new data arrives, the first time the web page fetches data, it will reload **one time**.

**Comment by corneliusroemer** [comment]
Aha, yes, new data! perfect :) so we have nailed the bug down

**Comment by chaoran-chen** [comment]
Ah, I found out the reason for the bug. It's indeed directly linked to the arrival of new data. It's unfortunately not very trivial to fix the problem. As of now, for around 20 minutes after receiving new data, the website will not work very well.

**Comment by corneliusroemer** [comment]
At

**Comment by corneliusroemer** [comment]
At least we know what it is and that it'll fix itself after 20min :)

**Comment by Jmuccigr** [comment]
This is definitely persisting for a lot more than 20 minutes at a time.

**Comment by corneliusroemer** [comment]
How long was it the case for you @Jmuccigr 

I think sometimes if there's a bug in the data update it can load until the bug is fixed.

**Comment by Jmuccigr** [comment]
I stopped checking, but it was well over 20 minutes.

**Comment by knoajp** [comment]
Hi, additional report here.

The footer says: "The sequence data was updated: Today at 11:33 AM"
(It seems to be in the locale timezone, I'm in Japan +9:00)

And now it passed 1 hour+, the reloads continues.
(Edit: It doesn't work until 4 hours+, then 4:01 PM finally get it!!)

**Comment by chaoran-chen** [comment]
The problem should now be resolved. Please let me know if it happens again!
