### ISSUE TITLE
Improve country selection

### ISSUE THREAD

**Issue by chaoran-chen** [GenSpectrum/cov-spectrum-website#459]
From the discussion in #321, I agree with @anastasia-escher that the current country selection in the top bar looks a bit unstructured. Maybe we can do something like this? We can then also add flags next to the country names.

![image](https://user-images.githubusercontent.com/18666552/163189633-13560595-fbdb-46f2-a198-b7f1b19c269b.png)

**Comment by anastasia-escher** [comment]
You can assign this to me as well.

**Comment by chaoran-chen** [comment]
Sure, thanks!
