### ISSUE TITLE
ENH: Improve UX of mutation threshold selectors

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/cov-spectrum-website#460]
I love the mutation threshold. Unfortunately, the UX is a bit cumbersome.

<img width="888" alt="image" src="https://user-images.githubusercontent.com/25161793/163221435-7441ae93-f31a-411f-b4bc-02b52370ec33.png">

It would be cool if selections were remembered across different queries, say in a cookie or URL parameter or both

Another improvement would be if there were dropdowns to quickly select predermined values: 
e.g. 0.0%, 0.2%, 0.5%, 1%, 2%, 5%, 10%, 20%, 50%, 80%, 90%, 95%, 99% for the lower
e.g 0.1%, 0.5%, 2%, 5%, 10%, 20%, 50%, 80%, 90%, 95%, 99, 100% for the upper.

Typing in the current text boxes is very cumbersome due to the validation. So dropdown point and click would be cool.

**Comment by chaoran-chen** [comment]
I'm not sure if a big dropdown box is the best option but I definitely think that the UI should be improved. At the moment, we have a couple of different number/range selection UIs:

In **Mutations over time**:

![Image](https://user-images.githubusercontent.com/18666552/215089317-710bcb4e-17e3-46b3-b11e-db067b155150.png)

In **Amino acid changes on the compare page**:

![Image](https://user-images.githubusercontent.com/18666552/215089619-e6ca0dd4-afef-48c7-a82a-efdd7b220669.png)

It would be nice to make it more consistent.

**Comment by fengelniederhammer** [comment]
> It would be cool if selections were remembered across different queries, say in a cookie or URL parameter or both

-> will be part of #341
