### ISSUE TITLE
ENH: Optional logit scale for share plots

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/cov-spectrum-website#462]
It would be great if covSPECTRUM had an optional logit scale button for share plots.

It would make comparisons like these useful. Right now there's not much to be seen.

With logit axis, it'd be super useful.

Slope as growth advantage ;)

I think this should be doable and would be a huge benefit!

![Screenshot_20220414-150719.jpg](https://user-images.githubusercontent.com/25161793/163397470-5ed52d87-16e6-4358-8f28-80a7f23fab7f.jpg)

**Comment by KarelBerka** [comment]
that would be a great improvement as it is useful for detecting rising slopes even in small numbers (as was visible in absolute numbers for Czech cases over all summer, while the total numbers kept the public completely unaware of the autumn Delta spree).

**Comment by chaoran-chen** [comment]
I agree, it would be useful to have it for the "Sequences over time" plots both in the single and the two comparison modes.

@anastasia-escher, may I assign this to you as one of the upcoming tasks? :)

**Comment by anastasia-escher** [comment]
@chaoran-chen sure!

**Comment by anastasia-escher** [comment]
Hi @chaoran-chen and @corneliusroemer, please check this
https://cov-spectrum-develop-3wb4lcdlb-cov-spectrum.vercel.app/explore/Switzerland/AllSamples/Past6M/variants?variantQuery=BA.3*&variantQuery1=BA.1*&analysisMode=CompareEquals&

**Comment by chaoran-chen** [comment]
<img width="941" alt="image" src="https://user-images.githubusercontent.com/18666552/180654230-02b1d3ae-da3d-478f-b135-5ac5038d79e8.png">

This doesn't look right, why are there negative values? The y-axis should still be in the range of 0 to 100%. (log(0) should be considered as undefined and not shown.) The implementation should be equivalent to the "log scale" mode for the international comparison. See: https://cov-spectrum-develop-3wb4lcdlb-cov-spectrum.vercel.app/explore/Switzerland/AllSamples/Past6M/variants/international-comparison?variantQuery=BA.3*&variantQuery1=BA.1*&

**Comment by chaoran-chen** [comment]
Also to clarify here: This issue is requesting a logit scale, not a log scale but I think that it would make sense to add both.

**Comment by chaoran-chen** [comment]
By the way, a related issue is #211 which is asking for a log scale option in the estimated cases plot.

**Comment by chaoran-chen** [comment]
We won't explicitly work on this for CoV-Spectrum but will add this feature eventually when we start using the new GenSpectrum components. There, logit scale is already implemented: https://github.com/GenSpectrum/dashboards/pull/30
