### ISSUE TITLE
BUG: Growth advantage fails to load if ORF9b used in query

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/cov-spectrum-website#463]
I've noticed that if I use an ORF9b mutation in the comparison view, the growth advantage fails to load and I also can't use the "Region" view. Seems to be a bug.

<img width="1670" alt="image" src="https://user-images.githubusercontent.com/25161793/163698904-a92444c2-d131-4038-86d9-e52c70af39e9.png">

https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?pangoLineage=BA.2.9&aaMutations1=ORF9b%3A51L&pangoLineage1=BA.2.9&analysisMode=CompareToBaseline&

If I use the equivalent nuc mutation the panel loads. If I use a different gene, e.g. N, it works.

<img width="1671" alt="image" src="https://user-images.githubusercontent.com/25161793/163698916-94f46fe1-96ca-4a3f-b5e1-f77d17c05d3e.png">

**Comment by chaoran-chen** [comment]
Thanks for reporting! I identified the problem and fixed it in https://github.com/cevo-public/LAPIS/commit/6e5ff6520e319ad6a984a73b371c35079a03a2fe.

I did not deploy the new version yet and will do it at some point tomorrow.

**Comment by chaoran-chen** [comment]
It's fixed now.
