### ISSUE TITLE
Make units of growth advantage explicit 

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/cov-spectrum-website#464]
There's been confusion about the time interval for which growth advantages are quoted in publications and news.

Two different sets of units/time periods are used currently on covSPECTRUM: per gen time (implicit, unstated) and per day.

It would be best to make all units explicit and visible.

Also, generation time is an inaccurately determined and changing time, so I think it's best to phase it out and replace with an unchanging unit, either day or week.

UKHSA quotes per week, which is not unreasonable as otherwise significant growth advantages of ~1%/day which is equivalent to 40-fold relative growth over a year need to be quoted with digits, like 0.5%.

Per week may give better number ranges and is also closer to generation time ~4 days.

So I'd advocate switching all units to growth per week.

Happy to discuss this but I think the current situation can cause misunderstandings.

Don't get me wrong, the tool is amazing, this is just a small way to reduce confusion.

**Comment by FedeGueli** [comment]
Agree with Cornelius. As we have used the implicit gen time one for months i think it would be wise to have the choice between old way and new one per week.

**Comment by chaoran-chen** [comment]
We now changed the time interval. **If you need the old value, it is still easy to get!**

Just click on the "Show more" button. On the detail page, the default generation time is still the old `4.8` and the growth advantage that is presented on the overview page is `f_d`. You might need to adapt the start and end dates on the detail page.

Screenshot 1:

![image](https://user-images.githubusercontent.com/18666552/167302285-ba8b874a-f168-44e0-b676-34dca21abc2e.png)

Screenshot 2:

![image](https://user-images.githubusercontent.com/18666552/167302323-754515c3-fe3f-4563-914e-902f8f38725c.png)

**Comment by FedeGueli** [comment]
@chaoran-chen in the comparison to baseline tool which one will be showed? the old or the new one?

**Comment by chaoran-chen** [comment]
It shows the new one.

**Comment by chaoran-chen** [comment]
You can also transform back to the old value using the following formula:

![image](https://user-images.githubusercontent.com/18666552/167309148-5ae5dec0-6234-4a9f-9ce3-68388ec46c39.png)
