### ISSUE TITLE
ENH: Checkbox to toggle deletion visibility in mutation view

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/cov-spectrum-website#466]
Due to artefacts and the Nextclade trailing deletion issue, when trying to find mutations arising, that are present at between 0.1-5%, the overwhelming number if mutations displayed are deletions.

Now deletions are actually the only thing I'm usually not interested in, since they are much less informative (due to artifacts and lack of uniqueness even if genuine).

So it would be great if it was possible to hide all deletions - through a checkbox. That would improve usability A LOT.

Maybe it would even make sense to hide deletions by default and show only upon toggle. Or if it was remembered for queries through a cookie so that one doesn't need to reselect for every single query.

I've used a workaround till now of including `ORF1a:. , N:420.` but that's really suboptimal to this solution. As it filters out sequences and makes queries more lengthy than necessary. And doesn't solve problem of long interior deletion stretches.

**Comment by chaoran-chen** [comment]
Thanks! This sounds like a quick solution until we decided on #398.

**Comment by corneliusroemer** [comment]
Yes exactly, and even after, it could be useful - there are sometimes quite common internal deletions, that I may want to hide even if #398 wasn't an issue.

**Comment by anastasia-escher** [comment]
Hi @corneliusroemer , is it what you meant? #482

**Comment by corneliusroemer** [comment]
Yep, totally, this is exactly it! @anastasia-escher 

Super useful since there are often lots of artefactual deletions which make it difficult to spot the real mutations among masses of fake deletions.

Thanks a lot! 🎉
