### ISSUE TITLE
Update editor's choice lineages

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/cov-spectrum-website#467]
It's convenient to have lineages thought to be growing in the editor's choice section. 

Alpha, Beta, Gamma, B.1.1.529* can be removed.

I'd add: BA.2.12.1, plus maybe BA.2* + S:452 since there are a lot of 452 lineages that could be interesting as a whole overall.

**Comment by chaoran-chen** [comment]
May I invite you to be an editor for CoV-Spectrum? ;)

You can change the pre-defined lists by editing https://github.com/cevo-public/cov-spectrum-website/blob/develop/src/components/KnownVariantsList/variantLists.json. Feel free to also update other lists and add/remove lists!
