### ISSUE TITLE
Links don't keep country/continent selection

### ISSUE THREAD

**Issue by FedeGueli** [GenSpectrum/cov-spectrum-website#471]
From the last update i am noticing that links to a query in a determinated country or area don't keep the selection for a choosen country and instead they link to default "switzerland" page.

it could be a big issue for pango proposals forcing the pango team to reconstruct what that link means.
it is the same for comparison btw variants pages. and it is true for old links too 

So this could influence a lot of things.

(for example i have a rapid list to check growth advantages or nr of sequencss, and it is not rapid at all now)

**Comment by chaoran-chen** [comment]
Oh, that's indeed a very troublesome bug! Thanks for reporting it. I rolled back the update.

**Comment by FedeGueli** [comment]
thx!
