### ISSUE TITLE
ENH: Allow selection of sub-country divisions for big countries

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/cov-spectrum-website#472]
Divisions of big countries are often bigger than most countries (e.g. California is bigger than most European countries).

It would be nice if divisions in a few big countries could be selected just like countries.

For example states in the US, Germany, nations in the UK.

I'm not sure whether this would increase computation requirements to prepopulate the database. If that's the case, one could restrict the sub-country divisions to a few big countries.

But the you seem to already have divisions in "regions" plots. So it seems natural to allow it for normal querying.

**Comment by AnonymousUserUse** [comment]
Push. It would also be wonderful if divisions in China can be selected.

**Comment by chaoran-chen** [comment]
We won't explicitly work on this for CoV-Spectrum but will add this feature eventually when we start using the new GenSpectrum components. We plan to implement a more sophisticated location component and are happy to receive suggestions: https://github.com/GenSpectrum/dashboards/issues/7
