### ISSUE TITLE
BUG: Open data loading since 4:15pm (already >40min)

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/cov-spectrum-website#476]
Open covSpectrum seems to have some problem, it's been loading since at least 4:15pm. I'm not sure whether that's expected/normal for open data.

<img width="2203" alt="image" src="https://user-images.githubusercontent.com/25161793/165535208-ef06c569-1040-43fb-b5fd-12b0020c399a.png">

**Comment by chaoran-chen** [comment]
Thanks for reporting! There was a bug which has now been fixed.
