### ISSUE TITLE
Export plot as PNG

### ISSUE THREAD

**Issue by chaoran-chen** [GenSpectrum/cov-spectrum-website#48]
Hey. ~Since recharts generates SVG elements, would it be easy to export a plot as an SVG file?~ PNG is also good for now. Could we have it for all the plots?

The reason is again that I believe that it would be very helpful if the user can easily download the plots and use them in their papers and presentations.

**Comment by spacephoton** [comment]
Seems like it.
I see there are [ways to save as PNG]( https://stackoverflow.com/questions/45086005/recharts-component-to-png), might that not be more useful? Or option to save both if easy?

**Comment by chaoran-chen** [comment]
Both would be great! Since I expect many users to be scientists and journalists, an SVG export will definitely be valuable.

**Comment by spacephoton** [comment]
I see! What are typical use cases? do they include them in reports?

**Comment by chaoran-chen** [comment]
Yes, exactly! And often they would like to make some small changes. For example, making fonts larger, change colors or translate the labels.
