### ISSUE TITLE
BUG: Venn diagram shows wrong label for query, no shared mutations

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/cov-spectrum-website#483]
On this query, the Venn diagram seems wrong in two ways:
https://cov-spectrum.org/explore/North%20America/AllSamples/Past6M/variants?aaMutations=S%3A452Q%2CS%3A704L&nucMutations=21721C&aaMutations1=S%3A452Q%2CS%3A704L&nucMutations1=21721T&analysisMode=CompareEquals&

1. The right label does not represent the actual query:
<img width="2160" alt="image" src="https://user-images.githubusercontent.com/25161793/166240779-3ae590c0-ab0a-4df1-a8c1-fbee6308e25d.png">
It's just 21721T, but should be a more extensive query (`aaMutations1` seem to be missing)

2. There are no shared mutations in the Venn, despite being shown in table view (where the 2nd query is also correctly shown btw)
<img width="1997" alt="image" src="https://user-images.githubusercontent.com/25161793/166240887-df35283b-acf7-40c8-99bc-34f68dee28ee.png">

**Comment by Sinickle** [comment]
For what it's worth, after a bit of playing around with it, I think I'm seeing it specifically making the mistake of swapping the mutations between "shared" and the 2nd variant in the comparison, only when you're comparing just 2 variants.

**Comment by chaoran-chen** [comment]
Thanks for reporting!

Part 1) The label was being cut off. I now gave the figure more width.

Part 2) Yes, it was indeed swapping the "shared" and "only variant 2"  areas.

The fix will be deployed within the next 10 minutes.
