### ISSUE TITLE
BUG: identification of ORF3a:H78Y within BA.2.9 lineage in amino acid Venn diagram

### ISSUE THREAD

**Issue by KarelBerka** [GenSpectrum/cov-spectrum-website#490]
Upon preparation of a report of current lineages to Czech authorities, I have looked at the Venn diagram between the 4 most typical lineages currently present in the Czech Republic. And I have found a weird problem when I compared BA.2.9 and BA.2 lineages in the World and in Czechia. 

While Czechia has 1 specific mutation for BA.2.9 - ORF3a:H78Y,... 
[https://cov-spectrum.org/explore/Czechia/AllSamples/Past6M/variants?pangoLineage=BA.2[…]Lineage2=BA.2&pangoLineage3=BA.1&analysisMode=CompareEquals&](https://cov-spectrum.org/explore/Czechia/AllSamples/Past6M/variants?pangoLineage=BA.2.9&pangoLineage1=BA.1.1&pangoLineage2=BA.2&pangoLineage3=BA.1&analysisMode=CompareEquals&)

... it is not visible in World one unless you lower down to 35% of samples
[https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?pangoLineage=BA.2.9[…]Lineage2=BA.2&pangoLineage3=BA.1&analysisMode=CompareEquals&](https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?pangoLineage=BA.2.9&pangoLineage1=BA.1.1&pangoLineage2=BA.2&pangoLineage3=BA.1&analysisMode=CompareEquals&)

However, this mutation DEFINES BA.2.9 sublineage and outbreak.info sees it in 99,6% of all sequences (121651/122090). 

Why it disappeared in CovSpectrum?

**Comment by chaoran-chen** [comment]
Hi @KarelBerka, thanks for creating this issue! We currently use the Pango lineage provided by GISAID and unfortunately, GISAID does not always use the most recent pangolin version and designation data. For that reason, quite a number of samples were misassigned to BA.2.9. But in the most recent data dump from GISAID, this has been resolved. Now, ORF3a:H78Y is also in 100% of the BA.2.9 samples in CoV-Spectrum.

![image](https://user-images.githubusercontent.com/18666552/167255712-8749148c-87a6-4e9e-829e-e2cb1e2edecc.png)
