### ISSUE TITLE
BUG: Formatting of top tick label of y-axis apparently not fixed yet

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/cov-spectrum-website#494]
I just noticed that the formatting of the top tick y-label seems not to be fixed yet

<img width="1152" alt="image" src="https://user-images.githubusercontent.com/25161793/167428288-7a5f1274-fe4d-4107-80e9-ed233abfaf45.png">

All the rest looks good @anastasia-escher :)

**Comment by anastasia-escher** [comment]
The was not enough space for the whole tick label, so I have simply added 15 px margin to the left: 
https://github.com/cevo-public/cov-spectrum-website/pull/495

**Comment by corneliusroemer** [comment]
Oh, I think I didn't mean the margin but the fact that the number was formatted as `40.86` as opposed to `40`.

**Comment by corneliusroemer** [comment]
For example here again `8.05`, maybe it's just in the variant to baseline comparison plot

<img width="1895" alt="image" src="https://user-images.githubusercontent.com/25161793/167629689-b5a4677a-241d-4ce9-9e52-ffb57f6a7729.png">

https://cov-spectrum.org/explore/Sweden/AllSamples/Past1M/variants?pangoLineage=BA.2*&aaMutations1=S%3A449H&pangoLineage1=BA.2*&analysisMode=CompareToBaseline&

**Comment by anastasia-escher** [comment]
It takes simply the highest value in the data, do you want it to be rounded?

**Comment by chaoran-chen** [comment]
I think it's alright to show up to two decimals. Of course, it would look even better if we show less if the numbers are large, but I think that's already fine.

**Comment by corneliusroemer** [comment]
Oh I see. It's maybe a bit unconventional to have ticks at `0,5,10,16.34` as opposed to regular `0,5,10,15` but not a big deal I guess.

**Comment by chaoran-chen** [comment]
True.. But tick formatting is just annoying.. ;)

**Comment by corneliusroemer** [comment]
It seems to be a slightly bigger issue, still maybe? This is on the international comparison plot on the main site:
<img width="1332" alt="image" src="https://user-images.githubusercontent.com/25161793/168343288-fb0e290b-2f3b-4811-8970-c0c059aa38de.png">

https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3A248H%2CS%3AS1261Y&nucMutations=22792T&pangoLineage=BA.2*&aaMutations1=S%3A452Q%2CS%3A164K&pangoLineage1=BA.2*&

**Comment by chaoran-chen** [comment]
Maybe we didn't address the issue for the international comparison plot. @anastasia-escher, could you please take a look? :)

**Comment by anastasia-escher** [comment]
Hi @corneliusroemer and @chaoran-chen, yes, it has to be fixed on that plot separately. Is there another plot on the website where this issue could appear? I have accidentally pushed the commit with the fixing of this issue to the develop branch, is it ok?

**Comment by chaoran-chen** [comment]
Thanks @anastasia-escher. @corneliusroemer, please re-open again if you find more issues with the ticks.

Otherwise: solved in 5eb3395aebdd69765f6cc06d19f77dd47bc59c46.
