### ISSUE TITLE
Auto-completion: Translate NSP and ORF1ab notation to ORF1a/b

### ISSUE THREAD

**Issue by chaoran-chen** [GenSpectrum/cov-spectrum-website#496]
There are two alternative ways to specify ORF1a and ORF1b AA mutations: either by seeing ORF1ab as one single gene or distinguish between the different nsps. E.g., `ORF1b:12` is equivalent to `ORF1ab:4413` and `nsp12:21`. There is a nice tool by @theosanderson (and @zach-hensel) to do the conversion (https://codon2nucleotide.theo.io/) and its code reveals how the conversion can be done (https://github.com/theosanderson/Codon2Nucleotide/blob/main/src/App.js).

Internally (and from the perspective of the APIs), we will only support the `ORF1a` and `ORF1b` notation. But to make it easier for users, it would be nice if our search bar supports the other notations as well and automatically translates them into our notation. I.e., if the user enters either `ORF1ab:4413L` or `nsp12:21L`, the auto-completion should suggest `ORF1b:12L`.

![image](https://user-images.githubusercontent.com/18666552/167654070-75e6482f-5f15-4652-95e4-68dbd6d233f4.png)

Further, if the user copy&pastes a comma-separated string like `nsp12:21L,nsp12:22P` into the search bar, it should convert the input to `ORF1b:12L` and `ORF1b:13P`.

GISAID uses the nsp notation and this feature would make it much easier to copy the mutations of a sequence shown on GISAID into cov-spectrum.

**Comment by anastasia-escher** [comment]
@chaoran-chen please check if it works correctly now.

**Comment by FedeGueli** [comment]
Great to hear!
