### ISSUE TITLE
UX tweak: changing from single variant to baseline mode

### ISSUE THREAD

**Issue by theosanderson** [GenSpectrum/cov-spectrum-website#497]
[low priority tweak]

The baseline comparison feature is incredibly useful. A regular situation I have is that I search for a particular variant of interest, e.g. BA.2.12.1 in single variant mode. And then I want to know how that variant compares to a baseline, like BA.2. So I click "Compare variants to a baseline" but my _Baseline_ is prepopulated with BA.2.12.1, whereas ideally for me _Comparing with_ would be prepopulated with this and the Baseline would be empty. Similarly if switching back the other way.

I can see why technically this might be a bit complex to implement, and can see that for switching from Baseline to Single with multiple lineages choosing the first one is a bit arbitrary, but IMO the tweak would be a plus overall.

Obviously not a big deal at all, but raising the issue after encountering it a few times.

**Comment by chaoran-chen** [comment]
Thanks for the feedback! @corneliusroemer already suggested it in #426 and it is very helpful to hear that you also see it this way.

**Comment by theosanderson** [comment]
Ah apologies, I tried a quick search but didn't see that!
