### ISSUE TITLE
Percent axis for Relative Growth Advantage plot

### ISSUE THREAD

**Issue by theosanderson** [GenSpectrum/cov-spectrum-website#498]
Did you ever consider having this axis in percent to match the Sequences Over Time graph? IMO that would be clearer when screenshotted (i.e. it's not totally clear if 0.1 means 10% or 0.1%)

**Comment by chaoran-chen** [comment]
I don't know if I ever noticed! It would for sure be better to have it more consistent. Thank you!

**Comment by chaoran-chen** [comment]
It took me ages to get to it but now it's finally fixed (2c0a148e5cb3d42b1751ed4239e966ce819c6d29). Thanks for the suggestion!
