### ISSUE TITLE
ENH: Set up staging branch to test potentially brittle new features

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/cov-spectrum-website#506]
I'd be very happy to try out new features in my standard usage of covSpectrum, before they are pushed to the live website.

Is there something like a staging branch that we could merge experimental PRs into? Or is this too complicated for now?

Would be good to test drive new features for a few days. Fixes could always get cherry-picked onto master, as well.

Maybe this sort of CI flow exists already and I'm just unaware of it, in which case it'd be nice if you could point me at the staging version @chaoran-chen

**Comment by chaoran-chen** [comment]
Aren't the current vercel builds for every PR enough?

**Comment by corneliusroemer** [comment]
Not really, because we always have multiple PRs open that we think have no bugs but we can't be sure without proper testing.

So right now there's very little solid testing before things end up live, which is OK I guess but not the most stable.

At Nextclade, we have master, which will get features that we consider ready to merge, so there shouldn't be bugs. That's what's on nextclade.vercel.app, if something pops up, we fix it then on master. And periodically we release from some fairly well tested commit on master.

The thing is, I can quickly try out a few things to check if a PR is ok, but for example the bug I spotted in #477 was kind of a lucky finding, because I monkey tested. These kinds of things are more easily found by more usage.

**Comment by chaoran-chen** [comment]
Okay, that's easy to do. We can push changes to develop but not to public immediately. The content in develop is deployed at https://cov-spectrum-develop.vercel.app/

**Comment by corneliusroemer** [comment]
Yep, exactly :) when there's an important fix, one can push immediately.
We could push to master after a few days. Tell people willing to be testers to use that beta version.
One could set up: covspectrum.dev, too, for the beta version. That's what we do for Nextclade, there's nextclade.dev ;)

**Comment by chaoran-chen** [comment]
Closing this as we already have a staging branch (`main`) deployed at https://cov-spectrum-develop.vercel.app/
