### ISSUE TITLE
BUG: When selecting `advanced search` checkbox, text gets deleted

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/cov-spectrum-website#507]
There's a bug when checking the `advanced search` checkbox: any text entered gets deleted.

I don't see any reason for this, it's rather annoying because one then needs to reenter any text that was there:

![image](https://user-images.githubusercontent.com/25161793/171676984-6af9b614-ac95-4fc1-8d49-f86319c3b75e.png)

To reproduce: uncheck checkbox, enter some text, e.g. `BA.2 & S:484K`, check checkbox, observe

**Comment by anastasia-escher** [comment]
Is it meant to be that when "advanced search" is on there are no autocomplete options?

**Comment by anastasia-escher** [comment]
Is it also a bug that the checkbox changes to be 'checked' only on second click (when used for the first time)?

**Comment by chaoran-chen** [comment]
> Is it meant to be that when "advanced search" is on there are no autocomplete options?

We don't offer an autocompletion for the advanced search. That's not the issue.

> Is it also a bug that the checkbox changes to be 'checked' only on second click (when used for the first time)?

Yes, that is a bug!

---

I just created #513 which is also about the search bar. Maybe the bugs are related and you can address them together?

**Comment by anastasia-escher** [comment]
Hi @corneliusroemer and @chaoran-chen , please check if it is the correct behaviour  (only #507 is addressed and not #513): 
https://cov-spectrum-develop-lpa0s4r84-cov-spectrum.vercel.app/

**Comment by chaoran-chen** [comment]
Hi @anastasia-escher, this looks good! I'm not sure if it is the original intent of Cornelius but I think that the behavior that you implemented is great.
