### ISSUE TITLE
Search bar does not change when selecting a known variant

### ISSUE THREAD

**Issue by chaoran-chen** [GenSpectrum/cov-spectrum-website#513]
How to reproduce:

1. Open a variant page (e.g., [this one](https://cov-spectrum.org/explore/Switzerland/AllSamples/Past6M/variants?aaMutations=S%3A452R&nucMutations=9866T%2C12160G&pangoLineage=BA.2*&)). We see that the variant is filled out in the search bar: 
![image](https://user-images.githubusercontent.com/18666552/177118674-a48e16bc-86c6-4078-ad92-d666921f3cfe.png)
2. If we now click on another variant (e.g., "BA.2* + S:452Q") in the known variant list on the left, the search bar does not change and looks like this:
![image](https://user-images.githubusercontent.com/18666552/177118900-556ee733-73c1-499b-aef5-b2cab5f92eb8.png)

**Comment by anastasia-escher** [comment]
Hi @chaoran-chen, if you are still not on vacation, please check this:
https://cov-spectrum-develop-ddt38aovs-cov-spectrum.vercel.app/explore/Switzerland/AllSamples/Past6M
