### ISSUE TITLE
Can a collection be private?

### ISSUE THREAD

**Issue by yexiao-cheng** [GenSpectrum/cov-spectrum-website#526]
Hi,

I noticed that you updated the `Collections` function, which I thought was very helpful. I wonder if users can make their collections private?

Many thanks for your answers!

Best,
Yexiao Cheng

**Comment by chaoran-chen** [comment]
Hi @yexiao-cheng, this is at the moment not possible. We might add it in the future (but probably not very soon).

**Comment by yexiao-cheng** [comment]
Thanks!
