### ISSUE TITLE
ORF9b vs. ORF9a discrepancy

### ISSUE THREAD

**Issue by JennKnapp** [GenSpectrum/cov-spectrum-website#530]
There is a discrepancy between ORF9b and ORF9a that I would like to draw attention to. 
When comparing BA.5 and BA.5.2.1 there is a single amino acid change that distinguishes the two, listed as ORF9b:D16G.
![ORF9b-D16G](https://user-images.githubusercontent.com/84808407/180492922-3a1a7faa-e345-41dd-a5f6-2fd25efec9b4.png)

When I obtain the reference sequence from GISAID for ORF9b, I get the following:
>EPI_ISL_402124-ORF9b
ATGCTGCAATCGTGCTACAACTTCCTCAAGGAACAACATTGCCAAAAGGCTTCTACGCAGAAGGGAGCAGAGGCGGCAGTCAAGCCTCTTCTCGTTCCTCATCACGTAGTCGCAACAGTTCAAGAAATTCAACTCCAGGCAGCAGTAGGGGAACTTCTCCTGCTAGAATGGCTGGCAATGGCGGTGATGCTGCTCTTGCTTTGCTGCTGCTTGACAGATTGA
Amino acid position 16 translates to a Lys(K)
>Translation_ORF9b
MLQSCYNFLKEQHCQ**K**ASTQKGAEAAVKPLLVPHHVVATVQEIQLQAAVGELLLLEWLAMAVMLLLLCCCLTD

However, looking up ORF9b on Uniprot brings up this protein sequence:
>sp|P0DTD2|ORF9B_SARS2 ORF9b protein OS=Severe acute respiratory syndrome coronavirus 2 OX=2697049 GN=9b PE=1 SV=1
MDPKISEMHPALRLV**D**PQIQLAVTRMENAVGRDQNNVGPKVYPIILRLGSPLSLNMARKTLNSLEDKAFQLTPIAVQMTKLATTEELPDEFVVVTVK
In which amino acid position 16 is in fact a D, but none of the other positions align either and the amino acid length is different.
This translation does however match the GISAID reference sequence for ORF9a:
>EPI_ISL_402124-ORF9a
ATGGACCCCAAAATCAGCGAAATGCACCCCGCATTACGTTTGGTGGACCCTCAGATTCAACTGGCAGTAACCAGAATGGAGAACGCAGTGGGGCGCGATCAAAACAACGTCGGCCCCAAGGTTTACCCAATAATACTGCGTCTTGGTTCACCGCTCTCACTCAACATGGCAAGGAAGACCTTAAATTCCCTCGAGGACAAGGCGTTCCAATTAACACCAATAGCAGTCCAGATGACCAAATTGGCTACTACCGAAGAGCTACCAGACGAATTCGTGGTGGTGACGGTAAAATGA

If we assume that the mutation ORF9b:D16G should actually be ORF9a:D16G, then it corresponds to the silent nucleotide change in the N gene reported for this lineage as well (A28330G).

The GISAID reference sequences for ORF9b and ORF9a are from this paper:
https://pubmed.ncbi.nlm.nih.gov/32015508/
![Wu-et-al-2020-ORFdefinitions](https://user-images.githubusercontent.com/84808407/180493307-536aa59e-c300-4c44-85a1-83bd58a079b1.png)

This paper is also cited by uniprot for their ORF9b sequence, but I think this should be ORF9a as well.

**Comment by chaoran-chen** [comment]
Hi @JennKnapp, I'm very sorry for the late reply! We just take the translations calculated by [Nextclade](https://github.com/nextstrain/nextclade/).

@corneliusroemer, @ivan-aksamentov, could you please take a look at the message above?
