### ISSUE TITLE
BA.2.12.1* does not pick up BG alias lineages

### ISSUE THREAD

**Issue by silcn** [GenSpectrum/cov-spectrum-website#531]
Searching for BA.2.12.1* only gives samples designated as BA.2.12.1, and misses its sublineages which have the alias BG.*. Other aliases are working as expected.

**Comment by chaoran-chen** [comment]
Thanks for reporting! The alias was missing in the database, it is now fixed.

You might need to clear your cache (or wait for the next data update) to see the correct results.
