### ISSUE TITLE
Open covSpectrum does not have NextcladePango

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/cov-spectrum-website#541]
I've noticed that `nextcladePangoLineage` advanced queries don't work in open covSpectrum (it would be nice if it did so we can use the same queries for editor's suggestion)

So I was wondering which lineage assignment method is used by open. I have the suspicion that it is Nextclade lineages, even though the lineages are listed as pangolin.

<img width="1517" alt="image" src="https://user-images.githubusercontent.com/25161793/182365080-98d06644-40a6-4192-9f72-6c8c45ffb394.png">

**Comment by chaoran-chen** [comment]
In the open version, we use the open dataset that Nextstrain provides and copy over values in the normal pango lineage field. Did you guys switch to Nextclade in the open dataset?

**Comment by corneliusroemer** [comment]
Which file exactly do you use? I can check what the method is.

In nextclade.tsv.gz it's definitely Nextclade Pango.

In metadata.tsv.gz both are present (I guess we get the pangolin part from Genbank).

<img width="604" alt="image" src="https://user-images.githubusercontent.com/25161793/182367702-fc8a4b30-2661-4032-9198-5daa3dc9a17e.png">

So it seems you use pangolin, not sure whether Usher or pangoLEARN 😬  I can try to figure it out

**Comment by chaoran-chen** [comment]
Yes, I've been using `pango_lineage` from metadata.tsv but good to know that `Nextclade_pango` is just next to it. It should then be quite easy to add.
