### ISSUE TITLE
Download mutation table

### ISSUE THREAD

**Issue by a-roguet** [GenSpectrum/cov-spectrum-website#544]
Hello covSpectrum team, 

Thanks for your amazing work, 
Is there a way to download the mutation list for each lineage/sublineage?
Best, 

Adelaide

**Comment by chaoran-chen** [comment]
Hi @AnehEf, thanks for reaching out! There is no such download button on the website yet but you could use the LAPIS API ([documentation](https://lapis-docs.readthedocs.io/en/latest/)). Here is a short Python script to download the mutations of all Pango lineages **using the open data**:

```
import os
import requests
from tqdm import tqdm

# Config
min_mutation_proportion = 0.5  # The minimal proportion for a mutation to be included
sequence_type = "nuc"  # Alternative: "aa"
file_format = "csv"  # Alternatives: "tsv", "json"
output_dir = './out'

# Create output dir if it does not exist
if not os.path.exists(output_dir):
    os.mkdir(output_dir)

# LAPIS URL
lapis_url = 'https://lapis.cov-spectrum.org/open/v1'
all_pango_lineages_url = lapis_url + '/sample/aggregated?fields=pangoLineage'
mutations_url = lapis_url + '/sample/{}-mutations?dataFormat={}&minProportion={}'\
    .format(sequence_type, file_format, min_mutation_proportion)

# Fetch all Pango lineages
pango_lineages = list(map(lambda x: x['pangoLineage'], requests.get(all_pango_lineages_url).json()['data']))

# Fetch the counts and proportions of all lineages
for lineage in tqdm(pango_lineages):
    if lineage is None:
        continue
    for include_sublineage in [True, False]:
        url = mutations_url + '&pangoLineage=' + lineage + ('*' if include_sublineage else '')
        result = requests.get(url).text
        file_name = '{}{}.{}'.format(lineage, '*' if include_sublineage else '', file_format)
        with open(os.path.join(output_dir, file_name), 'w') as f:
            f.write(result)
```

The GISAID instance of the API is unfortunately non-public. But I downloaded the data for you:

[nuc-mutations.zip](https://github.com/cevo-public/cov-spectrum-website/files/9267573/mutations.zip)

**Comment by chaoran-chen** [comment]
Just for completeness, here are the files with the amino acid changes:

[aa-mutations.zip](https://github.com/cevo-public/cov-spectrum-website/files/9268120/aa-mutations.zip)

**Comment by a-roguet** [comment]
Hello @chaoran-chen, 

Thank you very much for your response.
Is it because of the GISAID-API that I do not get the same outputs than you? For example with BA.5, I obtain mutations with proportions around 50%, while on cov-spectrum and in the files you sent, proportions are ~99%. 
Thanks, 

Adelaide

**Comment by chaoran-chen** [comment]
Thanks for noticing that, there were indeed a number of mutations missing/not being counted in the open data version! This has been fixed now. Sorry for the inconvenience!

**Comment by a-roguet** [comment]
Thank you so much.
