### ISSUE TITLE
Add quality filter for total number of unambiguous, aligned nucleotides

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/cov-spectrum-website#545]
Zach mentioned that he'd like to filter out a lot of Austrian partial sequences.

Right now Nextclade.tsv doesn't contain a ready-made coverage metric.

But something can be deduced easily: the number of aligned, non-ambiguous nucleotides.

That's equal to:
`sequenceLength - numberOfNs - ambiguousNucleotides + deletedNucleotides - insertedNucleotides`

That should give numbers between 0 and reference length.

Maybe the formula needs to be slightly different - but something like this should work really well. It basically says: how many informative sites do we have.

**Comment by corneliusroemer** [comment]
Relevant issue over at Nextclade: https://github.com/nextstrain/nextclade/issues/932#issuecomment-1208603840

**Comment by chaoran-chen** [comment]
What do you think when it might be addressed in Nextclade?

**Comment by corneliusroemer** [comment]
Hah, well, if there's a good use case in covSpectrum I can expedite this - just need to agree with @Ivan-aksamentov and Richard on the right metric to include.

I do think it will take at least a week, maybe two as it requires a significant software change.

**Comment by chaoran-chen** [comment]
Wow, that was quick - thanks @ivan-aksamentov for moving it along (https://github.com/nextstrain/nextclade/pull/956)! I'm happy to wait for you guys to decide on the right metric and will then include it in LAPIS on CoV-Spectrum.

**Comment by corneliusroemer** [comment]
Excellent, yeah I'll have a look at what Ivan did soon so we can get this moving forward :)

**Comment by chaoran-chen** [comment]
@corneliusroemer, how's the progress on Nextclade's side? :)

**Comment by ivan-aksamentov** [comment]
@chaoran-chen Cornelius is probably busy right now. On my side of things, I have nothing to add. It's pending scientific review (the formulas for the metric itself and for its QC score) and we need to decide on things I mentioned in the PR (whether it's a QC or not QC basically). Feel free to comment there.

**Comment by ivan-aksamentov** [comment]
@chaoran-chen The "coverage" metric has been released in [Nextclade 2.5.0](https://github.com/nextstrain/nextclade/releases/tag/2.5.0) (both Web and CLI)

**Comment by chaoran-chen** [comment]
Great, thank you!!
