### ISSUE TITLE
BUG: Clicking on "add variant" doesn't do anything

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/cov-spectrum-website#550]
I've noticed a recent bug.

E.g. using this page, if I click on "add variant" in baseline tab, the plots move a little but in the end nothing happens.

https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?variantQuery=NextCladePangoLineage%3ABA.2.75*+%26+S%3A574V&analysisMode=CompareToBaseline&

Not sure why and if this is reproducible. Sometimes, with other links, I can "add variant" - but not with this link.

**Comment by chaoran-chen** [comment]
Thanks for reporting the bug!
