### ISSUE TITLE
Placeholder of variant search field on mobile screen

### ISSUE THREAD

**Issue by anastasia-escher** [GenSpectrum/cov-spectrum-website#558]
A small style issue: placeholder of variant search field looks weird on mobile screen.
![Screenshot_20220810-122902_DuckDuckGo](https://user-images.githubusercontent.com/52914023/184080209-f73b7e7f-eafc-4aff-9a10-16c4ddd3b0dc.jpg)

**Comment by chaoran-chen** [comment]
I actually just fixed it yesterday night in 77dcdddf791f9779767bc735d157d389ed8e6e67 ;)

**Comment by anastasia-escher** [comment]
@chaoran-chen oh, ok :)
