### ISSUE TITLE
Proper error handling

### ISSUE THREAD

**Issue by tehwalris** [GenSpectrum/cov-spectrum-website#56]
- Treat non-200 status from the server as an error
- Show the user something useful when stuff fails to load
- Add [error boundaries](https://reactjs.org/docs/error-boundaries.html)
  - Currently our application will fully crash if the server replies with invalid data (eg. because it's down)

**Comment by chaoran-chen** [comment]
If I'm not mistaken, we only have functional components with hooks but error boundaries do not work with hooks, yet (see [react hooks FAQ](https://reactjs.org/docs/hooks-faq.html#do-hooks-cover-all-use-cases-for-classes)). Do you have a suggestion on how to use error boundaries in our application?

**Comment by tehwalris** [comment]
I think what the FAQ means is that you can't create an error boundary using hooks, but you *can catch* errors thrown by hooks using an error boundary. In our case we could (for example) add one extra class component wrapping the focus panel, which would catch any errors that occur in the focus panel. I've never used error boundaries myself though, so maybe I'm misunderstanding the FAQ.

**Comment by ningxie1991** [comment]
@chaoran-chen @TKGZ 

I am trying to reproduce such error by adding random characters to the api url and is the below screenshot an example of this issue?

![image](https://user-images.githubusercontent.com/3387698/128312836-f5fe847d-02f3-43c5-8ddf-ae0c64a633ce.png)

**Comment by spacephoton** [comment]
I think non 200 errors the server should have a response with an error message, but I'm not too familiar @chaoran-chen should know bettet

**Comment by chaoran-chen** [comment]
@ningxie1991, yes that would be such an example!

We should handle non-200 codes but not use the error messages because they are not really defined/implemented intentionally - yet.
