### ISSUE TITLE
Bring back "csv download"

### ISSUE THREAD

**Issue by chaoran-chen** [GenSpectrum/cov-spectrum-website#561]
I removed the `fast-csv` package in #560 because it was causing trouble. The last release of the package was two years ago so I think it's a good idea to replace it.

The CSV download depended on it. For now, it is disabled but we should bring it back.

![image](https://user-images.githubusercontent.com/18666552/184132534-c9c967fd-07c3-48e5-9446-5776254836ab.png)

![image](https://user-images.githubusercontent.com/18666552/184132691-189fea60-2b60-4c6e-88a5-492e17e6718e.png)

**Comment by anastasia-escher** [comment]
What about this one? 
https://www.npmjs.com/package/react-csv

**Comment by chaoran-chen** [comment]
Looks good! Would you like to implement it?

**Comment by chaoran-chen** [comment]
Although 40.9 kB is quite a lot for such a simple feature. I wonder if there is a slimmer library.

**Comment by anastasia-escher** [comment]
> Although 40.9 kB is quite a lot for such a simple feature. I wonder if there is a slimmer library.

I'll also look for something else.  But react-csv is the one we use in Mpox-spectrum, isn't it (at least I think I have used it there once)?

**Comment by chaoran-chen** [comment]
I don't think that we are transforming any JSON to CSV in MpoxSpectrum and the package.json does not list react-csv
https://github.com/cevo-public/mpox-spectrum-website/blob/main/package.json

**Comment by anastasia-escher** [comment]
> I don't think that we are transforming any JSON to CSV in MpoxSpectrum and the package.json does not list react-csv https://github.com/cevo-public/mpox-spectrum-website/blob/main/package.json

Right, I confused it with something else, sorry.
