### ISSUE TITLE
Different output searching variants country vs global

### ISSUE THREAD

**Issue by jrotieno** [GenSpectrum/cov-spectrum-website#569]
I was looking for BA.2.75* on the web interface and using the global setting I got 21 countries.

When I used the API, I got 28 countries. One of the countries missing in the web global search was Cambodia.

When I set the search to Cambodia and BA.2.75* (web), the one sample shows up.

Why is it missing in the global?

Is it the database or myself?

**Comment by chaoran-chen** [comment]
Hi @jrotieno, thank you very much for reporting the bug! There was an error that caused sequences without a known division to be excluded. This has been fixed now.

**Comment by jrotieno** [comment]
Thanks for resolving @chaoran-chen!
