### ISSUE TITLE
ENH: Provide GISAID-query for copy/paste, saving time

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/cov-spectrum-website#573]
For new lineages, the 3d delay between GISAID and covSpectrum is often critical so I go and check on GISAID directly.

Unfortunately, GISAID uses different AA names, so it's quite tedious to create these queries.

It would not be too hard but save a lot of time if covSpectrum could convert a covSpectrum AA query to a GISAID AA query.

Basically all one needs to do is turn things like `ORF1a:2243B, S:484K` to `NSP3_A154B, Spike_E484K`

Maybe covSpectrum isn't the right place, maybe this should sit with @theosanderson's codon2nucleotide - but there's definitely a need for this. I'm tired of doing the manual conversion :/

**Comment by theosanderson** [comment]
It's a neat idea (I probably don't plan to do it as part of codon2nucleotide I'm afraid)

**Comment by corneliusroemer** [comment]
Most important things are: 
- Turn ORF1a/b + position into whatever format GISAID expects
- Sub in the origin AA if it's missing (e.g. S:346T lacks the R which I don't want to have to look up manually every time - it's a quick lookup in a lookup table in code)

**Comment by chaoran-chen** [comment]
@corneliusroemer, thanks for the suggestion! I barely use the gisaid interface, would you be able to provide a clear specification of the transformation?

**Comment by corneliusroemer** [comment]
Yes absolutely! I will write one :)

**Comment by FedeGueli** [comment]
it could be great if "open in other website" would have an option open in Codon2 nucleotide and get the query transformed to Gisaid Format. @theosanderson dunno if possible.
