### ISSUE TITLE
Deleting a line from a collection can cause a crash, and change other lines

### ISSUE THREAD

**Issue by Sinickle** [GenSpectrum/cov-spectrum-website#574]
In my experience, the crash is very reproducible, and the changes to lines are less reproducible, but I'm very confident they happen. 
This has happened in multiple collections for me. Possibly only when deleting a line that isn't last on the list. 

Issue 1: It will crash soon after, but not immediately after deleting the line. Clicking save will cause the crash immediately, but only after saving is complete. (ie, system becomes unresponsive, and issue does not resolve)
Issue 2: The bottom line on the collection will take the query of the line that was above it. One time when I deleted multiple lines, the bottom 3 lines on the collection all ended up with the same query. Additionally, sometimes I can visually see that the bottom line's query is rapidly (many times per second) switching between the original query, and the line above it.

**Comment by FedeGueli** [comment]
Yeeah it is quite an issue cause collections are usually updated by more than 1 people of our group, Example today i uploaded lineages already in collection in 23 when i went to delete it messed up everything. i hope it was not damaged permanently @chaoran-chen

**Comment by Sinickle** [comment]
The workflow I'm using for deleting lines is to scroll to the bottom of the list, make note of what the name of that bottom line is, copy the query, go and delete whatever line I intend to delete, save, refresh, and then search for the name of what was the bottom line (sometimes it no longer is at the bottom?) and then add back in the query if it got messed up. 
I think there's a 50% chance it gets messed up, reflecting the 100% chance that it starts visually swapping back and forth between the correct and incorrect query as soon as you delete a line, which then gets locked in place when you hit save.

**Comment by chaoran-chen** [comment]
Thanks @Sinickle and @FedeGueli for reporting and sorry for the slow response! I'll investigate it in the upcoming days!

**Comment by chaoran-chen** [comment]
The problem should have been resolved. If not, please reopen!
