### ISSUE TITLE
Bugs related to the sampling strategy selection

### ISSUE THREAD

**Issue by chaoran-chen** [GenSpectrum/cov-spectrum-website#58]
Hi @tehwalris, I found two bugs:

- `/explore/Switzerland/` is currently redirecting to `/explore/Switzerland/variants` which does not work. Could you change the target to `/explore/Switzerland/AllSamples`, please?
- When we select "Surveillance" for Switzerland and then switch the country, the surveillance selection will stay and unchangeable. I suggest to switch to AllSamples automatically for countries that do not support the current selection. Screenshot:

![image](https://user-images.githubusercontent.com/18666552/111086703-ed7efb80-851d-11eb-908b-106397b2fcb5.png)

**Comment by tehwalris** [comment]
Thanks for finding these! These are definitely both bugs.

For the first one: I made a mistake and assumed that our old URLs ended with `/variants`. Fixed [here](https://github.com/cevo-public/cov-spectrum-website/commit/70258974ea2c0919d11dff0cc0a8baacdf12dbad).

For the second one: I forgot to make the toggle switch sampling strategy when it's not valid after I switched to using URLs. This is fixed [here](https://github.com/cevo-public/cov-spectrum-website/commit/8eae0e3b094f48983b3942a9272d79f787d07bd1). Note that if you set "Switzerland - Surveillance", then switch to "Germany" you will be switched to "All samples". If you then switch back to "Switzerland" you will be on "All samples" and not "Surveillance". I guess this is acceptable behavior.
