### ISSUE TITLE
Filter by submission date

### ISSUE THREAD

**Issue by chaoran-chen** [GenSpectrum/cov-spectrum-website#581]
Currently, the date filter filters by sampling date. It would be great if there is an option to filter by submission date.

**Comment by corneliusroemer** [comment]
That could help a lot with evaluation of prediction tools to simulate different data availability.

One thing to be aware of: it could be that the submission date is not the same as release data.

I notice that sometimes submission is 2 days earlier than the release on GISAID. But these are outliers.

**Comment by chaoran-chen** [comment]
For the URL, I suggest adding:

If a special date range is selected: `dateSubmitted=Past6M`

If a fixed date range is selected: `dateSubmittedFrom=2021-08-01&dateSubmittedTo=2021=09-28`, it should also be possible to only set `dateSubmittedFrom` or only `dateSubmittedTo` if the date range is open on one end.

**Comment by corneliusroemer** [comment]
This would be such an amazingly useful feature - thanks for working on it @chaoran-chen and @anastasia-escher 😍

**Comment by chaoran-chen** [comment]
Closed in #654
