### ISSUE TITLE
Changes of mutation proportion over time (within a variant)

### ISSUE THREAD

**Issue by chaoran-chen** [GenSpectrum/cov-spectrum-website#583]
It is interesting to see how the proportion of a mutation within a variant change over time.

One idea is to add small line plots next to the entries in the mutation table that can look like this:

![image](https://user-images.githubusercontent.com/18666552/187636394-fbdda674-a5fd-4584-a8bd-43ef12deb005.png)

We could also add a table showing the proportions of different weeks/months/percentiles (e.g., first/second/... quarter of the selected time range) and put it into a deep focus page.

**Comment by corneliusroemer** [comment]
That's a super cool idea - little spark lines https://en.wikipedia.org/wiki/Sparkline

Though having a metric that would be sortable like the Jaccard similarity would also be very useful

**Comment by anastasia-escher** [comment]
Or it could be a tooltip with a bigger plot image.
