### ISSUE TITLE
BUG: Last update of open covspectrum was 14th of August?

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/cov-spectrum-website#584]
Just noticed that the last update of open covspectrum was on the 14th of August, more than 2 weeks ago.

Not sure if you were aware @chaoran-chen 

<img width="1898" alt="image" src="https://user-images.githubusercontent.com/25161793/187930724-773971f9-5860-41ac-8d5f-c0b9270d466a.png">

**Comment by chaoran-chen** [comment]
I didn't notice, thanks for reporting!

**Comment by chaoran-chen** [comment]
The data update pipeline is working again.

**Comment by chaoran-chen** [comment]
The data update pipeline is working again.
