### ISSUE TITLE
BUG: Dropdown for "Other websites" has gap from trigger button, causing UX issues

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/cov-spectrum-website#590]
I remember this being an issue in the past, but I particularly noticed this during your presentation to SPHERES, where you struggled with this while giving the talk @chaoran-chen 

![2022-09-05 17 51 13](https://user-images.githubusercontent.com/25161793/188493091-0487683d-6d78-49dc-946a-5fe685790ffd.gif)

I can reproduce this problem on Safari on my Mac. But this seems to be a more universal issue given that you had it, too.

**Comment by chaoran-chen** [comment]
Yes, that's indeed annoying.

@anastasia-escher, could you please take a look at this when you have time?
