### ISSUE TITLE
ENH: Allow manual setting of number of rows shown in collections table

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/cov-spectrum-website#592]
I'd like to see all rows in a collections table - unfortunately the max is 100 right now - which isn't enough for my usage.

<img width="529" alt="image" src="https://user-images.githubusercontent.com/25161793/189103026-02ee367f-6f19-488f-9118-68aabd757370.png">

Either: make the max much bigger, e.g. 500, and/or let the user manually set it.

**Comment by chaoran-chen** [comment]
This is unfortunately not possible with the free version of the MUI Datagrid library that we use (https://mui.com/x/react-data-grid/pagination/#size-of-the-page). I'll keep this issue around but it can only be implemented if we choose to switch to a different data grid library.

**Comment by corneliusroemer** [comment]
Ah that's a shame. 

Maybe we could ask for sponsorship? :)
