### ISSUE TITLE
ENH: Collections, Flag Lineages as Special option

### ISSUE THREAD

**Issue by FedeGueli** [GenSpectrum/cov-spectrum-website#595]
Hi it would be great if possible to have the option to flag lineages while editing as SPECIAL (Call them as you like)
and then for users to.have a flag in each collection  as 'show specials only'  to create a shortlist of only the lineages flagged as special while editing by maintainer(s)

**Comment by corneliusroemer** [comment]
I agree this would be useful - allowing us to quickly elevate a lineage and reducing duplication

**Comment by chaoran-chen** [comment]
Thanks for the suggestion! This sounds like a good idea and easy enough to implement.
