### ISSUE TITLE
BUG: Collections crash when there's a 400

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/cov-spectrum-website#602]
Just noticed that collections crash. Looked at the console and there was a 400 for a request.

<img width="2551" alt="image" src="https://user-images.githubusercontent.com/25161793/191445815-b7bed131-7b4e-4896-bcbd-3c1e6126ac5c.png">

This collection crashes: https://cov-spectrum.org/collections/24

Other collections don't crash so this must be a validation/error catching oversight.

**Comment by corneliusroemer** [comment]
For this query:
<img width="447" alt="image" src="https://user-images.githubusercontent.com/25161793/191446144-89aaa4f7-e2c3-407f-8208-9357b4a0846f.png">
with aaMutations
```
 S:I68T,ORF1a:D3936N,nuc:T19452C
```

**Comment by chaoran-chen** [comment]
I fixed the collection by correcting the mutation query and will work on the issue that crashes the whole collection later.
