### ISSUE TITLE
ENH: Switch default lineage tab to Nextclade, in line with search default

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/cov-spectrum-website#603]
With GISAID pango lineages very out of date and the shift to default lineage search to Nextclade, it would be good to also shift the tab to Nextclade by default:

<img width="2089" alt="image" src="https://user-images.githubusercontent.com/25161793/191469270-3ec1825b-ed7d-4d89-9098-e705443309b0.png">

And the `(pangolin)` should probably be replaced with `pangoLEARN` to be precise - Usher would give very different results.

**Comment by chaoran-chen** [comment]
Re. default: sure, I can change that.

Re. writing "pangoLEARN": but for the open version, we take the preprocessed data from Nextstrain, and there, it's UShER? And another problem is that we won't get informed if GISAID should decide to switch to UShER.

**Comment by corneliusroemer** [comment]
Correct, it's Usher for Genbank.

I will inform you if GISAID switches, it's visible in the webapp.

**Comment by chaoran-chen** [comment]
I resolved the first part of the issue which is consistent with the title. Feel free to create a new issue for the second part which I might address at a later time.
