### ISSUE TITLE
Lineage XAN* (Nextclade) seems to include too many sequences?

### ISSUE THREAD

**Issue by Mike-Honey** [GenSpectrum/cov-spectrum-website#614]
Apologies if this is should be addressed to Nextclade.

I noticed the XAN* (Nextclade) lineage is reporting 37K+ sequences, which seems too high.
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?nextcladePangoLineage=XAN*

From the pango designation discussion, I was expecting under 100:
https://github.com/cov-lineages/pango-designation/issues/771

Searching for the GISAID query: Spike_F486V, NSP3_L1752M, NSP13_P529L, NSP4_L438F gave me 74.

Perhaps only the Spike mutation is being filtered?

**Comment by chaoran-chen** [comment]
Hi @Mike-Honey, I think that this should indeed be addressed to Nextclade. 

Ping @corneliusroemer, @ivan-aksamentov

**Comment by corneliusroemer** [comment]
Crosspost answer from https://github.com/nextstrain/nextclade/issues/1022

> 
> Simple reason: the 37k are almost all Spike-only sequences from Austria/South Korea.
> 
> Nextclade is currently not written to handle these perfectly. If the Spike of a recombinant is the same as of the actual lineage the sample is from, then currently a recombinant is often assigned because of the way Nextclade assigns lineages.
> 
> We are aware of this issue and will address it in the mid-term.
> 
> For now, you can avoid it by setting minimum coverage to 90% in advanced mode on covSpectrum
> 
> <img width="414" alt="image" src="https://user-images.githubusercontent.com/25161793/196166240-faff1d65-c4fa-4939-b21e-7f9d3ab39265.png">
> 
> <img width="2481" alt="image" src="https://user-images.githubusercontent.com/25161793/196166245-f9d4b65d-bdf5-4c15-a81d-4e249771694f.png">
> 
> <img width="2553" alt="image" src="https://user-images.githubusercontent.com/25161793/196166255-e5d6faea-5e84-4a05-9429-0d55cda1be1a.png">
> 
> That makes the issue go away.

**Comment by corneliusroemer** [comment]
To address this, we may want to set the default to 0.9 coverage maybe @chaoran-chen?
