### ISSUE TITLE
Stable color assignments in plots

### ISSUE THREAD

**Issue by chaoran-chen** [GenSpectrum/cov-spectrum-website#619]
In plots with multiple lines (variant comparison and international comparison), the colors are currently randomly assigned and change upon every reload. Even worse, when we use the "show regions" function to see a grid of plots, the color assignments are different for each plot (see screenshot below). In addition, there is no mechanism that tries to make the colors as distinguishable as possible.

We can solve it by manually defining a list of (a sufficient number of) colors. Giving a list of items that need different colors, we can sort the items and assign the colors in that order.

The idea is from @SarahNadeau - thank you very much!

---

![image](https://user-images.githubusercontent.com/18666552/196135847-f74ddb3e-9b62-40a5-b57c-7710c704c08d.png)

**Comment by corneliusroemer** [comment]
Yep, that'd be amazing - I've also thought about this (and maybe even mentioned it?) in the past.

Would be good to have a proper legend embedded as well - the tooltip is not great for screenshot graphs
