### ISSUE TITLE
BUG: Advanced query not working with nextstrainClade:recombinant

### ISSUE THREAD

**Issue by AnonymousUserUse** [GenSpectrum/cov-spectrum-website#621]
I've noticed that the advanced query mode seems not to function with nextstrainClade:recombinant while recombinant (Nextstrain clade) works fine with them.

This works:
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?nextstrainClade=recombinant&

But this doesn't:
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?variantQuery=nextstrainClade%3Arecombinant&

**Comment by corneliusroemer** [comment]
Yep, noticed this, too. Would be nice if recombinant worked as a clade.

**Comment by chaoran-chen** [comment]
thanks for the suggestion! I'll put it onto the todo list.

**Comment by corneliusroemer** [comment]
I think I must have dreamed about this working: tried it out, didn't work, checked status and it's on todo :)

**Comment by AnonymousUserUse** [comment]
> I think I must have dreamed about this working: tried it out, didn't work, checked status and it's on todo :)

Me too. When can I expect that this will work?
