### ISSUE TITLE
ENH: shorten the interval that data is used in collection or allow users to set the interval

### ISSUE THREAD

**Issue by AnonymousUserUse** [GenSpectrum/cov-spectrum-website#622]
I suppose either to shorten the interval that data is used in collection from the past 6 months to the past 2 months, or to allow users to select the interval that data is used, or both (enable to select the interval with default past 2 months). 

Reason: considering the fact that the circulating variant (even with chosen baseline) changes quickly, growth advantage six months ago is not really meaningful. In addition, using a shorter interval also makes the calculation more quickly.

Thanks.

**Comment by corneliusroemer** [comment]
I agree, I've been bothered by this in the past as well.

Maybe the reason for a preset interval is to not overload the server. In that case, a few presets would do - as opposed to letting the user choose freely which would create a lot of queries.

But regions are freely settable, so this doesn't quite explain. Maybe just to keep things simple while prototyping.

**Comment by chaoran-chen** [comment]
Thanks for the suggestion! We already have a plan to add a date filter (#518). I hope that it will be released soon.
