### ISSUE TITLE
Hospitalization / death rate plots

### ISSUE THREAD

**Issue by chaoran-chen** [GenSpectrum/cov-spectrum-website#63]
Hospitalization and death rate plots should be created for the private Switzerland area.

https://github.com/cevo-public/cov-spectrum-docs/blob/develop/API.md#sample-new provides all the needed information.

**Comment by chaoran-chen** [comment]
When calculating the hosp./death rate, we should only use data from up to one month ago because it takes time until an infected person needs to be hospitalized or dies. We should then also add a note explaining that.

**Comment by spacephoton** [comment]
Are we also interested in monthly here? @chaoran-chen (month by month)

**Comment by chaoran-chen** [comment]
Ah, thanks for asking! I forgot to specify an important detail!

We assume that the hospitalization/death rate of a variant depends on the age but does not vary through time. That means that we would like to see the rates per age group.

**Comment by spacephoton** [comment]
Thanks!
