### ISSUE TITLE
Lineage DJ.1 not appearing in cov-spectrum search

### ISSUE THREAD

**Issue by InfrPopGen** [GenSpectrum/cov-spectrum-website#651]
Searching for lineage DJ.1 (and DJ.1* (Nextclade)) returns zero sequences world wide; however, DJ.1 had over 80 known sequences at time of designation on 23rd November 2022, and has been growing since.

[Example search](https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?nextcladePangoLineage=DJ.1*&)

There is currently elevated interest in DJ.1 and that has prompted me to enquire.

Thank you.

**Comment by chaoran-chen** [comment]
Hi @InfrPopGen, I believe that DJ.1 is not supported by Nextclade yet - or did I miss a Nextclade update? (ping @corneliusroemer)

**Comment by InfrPopGen** [comment]
Thanks @chaoran-chen , the same issue occurs if searching plain "DJ.1" or "DJ.1*".

I was wondering if this is related to the fact that the current version of pangolin [v1.16] is dated November 7th, which predates the DJ.1 designation, and this might also have something to do with the lack of Nextclade support. In which case, this issue should resolve itself soon, and I can close this, at least until v1.17]

**Comment by corneliusroemer** [comment]
Yep - I'm working on a new dataset, should be there soon!

You can try: `BA.5.1.25* (Nextclade) + S:K444N` until then

https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3AK444N&nextcladePangoLineage=BA.5.1.25*
