### ISSUE TITLE
Sequence counts mismatch - cov-spectrum.org vs lapis.cov-spectrum.org

### ISSUE THREAD

**Issue by vsrdharca** [GenSpectrum/cov-spectrum-website#652]
Hello -

I am trying to compare the counts I get via cov-spectrum.org vs lapis.cov-spectrum.org and unfortunately the numbers don't match.

Example - 1

https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?variantQuery=%5Bexactly-5-of%3A+S%3A346%2C+S%3A356%2C+S%3A444%2C+S%3A445%2C+S%3A450%2C+S%3A446%2C+S%3A452%2C+S%3A460%2C+S%3A486%2C+S%3A490%2C+S%3A494%2C+S%3A493Q%5D%26+%21+%28S%3A346-+%7C+S%3A356-+%7C+S%3A444-+%7C+S%3A445-+%7C+S%3A450-+%7C+S%3A446-+%7C+S%3A452-+%7C+S%3A486-+%7C+S%3A490-+%7C+S%3A494-%29+%26+%21nextstrainClade%3A21K&

Total - 62,712

curl -X 'GET' \
  'https://lapis.cov-spectrum.org/open/v1/sample/aggregated?fields=pangoLineage&variantQuery=%5Bexactly-5-of%3A%20S%3A346%2C%20S%3A356%2C%20S%3A444%2C%20S%3A445%2C%20S%3A450%2C%20S%3A446%2C%20S%3A452%2C%20S%3A460%2C%20S%3A486%2C%20S%3A490%2C%20S%3A494%2C%20S%3A493Q%5D%26%20%21%20%28S%3A346-%20%7C%20S%3A356-%20%7C%20S%3A444-%20%7C%20S%3A445-%20%7C%20S%3A450-%20%7C%20S%3A446-%20%7C%20S%3A452-%20%7C%20S%3A486-%20%7C%20S%3A490-%20%7C%20S%3A494-%29%20%26%20%21nextstrainClade%3A21K&downloadAsFile=false&dataFormat=json' \
  -H 'accept: application/json'

Total across all lineages - 19,584

Example - 2

Even simple query that searches number of sequences acros say BQ.1.1 across both these gives very different numbers.

Seems like the Open API is missing data.

Can you please advice if I am maybe not using the API properly or confirm if there is an issue with the LAPIS Open API end point?

Thank you.

**Comment by vsrdharca** [comment]
much appreciate any help - @chaoran-chen

**Comment by chaoran-chen** [comment]
Hi @vsrdharca, sorry for the slow reply! The open API uses data from GenBank whereas the main dashboard at cov-spectrum.org uses data from GISAID. The latter has much more sequences (14 million vs 6.4 million).

We also have a GISAID-based API. However, due to the data-sharing regulations of GISAID, we unfortunately cannot share that API with the public.

**Comment by vsrdharca** [comment]
Thank you @chaoran-chen
