### ISSUE TITLE
Export sequence or csv with mutations

### ISSUE THREAD

**Issue by a-qvecell** [GenSpectrum/cov-spectrum-website#656]
Hi :)
Thank you for a great webpage.

We map spike sequences to a set of references that we sometimes update based on new variants. 

I can use your page to find e.g. XBB sequences from the entire world and filter for mutations with a frequency of e.g. 50 %, which is very nice.
But I cannot seem to find a good way to export this information to get a prototype of e.g. an XBB (spike) sequence.
It would be really helpful if there was a way to export either
- a sequences having the mutations (either whole genome, a selected gene or maybe even from nt x to nt y)
or 
- a csv with the mutations so that I can use them as input to a script and introduce the mutations into the Wuhan_wt sequence myself.

This would be such a nice feature :)
Have a nice day,
best,
Amanda

**Comment by chaoran-chen** [comment]
Hi Amanda! In the "open" instance (using data from the public domain), it is possible to download the sequences. E.g., open [this page](https://open.cov-spectrum.org/explore/World/AllSamples/Past6M/variants?nextcladePangoLineage=XBB*&) and click on the "sequence" button on the top right. Then, you can choose to download the sequences as a fasta file.

![image](https://user-images.githubusercontent.com/18666552/208881494-12c099b9-b69c-47a8-b9fa-fc5c9c8644a7.png)

For the GISAID-based instance, we are unfortunately not allowed to share the raw sequences.

**Comment by a-qvecell** [comment]
Hi :)
Thank you for the speedy reply. That is indeed a very neat feature. However, I still seem to get sequences with less common mutations. Maybe the solution is to just retrieve the seqs and generate a consensus. I was just wondering if there was a better way to get a "canonical" XBB S sequence (if you know of anywhere to get such a thing, please let me know ;) ).

**Comment by chaoran-chen** [comment]
Ah, I see. That's an interesting idea. Yes, I think that we can offer a feature to download the canonical/consensus sequence of a variant.

**Comment by a-qvecell** [comment]
That would be so nice :)
Looking forward to an implementation!

**Comment by chaoran-chen** [comment]
Done! @a-qvecell, is that as you expected?

![image](https://user-images.githubusercontent.com/18666552/209008508-3f7b1d20-9a97-40ba-ae12-cc76576c04c2.png)

**Comment by a-qvecell** [comment]
Yay :') Thank you so much!
