### ISSUE TITLE
Crash when deleting days in submission date filter

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/cov-spectrum-website#659]
Congrats on the submission date feature 🎉 

When I tried to change the date, deleting the days, the website crashed, see screencast:

![2022-12-21 23 11 34](https://user-images.githubusercontent.com/25161793/209012240-18a8ce3b-8c68-42c3-9fcd-6e66688e91e0.gif)

Workaround: use the date picker

**Comment by corneliusroemer** [comment]
Same bug actually happens for the main date picker as well, so more critical

**Comment by chaoran-chen** [comment]
Duplicate of #655 :)
