### ISSUE TITLE
Inconsistency in the name and the query of a variant from editor's choice

### ISSUE THREAD

**Issue by AnonymousUserUse** [GenSpectrum/cov-spectrum-website#660]
![image](https://user-images.githubusercontent.com/113214374/209725074-66bf99b9-b64c-4282-bc6a-03def713b0a9.png)

The name BQ.1* + S:R346T + S:144del is apparently inconsistent with the query nextcladePangoLineage:bq.1.1* & s:346t & s:144-. 
Personally speaking, I think monitoring nextcladePangoLineage:BQ.1* & S:346T & S:144- would be better.

@chaoran-chen

**Comment by chaoran-chen** [comment]
Thanks for reporting!

@Sinickle, what do you think?

**Comment by Sinickle** [comment]
@AnonymousUserUse @chaoran-chen Thanks for creating the issue and tagging me! 
I've updated it as @AnonymousUserUse suggested -- I believe this is what I had intended, and I forgot to update the query for this item. 

I believe the issue can be closed now.

**Comment by AnonymousUserUse** [comment]
Thanks, it has been corrected and I will close this issue now.
