### ISSUE TITLE
English name of 内蒙古自治区 should be Inner Mongolia instead of Nei Mongolia, leading to the problem that sequences from Inner Mongolia cannot be illustrated in the map

### ISSUE THREAD

**Issue by AnonymousUserUse** [GenSpectrum/cov-spectrum-website#662]
BUG: English name of 内蒙古自治区 should be Inner Mongolia instead of Nei Mongolia, leading to the problem that sequences from Inner Mongolia cannot be illustrated in the map
![image](https://user-images.githubusercontent.com/113214374/210479854-d50fa307-ac8f-4b47-9163-f7cde45cbfdb.png)
@chaoran-chen

**Comment by chaoran-chen** [comment]
Thank you very much for reporting the bug!
