### ISSUE TITLE
Suggestion: add description of "Relative growth advantage" plot (comparison to baseline)

### ISSUE THREAD

**Issue by flodebarre** [GenSpectrum/cov-spectrum-website#666]
The "Relative growth advantage" plot in "Compare variants to a baseline" seems to sometimes be misunderstood. Not only do some people not realise that a proportion is plotted and not a percentage, but some people also do not seem to realise that the plot does not show the proportion of the variant of interest among all sequenced variants, and that the values change when a different baseline is chosen ([recent example on Twitter](https://twitter.com/Tuliodna/status/1612516843788328981?s=20&t=CbimkA0jb0ZtdIkTUo-ecQ)). 

Would it be possible to add a quick description of what the dots actually represent in the text near the plot? In particular, the use of the plural "_compared to co-circulating strains_" in the current description is a bit confusing when a single baseline is chosen (but maybe I also misunderstand the plot??). 

You could for instance consider adding the definition using the names of the selected variants, which are currently not shown on the plot. 

Thanks!

**Comment by chaoran-chen** [comment]
Thanks for the suggestions, @flodebarre! I changed the text to say "compared to the selected baseline" if the corresponding comparison mode is being used. Further, the axes now show percentages.

<img src="https://user-images.githubusercontent.com/18666552/212565178-e0438826-fa26-49ae-a095-9833dbec652e.png" width="400" />

(Resolved in 7c914d410f6c9b54183218e20edc76dfd561004b and 2c0a148e5cb3d42b1751ed4239e966ce819c6d29)
