### ISSUE TITLE
Export mutations with proportion < 0.10 %

### ISSUE THREAD

**Issue by a-qvecell** [GenSpectrum/cov-spectrum-website#667]
Hello :)
Thank you for a nice webpage that is both useful and easy to navigate. 

I am looking for a way to get a list of all mutations observed (all times, all geographical regions), and I can select data from these sequences using your page However, when I try to get all the mutations by setting limits from 0.0% to 100 %, I only get mutations that are seen in 0.1 % of sequences or more. 
I was wondering if you could change the filtering, so that it is possible to get mutations observed with frequencies that are below 0.1 %.

Best regards, 
Amanda

**Comment by chaoran-chen** [comment]
okay! It should now be possible.

**Comment by a-qvecell** [comment]
Yay, thank you!

**Comment by a-qvecell** [comment]
Hi :) 
Sorry to bother you with this again, but every time I (or others in our institution) try to export the rare mutations seen in the world across all times, the page is stalling/crashing.
This has been a problem for the two past weeks or so but not previously.

Has anything changed or is it the number of sequences just being too high? I have tried for just a single country, and the page stalls for a while, but in the end, I was able to download the file.
Specifically, I am looking for amino acid mutations occurring with 0,0%-0,2% abundance across the world at all times :) 
Can you help me?

Best wishes,
Amanda
