### ISSUE TITLE
Improve the look of the country selection

### ISSUE THREAD

**Issue by chaoran-chen** [GenSpectrum/cov-spectrum-website#68]
The country (and region) selection in the top bar deserves an improvement :)

See also #67

**Comment by spacephoton** [comment]
Do you think a selection similar to comparison could work and be useful? 
![image](https://user-images.githubusercontent.com/36269621/117179512-7bb38780-add3-11eb-86f6-66205b50ac21.png)

I personally don't think it's useful for everything, so probably not worth investing the effort for it.

What improvements do you have in mind @chaoran-chen?

**Comment by chaoran-chen** [comment]
I think that it is not the most important task right now, so I will move it back to the backlog.

**Comment by chaoran-chen** [comment]
One reason to have an advanced country/region selection would be to make it clearer that it is possible to select a continent (and eventually the whole world). Maybe we can show something like this if the user clicks on the country selection? (The circles represent flags or a symbol for a region)

![image](https://user-images.githubusercontent.com/18666552/118054383-754e7e00-b386-11eb-9030-77287de6a99d.png)

And when the user starts to type, it will filter.

We could also additionally group the countries by continent. This way, a user with not the best geographic knowledge can easily click through the countries on a continent.

**Comment by chaoran-chen** [comment]
The view is good enough for now.
