### ISSUE TITLE
DU.1 isn't considered a BQ.1 sublineage..?

### ISSUE THREAD

**Issue by Sinickle** [GenSpectrum/cov-spectrum-website#685]
Worried this might be something more broad than the title implies. It doesn't seem to be related to the length of the lineage name, since DN.1 which is just as long looks fine. 
To me it looks like it doesn't recognize that B.1.1.529.5.3.1.1.1.1.1.1.2.1 is a child of B.1.1.529.5.3.1.1.1.1.1.1.2, because it isn't able to process B.1.1.529.5.3.1.1.1.1.1.1.2.1 at all. This extends back all the way, such that querying for B* wouldn't pull in DU.1

![image](https://user-images.githubusercontent.com/94097102/216459551-bff64127-f409-4723-b3e2-5b429649b86e.png)

![image](https://user-images.githubusercontent.com/94097102/216459602-ff9c5da7-c99d-43c7-8a54-e5dec6977833.png)

![image](https://user-images.githubusercontent.com/94097102/216459826-0579f01f-67c7-47a9-97ae-a3fb77ad94bf.png)

**Comment by chaoran-chen** [comment]
Thank you very much for pointing out this issue! The five newest Pango lineage aliases had not been propagated through the whole application. I just fixed it.
