### ISSUE TITLE
"assert" library is outdated and not working properly

### ISSUE THREAD

**Issue by chaoran-chen** [GenSpectrum/cov-spectrum-website#695]
We have a number of `assert()` statements using the ["assert" package](https://www.npmjs.com/package/assert). That package, however, isn't maintained anymore and not working properly. When an assertion fails, it throws an "assertion_error.js:392 Uncaught ReferenceError: process is not defined" error. We should get rid of the package.

**Comment by fengelniederhammer** [comment]
What should we do with the respective code? Should we simply delete the assertions or replace it by something else?

From looking at the code, we only use `assert(<boolean expression>)` only anyway. Something similar would be easy to implement ourselves.

**Comment by chaoran-chen** [comment]
I'm not sure. What's about using `console.assert` instead?

**Comment by fengelniederhammer** [comment]
`console.assert` sounds good.

**Comment by JonasKellerer** [comment]
I just tried to change all occurrences of assert. However, `console.assert` only writes an error message but does not throw an error. It seems to me that we want to keep the functionality to throw errors? So how about `assert` from [node](https://nodejs.org/docs/latest-v18.x/api/assert.html) ?

**Comment by fengelniederhammer** [comment]
Node doesn't work, as it's not available in the browser IIRC. Not throwing an error seems fine to me, as either the following code can cope with the failed assertion or it will fail anyway (in which case the `console.assert` output gives context to the error).

**Comment by chaoran-chen** [comment]
I agree with Fabian. In addition, we can adapt our Sentry setup (see Slack message that I sent a bit ago) to report error messages ([explained here](https://stackoverflow.com/a/56736902/8376759)).
