### ISSUE TITLE
When not using advanced search, first character entered for each term gets ignored. 

### ISSUE THREAD

**Issue by Sinickle** [GenSpectrum/cov-spectrum-website#696]
ie, if I want to search "s:486p, s:444t" I will have to type "ss:486p" enter, "ss:444t". Visually everything displays correctly, but the first button press doesn't make it in at all. 

I'm using google chrome, haven't tested on other browsers.

**Comment by chaoran-chen** [comment]
Oh, that's annoying. Thanks for reporting the issue!

**Comment by corneliusroemer** [comment]
Yep, I can confirm the issue on ARM Mac with Brave. Noticed yesterday, quite annoying indeed 😬 

Screencast:
![2023-02-06 16 42 12](https://user-images.githubusercontent.com/25161793/217016699-b572d924-e0d3-4afb-99ca-f0632bc0b02c.gif)

**Comment by FedeGueli** [comment]
i found that if you paste two times or digit two times it works (as temporary trick)

**Comment by corneliusroemer** [comment]
Yes, it just ignores the first stroke/action, everything after gets accepted
