### ISSUE TITLE
BUG: Some regions in China not matched due to spelling differences

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/cov-spectrum-website#697]
Querying for all lineages in China, I noticed that some regions don't seem to be mapped correctly to the map.

For example, there definitely are sequences from `Shanxi` but GISAID seems to map these as `Shaanxi`.

Given attention on China it may be good to fix the mappings.

<img width="1104" alt="image" src="https://user-images.githubusercontent.com/25161793/217018818-069786a6-b757-4ff1-a9c0-10dd9587cb14.png">

https://cov-spectrum.org/explore/China/AllSamples/Past6M/variants?&

**Comment by AnonymousUserUse** [comment]
Note that Shanxi (Chinese: 山西; pinyin: Shānxī) and Shaanxi (Chinese: 陕西; pinyin: Shǎnxī)i are two different provinces in China. See also: https://en.wikipedia.org/wiki/Shaanxi#Name.

Besides, there are following problems with spelling differences for regions in China:
Guangxi Zhuang vs. Guangxi
Xinjiang Uygur vs. Xinjiang
Quinghai vs. Qinghai

**Comment by JonasKellerer** [comment]
We had a look at it and found indeed some spelling mismatches. @chaoran-chen @corneliusroemer at which end should we fix that? Should we change the mapping in the  [GeoLocationRules](https://github.com/nextstrain/ncov-ingest/blob/master/source-data/gisaid_geoLocationRules.tsv) or implement our own mapping in LAPIS?

However, we also found three instances, where there was no data from LAPIS. @chaoran-chen could you check if there are entries in the database?

![Image](https://user-images.githubusercontent.com/122305307/218695284-c32b7144-8816-4e0d-b9f1-44cde0ac4661.png)

**Comment by chaoran-chen** [comment]
- Ningxia and Qinghai: I think both the name in LAPIS and the name in the map data are alright, so for simplicity, I'd change the [JSON map data](https://github.com/GenSpectrum/cov-spectrum-website/blob/develop/src/maps/china.json)
- Qinghai vs. Quinghai: is the latter just wrong/a typo? If yes, it should also be fixed in our map data.
- Macau: we have a separate country "Macao" with one sequence.
- Xizang: can't find any data in LAPIS either.
- Guangxi Zhuang: LAPIS has "Guangxi", so we could change the map data to be the same.

**Comment by chaoran-chen** [comment]
I wonder whether there is really not a single sequence available from Xizang/Tibet or if we are missing something. @AnonymousUserUse, do you happen to have some insights?

**Comment by fengelniederhammer** [comment]
According to Google, Quinghai is a typo: https://www.google.de/search?q=Quinghai

**Comment by AnonymousUserUse** [comment]
> * Qinghai vs. Quinghai: is the latter just wrong/a typo? If yes, it should also be fixed in our map data.

I think the latter is just a typo.


> I wonder whether there is really not a single sequence available from Xizang/Tibet or if we are missing something. @AnonymousUserUse, do you happen to have some insights?

There are sequence data from Xizang in the surveillance report of China CDC (https://weekly.chinacdc.cn/). So I think it is probably the problem that researchers in Xizang do not upload their sequences to GISAID. It would be interesting to see how BA.2.76 is currently mutated in Xizang, which has been circulated since August 2022.
![image](https://user-images.githubusercontent.com/113214374/218709427-6637425d-b938-4a37-9d60-c09047aa5baf.png)

**Comment by fengelniederhammer** [comment]
That sounds like Xizang/Tibet is not an issue that we can fix on our side, so #720 should close this issue.

**Comment by corneliusroemer** [comment]
Thanks a lot everyone for looking into this! In general, the same issue may also be present for other countries and their regions. May be worth having a look at the big ones, like USA, India...

Regarding Shanxi/Shaanxi, I only see one in your table, but there are definitely both in GISAID. @JonasKellerer 

It may be worth getting GISAID credentials for you @fengelniederhammer @JonasKellerer - have you requested them already? Then some checks are easier to do immediately ;)

Indeed there is nothing on GISAID from Xizang or Tibet.

**Comment by chaoran-chen** [comment]
Both Shanxi and Shaanxi are available on the map:

![image](https://user-images.githubusercontent.com/18666552/218777699-ba3eed59-15a7-4e6c-a231-b0e157766352.png)

![image](https://user-images.githubusercontent.com/18666552/218777762-d73787fd-df92-4676-a769-372ab147965c.png)

**Comment by corneliusroemer** [comment]
Ah great! Thanks @chaoran-chen 

Silly me :D

**Comment by fengelniederhammer** [comment]
> Regarding Shanxi/Shaanxi, I only see one in your table, but there are definitely both in GISAID.

They are both present: line 9 and line 21 (we should have sorted the table alphabetically ;) )

**Comment by fengelniederhammer** [comment]
We requested credentials for GISAID, but didn't get them yet.

**Comment by corneliusroemer** [comment]
Regarding US, the map misses: Alaska, Puerto rico, Hawaii

India strangely has no map at all? 
<img width="1570" alt="image" src="https://user-images.githubusercontent.com/25161793/218778490-c092d42e-79fe-48e3-927b-a1017fba0044.png">

Brazil has a few mismappings (states with accents?) like Amapa: 
<img width="461" alt="image" src="https://user-images.githubusercontent.com/25161793/218778850-762127b6-6a5e-4e3f-ad8b-ece80206be82.png">

<img width="923" alt="image" src="https://user-images.githubusercontent.com/25161793/218778901-3ae08df1-e37b-42db-9ece-89a4598bd633.png">


This could be a good project for someone from the community who wants to help! Maybe add `help wanted` label and explain how to check states :)

@fengelniederhammer hmm, :/ when did you request? 

Btw there are 2 other Chinese provinces with no recent data (though data from pre-recent): Guanxi and Hebei.
