### ISSUE TITLE
Country switching redirects to landing page for countries with a space in the name

### ISSUE THREAD

**Issue by chaoran-chen** [GenSpectrum/cov-spectrum-website#704]
@JosetteSchoenma pointed out to me (thank you!) that switching the country on a variant page sometimes redirects to the landing page. It seems to only happen for countries with a space in its name and I suspect that it was introduced in #680 in a bug that was (apparently only partially) addressed in be0ec6cacfd986f29e7d1cadce4d48c67dfd2e88.

**How to reproduce:**

1. Go to [here](https://cov-spectrum.org/explore/United%20Kingdom/AllSamples/Past6M/variants?variantQuery=nextcladePangoLineage%3Aba.5*+%26+%21nextcladePangoLineage%3ABQ.1*&)
2. Select another country, let's say Germany

**Expected result:**

[This page](https://cov-spectrum.org/explore/Germany/AllSamples/Past6M/variants?variantQuery=nextcladePangoLineage%3Aba.5*+%26+%21nextcladePangoLineage%3ABQ.1*&) is opened

**Actual result:**

[This page](https://cov-spectrum.org/explore/Germany/AllSamples/Past6M) is opened

**Comment by JosetteSchoenma** [comment]
I don't know why this issue has been closed, but as far as I can see, the problem has not been solved.
Do I have to wait for an update?
