### ISSUE TITLE
Open data last updated on 2023-01-20, about 2 weeks ago

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/cov-spectrum-website#710]
Just noticed that the open data was last updated ~2 weeks ago

Seems to be known and worked on, see https://github.com/GenSpectrum/LAPIS/issues/86

<img width="799" alt="image" src="https://user-images.githubusercontent.com/25161793/217948318-e0a92693-171d-4015-b305-5a80a9fbaf8e.png">

**Comment by chaoran-chen** [comment]
This was solved together with https://github.com/GenSpectrum/LAPIS/issues/86.
