### ISSUE TITLE
Adding a new term to an advanced search can cause the text to flicker back and forth..?

### ISSUE THREAD

**Issue by Sinickle** [GenSpectrum/cov-spectrum-website#711]
I'm definitely missing some details on this one. It should be highly reproducible yet inconsistent though. 

Version A:
When I'm editing collections such as 37, when I go to add a new term to my advances queries (ie, !s:147e), I can enter a few characters without issue, but then a few after that will have an issue where they flicker back and forth. Further characters I add to it after this also flicker back and forth. (meaning, they appear and then disappear rapidly). This issue resolves itself unpredictably after I add or delete some text. The issue does not resolve itself on its own. The issue can come back without me exiting the field. 
This can also happen immediately after switching a query to be regular to advanced, and trying to add a new term. 

Version B: 
I can cause the issue just by doing an advanced search on the main site, outside of a collection. Add in a term, search, add in another term, search, add in another term, search, etc. I strongly suspect this comes down to speed/if you are trying to add terms while the system is still processing something.. from what I can tell, if you click search and then go and add something (ie, &s:452m) quickly, the issue will happen. Additionally, I have gotten the issue to happen a similar way but by clicking the "advanced search" button to toggle between it. This causes the button to flicker back and forth. 

I believe this issue may have started at the same time as #696, but the issue definitely did not exist on Feb 2.

**Comment by corneliusroemer** [comment]
Highly reproducible yet inconsistent is quite contradictory ;)

Can you make a screen recording using something like Gifox? A picture is worth a thousand words :)

Which browser did this appear on? OS? Have you tried another browser? What's your computer? Especially if it's due to thread blocking it may be hard to reproduce on a high end machine.

I can't reproduce.

**Comment by Sinickle** [comment]
Haha it was reproducible in the sense that I could reproduce it within 20 seconds, but inconsistent in the sense that if I wrote a test script, I couldn't tell you which step would produce the bug. 
Today it is happening much less frequently, and i haven't been able to capture a good gif of it. I'll post one if I have a day where it is very reproducible for me again though. 

I'm on Windows, Chrome. I'll test edge if I have a day where it is happening frequently again. I'm definitely not using a high-end machine, and did get the sense it had to do with performance in some way. 

Here are 2 gifs I got though. The first one, it erases my 4 although I didn't do anything to delete it. Yesterday this would happen before the flickering effect. 
The second one is the flickering effect, but unfortunately I didn't record the steps that led to it, which I believe was exiting the field, coming back in a bit, clicking into it, and starting to add a new term. 
![testThing4](https://user-images.githubusercontent.com/94097102/218134709-b7dd8992-5514-442d-8531-694b0f081f01.gif)
![testThing5](https://user-images.githubusercontent.com/94097102/218134724-113f0c78-dc5d-48ac-b9b1-5e30fe7eafaa.gif)

**Comment by Sinickle** [comment]
Okay here's a better one. Will test on other browser later.
![testThing7](https://user-images.githubusercontent.com/94097102/218149510-49b0320c-7fe5-408f-9e80-f140c3a5b139.gif)

**Comment by corneliusroemer** [comment]
Thanks for the casts! Looks like some key stroke handling thing, possibly in combination with performance.

You could make the cast even better if you used one that included the keys you hit. Gifox does that for example :)

**Comment by JonasKellerer** [comment]
We could reproduce the bug, when typing in the advanced search field.:

1. Type in advanced search field S:129T and hit search
3. Add &S:129 and hit search 
4. redo 3. until bug appears

It is  easier to reproduce on a slower machine, but we also managed to show it on a faster machine.

**Comment by fengelniederhammer** [comment]
@Sinickle Could you please check whether the issue still occurs on the Vercel deployments of #714?
(e.g. https://cov-spectrum-develop-git-variantserachflicker-cov-spectrum.vercel.app/)

At least we could not reproduce the issue on our local machines anymore.

**Comment by Sinickle** [comment]
Sorry for the delay -- but I agree this seems fixed now!
