### ISSUE TITLE
Bug: the lineage/mutation input bar is malfunctioning 

### ISSUE THREAD

**Issue by FedeGueli** [GenSpectrum/cov-spectrum-website#712]
i am ahving a lot of issues in copying pasting to the lineage search bar, when i set a different timeset i lose everything, also in collection i cant add mutations to my query that everything goes messed up.
<img width="198" alt="Schermata 2023-02-10 alle 15 46 35" src="https://user-images.githubusercontent.com/87669813/218120535-f5ef1541-34c5-4d94-b7a3-9336d2e99cda.png">
i am adding a lineage to a collection it doesnt take the first letter and when i try to modify it erases all the query.

**Comment by corneliusroemer** [comment]
Duplicate https://github.com/GenSpectrum/cov-spectrum-website/issues/696

This would be good to be fixed rather soon 🙃
