### ISSUE TITLE
Redirecting to the country of the user is not working

### ISSUE THREAD

**Issue by chaoran-chen** [GenSpectrum/cov-spectrum-website#750]
When opening the landing/root page (e.g., https://cov-spectrum.org), the user should be redirected to the page of their current country based on the IP address. This does not seem to work anymore. Instead, the website is always opening the page for Europe (which is the fallback region).

**Comment by corneliusroemer** [comment]
I do like that actually. I thought this was a feature. I was never a fan of the country detection. Countries can be very small, also maybe don't have much data, and it's getting less.

I understand that maybe in the US you can make an exception. But say if you're in San Marino, we shouldn't select San Marino.

I think at the current point in the pandemic there's a big case to make region the user's default.

As fallback I'd use world not Europe.

As it's strange if you're shown a specific location if you're not in the region. Better to go too general than specific.
