### ISSUE TITLE
Tooltips of wastewater plots are not completely visible

### ISSUE THREAD

**Issue by chaoran-chen** [GenSpectrum/cov-spectrum-website#788]
On https://cov-spectrum.org/stories/wastewater-in-switzerland, the lower part of the tooltips is not visible.

![image](https://user-images.githubusercontent.com/18666552/234278763-4967d450-9b66-41e4-ba1e-788d916f178d.png)

**Comment by AnonymousUserUse** [comment]
Same problem occurs when one chooses too many variants in the function "Compare variants" etc..
https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?nextstrainClade=22A&nextstrainClade1=22B&nextstrainClade2=22C&nextstrainClade3=22D&nextstrainClade4=22E&nextstrainClade5=22F&nextstrainClade6=23A&nextstrainClade7=23B&analysisMode=CompareEquals&
![image](https://user-images.githubusercontent.com/113214374/235374241-11b8f862-921e-405b-9d0d-57dd4edf2de2.png)

**Comment by JonasKellerer** [comment]
Thanks for the feedback. I will look into this.

**Comment by JonasKellerer** [comment]
![image](https://user-images.githubusercontent.com/122305307/235632187-e630300a-a3f2-4bfb-8268-cbc96c8cdee7.png)
I found also this
