### ISSUE TITLE
Use fields param for faster loading

### ISSUE THREAD

**Issue by tehwalris** [GenSpectrum/cov-spectrum-website#80]
The `samples2` endpoint can now return a subset of fields, which makes requests significantly faster. We should use this in our requests, especially for `wholeInternationalSampleSet` which takes very long.

**Comment by chaoran-chen** [comment]
A lot has changed since then (e.g., caching was introduced on the server). We will have to re-evaluate whether using the fields param is a good idea and determine what's really helpful to improve the performance.
