### ISSUE TITLE
White screen after search

### ISSUE THREAD

**Issue by chaoran-chen** [GenSpectrum/cov-spectrum-website#818]
@corneliusroemer observed that clicking on search would make the screen go white. After a reload, it works again.

![2023-06-21 13 56 35](https://github.com/GenSpectrum/cov-spectrum-website/assets/18666552/f4e3555f-22d7-4b08-8e85-ec1d8df5afe6)

**Comment by chaoran-chen** [comment]
The console shows that Plotly is throwing an error but it’s not obvious to me why. The last big change that we made was #784 but as far as I remember, it does not use Plotly? 

![image](https://github.com/GenSpectrum/cov-spectrum-website/assets/18666552/f91a2243-8a93-40cf-9dd9-de53a0491dd3)

**Comment by corneliusroemer** [comment]
Upstream issue: Plotly had a CDN issue. Now fixed. Maybe ship yourself instead of using their CDN.
https://github.com/plotly/plotly.js/issues/6648
