### ISSUE TITLE
Collections have been swamped with 20k script created collections

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/cov-spectrum-website#833]
Someone seems to have created more than 20k collections with a script completely overwhelming the current collection overview page:
<img width="1964" alt="image" src="https://github.com/GenSpectrum/cov-spectrum-website/assets/25161793/75017e0b-f5fe-4922-bae9-8a4cfe6a29c9">

**Comment by chaoran-chen** [comment]
Annoying.. I deleted them. Hopefully, this is a one-time thing and I don't need to add a captcha and/or registration. Thanks for letting me know!
