### ISSUE TITLE
The sequence data weren't updated today?

### ISSUE THREAD

**Issue by oobb45729** [GenSpectrum/cov-spectrum-website#853]
I'm not so sure about it, but the numbers does not seem changed (for several lineages I am tracking) after the latest sequence data update today.

**Comment by corneliusroemer** [comment]
Agree, also noticed. To confirm we can do an advanced filter by submission date. Prediction is that there's nothing submitted after around 5th of September.

**Comment by corneliusroemer** [comment]
Bingo, most recently submitted sequences are from 31st of August 🫣

**Comment by chaoran-chen** [comment]
Thank you very much for reporting the issue! It has been fixed now and new data are online.
