### ISSUE TITLE
Adapt to LAPIS v2

### ISSUE THREAD

**Issue by chaoran-chen** [GenSpectrum/cov-spectrum-website#855]
We are soon ready to test CoV-Spectrum with LAPIS v2! :) We can start with using the test instance to be set up in https://github.com/GenSpectrum/LAPIS/issues/371.

**Comment by JonasKellerer** [comment]
use case of config for filters
- currently LAPISv1 uses upper case

**Comment by chaoran-chen** [comment]
In LAPIS 2, could we make the field and filter names case-insensitive? I.e., `?couNTRY=...&FielDS=REGIon` should work. (The filter values should remain case-sensitive.)

**Comment by fengelniederhammer** [comment]
We would need to implement that in SILO, as a simple `lowercase` in LAPIS doesn't do the job, (e.g. for a camel case field such as `pangoLineage`). We can of course implement that. But I wonder whether that's worth the effort. We usually have quite readable error messages that tell the user what valid fields are.

Also this does not solve all "case issues" as it isn't purely about upper or lower case characters (`pangoLineage` vs `pango_lineage`).

**Comment by chaoran-chen** [comment]
I'm not sure that I fully understand the difficulty. LAPIS knows the correct capitalization that SILO expects, right? I.e., couldn't we maintain a map in LAPIS from lowercase to the right capitalization for each field (`pangolineage -> pangoLineage`)?

If it is easy and fast to make it case-insensitive in LAPIS, I think that'd be the preferred solution as we should minimize the breaking changes. (After having LAPIS 2 fully launched and stable, we need to think about the general migration path from v1 to v2. We'll probably have to write a few redirects that we support for a while so that other users of the open LAPIS don't experience an abrupt break.)

(`pangoLineage` vs `pango_lineage` of course wouldn't be solved by this but, I feel, that's a bit different.)

**Comment by fengelniederhammer** [comment]
Ok, then let's do it in LAPIS. In all cases where fields matter? Or only in the "fields" field in /aggregated and /details?
