### ISSUE TITLE
BUG: Wrong dataset version shown in footer

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/cov-spectrum-website#862]
The footer claims your dataset version is `Nextclade dataset version: 2023-09-21T12:00:00Z`

But it definitely isn't given that things like `XCH` return 0 results

https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?nextcladePangoLineage=XCH*&

<img width="1659" alt="image" src="https://github.com/GenSpectrum/cov-spectrum-website/assets/25161793/fc54d643-1d7c-4271-a4a8-095e76c375b1">

Also, the update time has not changed, only the version. So maybe something to do with current lapis upgrade?

**Comment by corneliusroemer** [comment]
Now the data is updated, so should be good.

```
The sequence data was updated: Today at 4:44 PM
Nextclade dataset version: 2023-09-21T12:00:00Z
```

**Comment by chaoran-chen** [comment]
Closing as this is outdated.
