### ISSUE TITLE
Update "Wastewater in Switzerland" "stories" page

### ISSUE THREAD

**Issue by mcarrara-bioinfo** [GenSpectrum/cov-spectrum-website#867]
The overall structure of workflow changed, with different parties involved in sample collection and different treatment plants being sampled.

As in the past, we compiled a google docs (https://docs.google.com/document/d/1dTS0C7Y_LJZuPr5zUyCRVZ5CurbvK24NuNcssyNgH20) with the updated text

**Comment by JonasKellerer** [comment]
@mcarrara-bioinfo I tried to change the text as you requested and created a draft pull request #868. However in the google-docs there seems to be some comment hidden behind "[CURVES]". Could you provide me with this info or is this only coloring?

**Comment by mcarrara-bioinfo** [comment]
@JonasKellerer The part you mention is only highlighted. There are no open comments in the document that are relevant to this issue.
I looked at the preview and commented on the PR
