### ISSUE TITLE
Embed-widget design

### ISSUE THREAD

**Issue by chaoran-chen** [GenSpectrum/cov-spectrum-website#87]
As we are going to embed plots from CoV-Spectrum on the website of the science taskforce (and possibly elsewhere) as soon as we go public, I wanted to ask whether you have some ideas on improving the design of the embed-widget.

The current "header" of the widget:

![image](https://user-images.githubusercontent.com/18666552/115143700-293f4080-a049-11eb-9787-c653676e5f67.png)

(@tehwalris, @TKGZ  :))

**Comment by spacephoton** [comment]
Yes! I'll have a look and provide suggestions. Not happy with how the bottom ticks are functioning.

**Comment by spacephoton** [comment]
Are we also interested in multilingual titles?

**Comment by chaoran-chen** [comment]
No, we don't need to think about multilingualism.

**Comment by chaoran-chen** [comment]
A border and a better text were added. That should be enough for now.
