### ISSUE TITLE
Reminder to add "2024"  Option on Covspectrum

### ISSUE THREAD

**Issue by FedeGueli** [GenSpectrum/cov-spectrum-website#899]
Happy new year everyone!
Just a short reminder to add the 2024 option for Covspectrum  in the custom/preselected time set options

Thank you!

**Comment by chaoran-chen** [comment]
Happy New Year, @FedeGueli! Thank you very much for the reminder!

**Comment by FedeGueli** [comment]
> Happy New Year, @FedeGueli! Thank you very much for the reminder!

Thank you Chaoran! U re as usual the best!
