### ISSUE TITLE
"wastewater in Switzerland" page text and layout update

### ISSUE THREAD

**Issue by mcarrara-bioinfo** [GenSpectrum/cov-spectrum-website#931]
Sampling strategy changed for 2024. The stories page "wastewater in Switzerland" should be updated to reflect it in both the layout and the text.

We have a google document describing the necessary changes [at this link](https://docs.google.com/document/d/1cEdrvw26P4QlfcU3dOO9SFhUGRsov6w0xh6skAATZcA/edit?usp=sharing). Differences from the original have been highlighted in yellow. Where necessary links are embedded.

**Comment by mcarrara-bioinfo** [comment]
Is there any update on this front?

**Comment by DrYak** [comment]
Created  PR  #957 

- this *does* update  the *text*
- I am  not attempting to split out the legacy in a separate grid as I don't have the necessary webdev skills.

**Comment by chaoran-chen** [comment]
Sorry for the delay and thank you very much for the PR!

> I am not attempting to split out the legacy in a separate grid as I don't have the necessary webdev skills.

We'll do it soon!
