### ISSUE TITLE
Some collections fail to load

### ISSUE THREAD

**Issue by Sinickle** [GenSpectrum/cov-spectrum-website#932]
After the update last week, certain collections now fail to load for me on PC in chrome, as well as on my Android phone on a chrome browser (haven't tried others). 

The UI loads properly, and then a spinning circle appears in the variants table as normal when a collection is loading -- after a few seconds, the whole page goes white and there is no loading symbol or UI anymore. 

As just a few examples -- collection 24 and 169 have this issue for me, while collection 42 does not.

**Comment by chaoran-chen** [comment]
Thanks for the bug report!

For [collection 24](https://cov-spectrum.org/collections/24), the size (1182 variants) might be causing a problem (although I definitely think that we should be able to support it) but [collection 169](https://cov-spectrum.org/collections/169) has only 75 variants which is smaller than collection 42 (103 variants). We'll work on it!

**Comment by fengelniederhammer** [comment]
This is very likely a load problem. We are investigating in https://github.com/GenSpectrum/LAPIS-SILO/issues/298, so I'll move this to blocked for now.

**Comment by corneliusroemer** [comment]
I confirm that I also (sometimes) can't load collection 42, for example. Getting error 500

<img width="2542" alt="image" src="https://github.com/GenSpectrum/cov-spectrum-website/assets/25161793/b7cf8172-0ab5-4893-bf30-fee63ce1b5aa">

```json
{
    "error": {
        "type": "about:blank",
        "title": "Internal Server Error",
        "status": 500,
        "detail": "Could not connect to silo: class java.io.IOException HTTP/1.1 header parser received no bytes"
    },
    "info": {
        "dataVersion": null,
        "requestId": "fd8424b4-b1f8-406c-9ee7-a8fc4adddf3f"
    }
}
```

**Comment by fengelniederhammer** [comment]
The collections now load (although it may take a while). See https://github.com/GenSpectrum/LAPIS-SILO/issues/298#issuecomment-1970965529. So I'm closing this.

We will continue to work on improving response times.
