### ISSUE TITLE
Query with `.` no longer searches for unmutated

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/cov-spectrum-website#938]
Before the recent LAPIS changes, when querying for something like `23271.` it showed all sequences that had 23271 genotype of reference/unmutated.

This no longer seems to be the case. I get almost nothing for `23271.` but lots for `23271C` (C being reference):

https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?nucMutations=23271C&:
<img width="1475" alt="image" src="https://github.com/GenSpectrum/cov-spectrum-website/assets/25161793/ddffa4af-a850-44e0-9ecb-e8c94ff053a8">

https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?nucMutations=23271.&:
<img width="1456" alt="image" src="https://github.com/GenSpectrum/cov-spectrum-website/assets/25161793/e61def0a-91cd-49ae-ac72-53a3553abb4e">

**Comment by JonasKellerer** [comment]
This should be fixed by https://github.com/GenSpectrum/LAPIS-SILO/pull/341 .

**Comment by JonasKellerer** [comment]
https://github.com/GenSpectrum/LAPIS-SILO/pull/341 is merged.
Lets wait for the next update of SILO for production. Then we can check again and hopefully close this.

**Comment by JonasKellerer** [comment]
After restart both urls you provided show the same count. So I close this issue.
